- .travis.yml
- Makefile
- config/config_test.go
almost the same as we've been doing in coreos-kubernetes
builds are passing as we can see in https://travis-ci.org/mumoshu/kube-aws/builds/169114009
> Enable Travis CI builds

- config/config.go
- config/templates/cluster.yaml
- config/templates/stack-template.json
This toggle still requires the operator to bootstrap the VPC with a NAT gateway, but i think it's fair to expect the operator to do this manually/with external tooling.
I might send a subsequent PR to add functionality to create a NAT gateway from kube-aws. Gateway initialization takes several (sometimes 5+) minutes though, so i'm slightly worried cluster bootstrap might be affected.
> Simple toggle to stop the automatic assignment of public IP's for all the nodes.

- config/templates/stack-template.json
```
$ ../bin/kube-aws validate
Validating UserData...
UserData is valid.
Validating stack template...
Error: Failed to render stack template: template: stack-template.json:344:42: executing "stack-template.json" at <.MapPublicIPs>: can't evaluate field MapPublicIPs in type config.etcdInstance
```
```
$ ../bin/kube-aws validate
Validating UserData...
UserData is valid.
Validating stack template...
Error: Failed to render stack template: template: stack-template.json:802:33: executing "stack-template.json" at <.MapPublicIPs>: can't evaluate field MapPublicIPs in type string
```
> fix MapPublicIPs in stack template

- .gitignore
- e2e/README.md
- e2e/kubernetes/Dockerfile
- e2e/kubernetes/Makefile
- e2e/kubernetes/conformance.sh
- e2e/run
I'd like to add a set of Dockerfile, Makefile, and a shell script to easily build docker images to run the k8s e2e test suite including conformance tests, run it locally or remotely(on k8s controller nodes with manually modified controller security group with 10250 opened, to fully test things like e.g. cAdvisor/Prometeus related ones)
Beware that you should be running at least 4 m3.medium instances for k8s worker nodes to pass tests related to the horizontal pod autoscaler
> feat(test): Implement an easier way to run k8s conformance tests against kube-aws-provisioned cluster

- cmd/kube-aws/command_init.go
- config/config.go
- config/templates/cluster.yaml
There's no official AMIs for CoreOS in China region. This PR make it possible to launch an instance by a user specified AMI.
> allow to override the ami id of coreos

- config/config.go
- config/templates/stack-template.json
The `Service` in IAM profile is different in Global regions and China region. It's a little bit ugly to expose a var named `IsChinaRegion`, but I don't know whether there is a better way to fix this.
> add a new var IsChinaRegion to fix for China Region

- build
- build-release-binaries
Having `GOOS=darwin` on my fedora box causes `go generate` to fail with a weird error. This fixes that problem (encountered when building release binaries).
\cc @mumoshu
> [build] only set target os/arch for compile

- cmd/kube-aws/command_render.go
Note that it will overwrite all the other TLS assets. I think this is okay or maybe even desired. This will at least prevent some harm..
fixes #16
> Don't overwrite the CA by default on deprecated 'render' command

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
- config/templates/stack-template.json
This still needs some work but i think it currently qualifies and fills a need.
Creating (and later finding) an EFS volume through cloudformation is more trouble than it's worth so the option currently requires an existing EFS-id. We can later turn this into an option which requires a unique id for creating the volume. We'd need to create the volume before we evaluate the stack-template though and my Go skills are still quite rusty so i think it's better to do that in a separate PR.
(nearly) fixes #10
> Add option to mount existing Amazon EFS volume.

- config/templates/stack-template.json
Not everything is tagged with a name which means the AWS console gets filled with empty named resources, this helps fix it up so they are easier to identify especially with multiple k8s stacks.
A replacement of https://github.com/coreos/coreos-kubernetes/pull/717.
> Add name tags where applicable

- config/templates/stack-template.json
Goes some way to resolve coreos/coreos-kubernetes/issues/620, a replacement of https://github.com/coreos/coreos-kubernetes/pull/731.
> Allow ECR pull from controller IAM role

- config/templates/cloud-config-worker
Systemd only allows "Restart=no" for  "Type=oneshot" services.
> Remove "Restart=on-failure" from kube-node-drainer.service

- config/templates/cloud-config-worker
Fix `kube-node-drainer.service` `ExecStart` and `ExecStop` errors . #40
> Replace docker with rkt in "kube-node-drainer.service".

- .gitignore
- containerized-build-release-binaries
`rkt run` was doing some weird stuff on fedora machines with SELinux in enforcing mode, so we're back to docker for the containerized build wrapper.
After this, we'll be ready to cut `v0.9.1`.
\cc @mumoshu
> build: fix up containerized release build process

- cluster/cluster.go
- cluster/cluster_test.go
- cmd/kube-aws/command_up.go
- cmd/kube-aws/command_update.go
- cmd/kube-aws/command_validate.go
- e2e/run
If you are hit by the cloudformation limit, `kube-aws up` now fail with a specific error explaining the limit and how to work-around it:
```
$ kube-aws up
Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: stack-template.json size(=51673) exceeds the 51200 bytes limit of cloudformation. `--s3-uri s3://<bucket>/path/to/dir` must be specified to upload it to S3 beforehand
```
As the error message says, if you provide the `--s3-uri` option composed of a s3 bucket's name and a path to directory, `kube-aws` uploads your template to s3 if necessary:
```
$ kube-aws up --s3-uri s3://mybucket/mydir
```
resolves #38 (for now)
> feat: `kube-aws up --s3-uri s3://<bucket>/<directory> to automatically avoid the 51200 bytes limitation errors of CloudFormation

- config/templates/cloud-config-etcd
Exporting  etcdctl environment variables, allow cluster managers to run etcdctl commands without providing arguments.
Currently when you logging in the etcd cluster you can't run etcdctl commands except you provide all the args.  
```
$ etcdctl --cert-file=/etc/etcd2/ssl/etcd-client.pem --ca-file=/etc/etcd2/ssl/ca.pem --key-file=/etc/etcd2/ssl/etcd-client-key.pem  --endpoints=https://ip-10-0-0-5.eu-west-1.compute.internal:2379 cluster-health
member f5654f631de6e415 is healthy: got healthy result from https://ip-10-0-0-5.eu-west-1.compute.internal:2379
cluster is healthy
```
After this PR will be easy for run etcdctl commands
```
$ etcdctl cluster-health
member f5654f631de6e415 is healthy: got healthy result from https://ip-10-0-0-5.eu-west-1.compute.internal:2379
cluster is healthy
``` …
> Easily manage etcd cluster with env vars

- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
EFS can obviously only be mounted if we have a network.
> EFS systemd unit start ordering.

- cmd/kube-aws/command_up.go
- cmd/kube-aws/command_update.go
- cmd/kube-aws/command_validate.go
- kube-aws up, update, and validate all feature the --s3-location flag.
Users would benefit from knowing the format expected when specifying
their S3 bucket. This commit adds an example to each instance of the
flag.
> cmd/kubeaws: Add S3 location format to help flag

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
- config/templates/stack-template.json
This enables users to to pass AWS cloudformation stack references in environment variables to custom scripts.
Use 'EnvironmentFile=/etc/aws-environment` in systemd units to consume the variables.
Fixes #29
> Add experimental feature "awsEnvironment".

- e2e/run
* easier ways to connect worker/controller via ssh
* supress verbose logging while waiting for kube-apiserver to be up
* differentiate s3-uri for each cluster so that we can safely run multiple e2e tests with different configurations in parallel
* set KUBE_AWS_USE_CALICO envvar to provision clusters with calico enabled
* print startup time taken since `kube-aws up` until apiserver becomes responsive so that I could notice unexpected effects to startup time more
* Make nodes count smaller because conformance tests seem to pass with 2 nodes now
> Various improvements to kube-aws e2e testing script

- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
PR #79 introduced a static reference to `ap-northeast-1`.
> Fix static reference to AWS region

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
- config/templates/stack-template.json
This PR make some improvements when creating or updating cluster. #49 
When the resources are creating, cfn-signal will monitor specific services to check if they are healthy. Only after all service are healthy, it send a successful signal to Cloudformation.  The same monitoring will be applied on update command, now we have consistent status for rolling updates.
On the node controller, cfn-signal will check the status for: calico if enabled, scheduler, api-server, controller-manager and kubelet. 
```
...
/usr/bin/curl -s -m 20 -f  http://127.0.0.1:8080/healthz > /dev/null &&
/usr/bin/curl -s -m 20 -f  http://127.0.0.1:10252/healthz > /dev/null && 
/usr/bin/curl -s -m 20 -f  http://127.0.0.1:10251/healthz > /dev/null &&  
/usr/bin/curl --insecure -s -m 20 -f …
```
> Send sucesss signal to cloudformation when controllers and workers are ready

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-etcd
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
Apart from the calico image users can host cluster assets themselves.
I mostly want this so i can easily test contributions to https://github.com/coreos/awscli
> Add configuration option for AWS CLI image

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
- config/templates/stack-template.json
In preparation for node cordoning/uncordon process 1/2
I think it's safer to have an easy way to disable this while we work on it.
Note that this reverts the PauseTime to 2 minutes and the `WorkerCreateTimeout` / `ControllerCreateTimeout` remain top level variables.
> Shield cfn-signal behind experimental flag.

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-etcd
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
So cluster operators don't have to share the same SSH public key.
Suggested workflow:
- Keep a main organization key (`keyPair`) in a keysafe. Don't use it for normal daily operations.
- Add a select number of cluster operators to the `sshAuthorizedKeys` list
> Add cloudinit sshAuthorizedKeys option to cluster.yaml

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
- config/templates/stack-template.json
Currently adds:
Labels:
- `kube-aws.coreos.com/autoscalinggroup` = autoscalinggroup the node belongs to
- `kube-aws.coreos.com/launchconfiguration` = launchconfiguration of the autoscalinggroup during node intialization
Annotations:
- `kube-aws.coreos.com/securitygroups` = comma separated list of security groups attached to node
> Add additional AWS labels and annotations to node

- config/templates/cloud-config-controller
`Scheduled Jobs` from 1.4 was renamed to  `Cron Jobs` in 1.5.
This PR works with both versions.
More info here:
http://kubernetes.io/docs/user-guide/cron-jobs/
> Enable Scheduled Jobs in k8s 1.4  aka Cron Jobs in 1.5

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
Intended to be used on instances that come with local storage (eg the `m3`, `c3`,`r3` and`g2` instance types).
When just setting the  `enabled` flag it formats (XFS) & mounts the local `xvdb` disk by default to the appropriate location (depending on container runtime). I chose XFS because of speed and the generous amounts of inodes by default.
Users can choose the filesystem and source disk by overriding the defaults:
```yaml
experimental:
ephemeralImageStorage:
enabled: true
disk: xvdc
filesystem: ext4
```
:warning: i haven't tested `rkt` as container runtime yet but i guess this will work? :crossed_swords: 
I would like to add the option to RAID together some local disks. The defaults should work all nodes with local storage, but doesn't use additional disks which is a waste if you move …
> Add option to mount ephemeral disks for image storage

- config/config.go
- config/templates/cluster.yaml
- config/templates/stack-template.json
This is useful for operators that have special ELB requirements like the proxyprotocol or where loadbalancer/network asset management is delegated to a different team.
> Option to automatically assign externally managed ELBs to the worker autoscaling group

- codegen/templates_gen.go
- config/config.go
which has been used for embedding config/templates/* files into go structs hence kube-aws binaries, from the config package to its own package, so that we can reuse it from the upcoming node pools feature.
I'm merging this without mentioning anyone because recalling recent pull requests turns out that no one seems to touch or use this code :)
> refactoring: Move the code generator

- config/config.go
Config() func had been returning inconsistent result for each call by incrementing private IPs statically assigned to etcd nodes in configuration time.
This has never affected clusters created via kube-aws but does break the upcoming node pools feature. So I'm fixing this now.
> fix: Remove problematic states from Config objects

- config/config.go
- config/tls_config.go
- filereader/jsontemplate/jsontemplate.go
- filereader/texttemplate/texttemplate.go
- filereader/userdatatemplate/userdatatemplate.go
- gzipcompressor/gzipcompressor.go
We'd been doing text/json/userdata templating in a specific package(=`config`).
While doing the same templating in the implementation of the node pools feature, it turned out that it is time to reveal what is the common sense of "templating" in kube-aws and what can be reused.
I've made each of the text, json and userdata templating resides in their own packages, and placed them under the umbrella package renamed `filereader` because the templating happens while reading files e.g. `user-data/cloud-config-*` and `stack-template.json` templates initially generated via `kube-aws render` but can be modified by users, hence they're `reader`s rather than `templator`s.
> Extract templating and compressing

- config/config.go
- coreos/amiregistry/amiregistry.go
- coreos/userdatavalidation/userdatavalidation.go
Extract it out of the config package into its own package "userdatavalidation" for future use in the upcoming node pools feature.
The former `coreosutil` package is now named `coreos/amiregistry` and the validation is in the `coreos/userdatavalidation` package to reflect the fact that both of them are coreos specific but they have different responsiblity compared to each other.
> refactoring: Extract coreos-cloud-init userdata validation

- config/config.go
- config/tls_config.go
- config/user_data_config_test.go
which is used for compacting TLSassets more open to be reused from other packages
This makes implementing the upcoming node pools feature a bit easier.
> refactoring: Make the Compact func and the KMS ecryption interface

- config/config.go
- config/config_test.go
This is intended to make implementing and maintaining the upcoming node pools feature eaiser.
Reorganizing structs and funcs like this would result in:
* Less conflicts between commits from multiple branches
* Better reusability when we try to make kube-aws provision a separate cfn stack for each part of a cluster e.g. etcd, control plane, worker nodes(incoming as the node pools feature)
> refactoring: Rethink how we organize cluster configuration for better maintenability

- .gitignore
- build
- cmd/nodepool.go
- cmd/nodepool/init.go
- cmd/nodepool/render.go
- cmd/nodepool/root.go
- cmd/nodepool/up.go
- config/config_test.go
- config/templates/stack-template.json
- e2e/run
- nodepool/cluster/cluster.go
- nodepool/config/config.go
- nodepool/config/config_test.go
- nodepool/config/templates/cluster.yaml
- nodepool/config/templates/stack-template.json
The initial implementation for #46.
Several pull requests were already merged to make this easier, smaller:
#97, #98, #99, #100, #101, #102, #103, #104, #105
Our E2E test suite now include `kube-aws node-pools` and Kubernetes conformance tests are passing.
---
Notes on the initial implementation of Node Pools.
`kube-aws node-pools (init|render|up) --node-pool-name mypool` commands assume you run `kube-aws` from the same working directory where you've run `kube-aws (init|render|up)` hence the `cluster.yaml` and other assets exist.
```
$ mkdir mycluster
$ cd mycluster
$ kube-aws init --cluster-name mycluster ...
$ kube-aws render credentials
$ kube-aws render stack
$ kube-aws up ...
$ kube-aws node-pools init --node-pool-name mypool ...
$ kube-aws node-pools render stack --node-pool-name …
```
> Initial implementation of Node Pools

- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
This was left out in PR https://github.com/coreos/kube-aws/pull/95
I am using `Wants=` instead of `Requires=` so that it works even for instance types that do not have ephemeral storage.
> Ensure ephemeral storage is prepared before docker starts

- cmd/update.go
Output from `kube-aws update` contained an errant `%!(EXTRA`
due to a missing formatting placeholder.
Fixes #116
> fix: `kube-aws update` success message formatting issue

- cmd/nodepool/init.go
- cmd/nodepool/root.go
When initializing a node pools I got a "wrong" message, fixed calling the function.
```
$ bin/kube-aws node-pools init --node-pool-name mypool --availability-zone=eu-west-1b
Success! Created %!s(func() string=0xacd50)
Next steps:
1. (Optional) Edit %!s(func() string=0xacd50) to parameterize the cluster.
2. Use the "kube-aws nodepool render" command to render the stack template.
```
After the fix
```
$ bin/kube-aws node-pools init --node-pool-name mypool --availability-zone=eu-west-1b
Success! Created node-pools/mypool/cluster.yaml
Next steps:
1. (Optional) Edit node-pools/mypool/cluster.yaml to parameterize the cluster.
2. Use the "kube-aws nodepool render" command to render the stack template.
```
> Fix console msg when initializing node pools

- config/config.go
- config/tls_config.go
- config/tls_config_test.go
- config/user_data_config_test.go
- e2e/run
- nodepool/config/config.go
- test/helper/helper.go
so that we can prevent unnecessary node replacement when `kube-aws update` run.
Encrypted credentials are named with the suffix `.enc` hence `*-key.pem.enc` for keys, `*.pem.env` for certs, and `ca.pem.enc` for ca cert.
If you've removed one of more `*.enc` files, `kube-aws (validate|up)` automatically re-generate not only removed ones but "all" the `*.enc` files by encrypting pem files.
The whole file tree representing kube-aws' state after `kube-aws init` now look like:
```
$ tree e2e/assets/
e2e/assets/
└── kubeawstest2
├── cluster.yaml
├── credentials
│   ├── admin-key.pem
│   ├── admin-key.pem.enc
│   ├── admin.pem
│   ├── admin.pem.enc
│   ├── apiserver-key.pem
│   ├── apiserver-key.pem.enc
│   ├── apiserver.pem
│   ├── apiserver.pem.enc
│   ├── ca-key.pem
│   ├── ca-key.pem.enc
│   …
```
> Persist encrypted credentials under the `credentials/` directory

- config/config.go
- config/config_test.go
- config/templates/cluster.yaml
- config/templates/stack-template.json
- nodepool/config/config.go
- nodepool/config/config_test.go
- nodepool/config/templates/cluster.yaml
- test/integration/aws_test.go
We can now specify which existing security groups to be attached to worker nodes created by kube-aws.
`workerSecurityGroupIds` configuration key was added to allow that.
In cluster.yaml, it would look like:
```
workerSecurityGroupIds:
- sg-87654321
- sg-98765432
```
Worker nodes in either main clusters and node pools are supported.
fix #43 
TODOs:
> Allow to attach user defined security groups to worker nodes

- cmd/nodepool/update.go
- nodepool/cluster/cluster.go
This command had been missing since the initial implementation done in #106
> Add `kube-aws node-pools update` command

- config/config_test.go
- nodepool/config/config_test.go
- nodepool/config/templates/cluster.yaml
- nodepool/config/templates/stack-template.json
- test/integration/aws_test.go
The following experimental features are added to node pools via this change:
* awsEnvironment
* waitSignal
* nodeLabel
* loadBalancer
ref #46 
TODOs:
> Add several experimental features already introduced to main clusters to node pools

- config/config.go
- config/config_test.go
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
- nodepool/config/config_test.go
- test/integration/aws_test.go
> Experimental feature to taint worker nodes with user-provided `key=value:effect`

- config/templates/stack-template.json
- nodepool/config/templates/stack-template.json
[They are free now](https://aws.amazon.com/about-aws/whats-new/2016/08/free-auto-scaling-group-metrics-with-graphs/) !
> Enable ASG metrics

- cfnstack/provisioner.go
- cluster/cluster.go
- cmd/nodepool/destroy.go
- e2e/run
- nodepool/cluster/cluster.go
which had been missing since the first implementation of Node Pools
> Add `kube-aws node-pools destroy` command

- e2e/run
- nodepool/cluster/cluster.go
We've been denying all the updates to cfn stacks for node pools in stack policy
> Make `kube-aws node-pools update` not to fail

- config/config.go
- config/templates/cloud-config-worker
- nodepool/config/templates/stack-template.json
This change fixes the issue that the second and the subsequent nodes in each spot fleet couldn't be registered thus unable to run any pods.
ref https://github.com/coreos/kube-aws/issues/112#issuecomment-265643237
> Fix node registration issue for spot-fleet-powered worker nodes

- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
That way rebooting the agents does not cause a re-download of images
it's likely to have had and now need again nor losing any Pod logs
> format ephemeral storage only on first boot

- cmd/nodepool/up.go
- cmd/nodepool/update.go
- cmd/up.go
- cmd/update.go
- cmd/validate.go
- config/config.go
- config/config_test.go
- filereader/jsontemplate/jsontemplate.go
- nodepool/config/config.go
- nodepool/config/config_test.go
- test/integration/aws_test.go
Means stack contents are easier to compare out of the box
> Option to pretty print CloudFormation JSON

- config/config.go
- config/config_test.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
- config/templates/stack-template.json
- e2e/run
- nodepool/config/config_test.go
- nodepool/config/templates/cluster.yaml
- nodepool/config/templates/stack-template.json
This complements Node Pools(#46) and Spot Fleet support(#112)
The former `experimental.nodeLabel` configuration key is renamed to `experimental.awsNodeLabels` to avoid collision with newly added `experimental.nodeLabels` and consistency with `experimental.awsEnvironment`.
cc @pieterlange @c-knowles
> Experimental feature: User-specified node labels for worker nodes

- cmd/nodepool/validate.go
- e2e/run
This is the last missing sub-command under the `kube-aws node-pools` command.
cc @c-knowles
> Add `kube-aws node-pools validate` command

- config/config.go
- config/config_test.go
- config/templates/cluster.yaml
- config/templates/stack-template.json
- nodepool/config/templates/cluster.yaml
- nodepool/config/templates/stack-template.json
Return of [my PR on the coreos-kubernetes repo](https://github.com/coreos/coreos-kubernetes/pull/252), this time with node-pool support added.
Let me know if you'd like tests or anything. The only thing slightly tricky about dedicated tenancy is that it's mutually exclusive with spot instances, I could potentially add a check for that.
> Add configurable instance tenancy

- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
e.g if you attach external security group to worker nodes and this group name contains whitespace then `systemctl set-environment` fails with `Failed to set environment: Invalid environment assignments`
Also applied same fix for launchconfiguration and autoscaling group labels, though these names are generated, but it is possible to create manually autoscaling group or launchconfiguration that has whitespace in its name
> Fix kube-node-label failure when there is a whitespace in sg name

- config/templates/cloud-config-controller
ref #147
We can now opt to schedule pods on controller nodes if appropriate tolerations are given to the pods.
This is not a breaking change because pods are still unable to be scheduled onto controller nodes by default.
depends on #149.
This will be rebased once #149 is merged.
> Adapt to schedulable and tainted controller nodes

- cluster/cluster.go
- config/config.go
- config/config_test.go
- config/templates/cluster.yaml
- e2e/run
- model/worker.go
- nodepool/cluster/cluster.go
- nodepool/config/config.go
- nodepool/config/templates/cluster.yaml
CloudFormation stacks created via kube-aws can now be tagged with the following keys with the values containing source of truth for cluster-autoscaler to update their autoscaling target and its min/max size.
* `kube-aws:cluster-autoscaler:logical-name` (Currently fixed to `AutoScaleWorker` which corresponds to the logical name of the autoscaling group for worker nodes defined in `stack-template.json`)
* `kube-aws:cluster-autoscaler:max-size`
* `kube-aws:cluster-autoscaler:min-size`
Adding tags to stacks instead of to autoscaling groups allows us to support autoscaling of spot fleet via cluster-autoscaler, in the future.
Currently, enabling this configuration doesn't automatically deploy cluster-autoscaler itself.
Please read [the original issue](coreos#148) carefully for more information. …
> cluster-autoscaler support

- config/templates/cloud-config-worker
- e2e/README.md
- e2e/run
- e2e/testinfra/stack-template.yaml
- nodepool/config/templates/stack-template.json
The last two TODOs mentioned in #112 are addressed
> Conform worker nodes powered by spot fleets to the ones powered by autoscaling groups

- config/templates/cloud-config-controller
* kube-dns is now deployed via a deployment instead of a replicaset
* kube-dns supports zero downtime rolling update (https://github.com/kubernetes/kubernetes/pull/37730)
* prometeus metris are exposed
fix #173 
ref #111
> Update kube-dns to the one bundled with k8s v1.5.1

- Documentation/kubernetes-on-aws-node-pool.md
- README.md
- cmd/init.go
- cmd/nodepool/init.go
- cmd/nodepool/render.go
- cmd/render.go
Corrects one of my comments from https://github.com/coreos/kube-aws/issues/44 now we actually have the node pool validation. I'm not sure we even need the `runCmdRender` method as isn't `kube-aws node-pool render` without any subcommand already deprecated? We shouldn't add deprecated things so if we want it to always be `kube-aws node-pool render stack` then I think we remove this part entirely.
> Correct node pool command inconsistencies

- config/config.go
Match spelling in config/templates/cluster.yaml
> Fix typo "etcdDataVolumeEphemeral": fix #192

- config/tls_config.go
Causes panic when ReadOrCreateEncryptedTLSAssets, for example when you enter a bad `kmsKeyArn`. 
Ever considered using Dave Cheney's error package? 
https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully
> Handle error from ReadOrCreateEncryptedTLSAssets gracefully.

- Documentation/kubernetes-on-aws-render.md
(aws-experimental-features) is a dead link, but in this case the intended target seems to be the node-pool documentation.
> Point to the node-pool documentation

- Documentation/kubernetes-on-aws-node-pool.md
- Documentation/kubernetes-on-aws-prerequisites.md
- config/config.go
- config/config_test.go
- config/templates/cluster.yaml
- model/worker.go
- nodepool/config/config_test.go
- nodepool/config/templates/cluster.yaml
- test/integration/aws_test.go
> Move from the old m3.medium instance type to the marginally better t2.medium

- cluster/cluster.go
- config/config.go
- nodepool/cluster/cluster.go
- nodepool/config/config.go
Nest node pool stack name by cluster name to avoid conflict when running multiple clusters.
e.g.
```
cluster-1
cluster-1-pool-1
cluster-1-pool-2
```
```
cluster-2
cluster-2-pool-1
cluster-2-pool-2
```
> Node Pool Nested Stack Name

- config/templates/cloud-config-controller
This labels are important for service auto discovery on [kube-prometheus](https://github.com/coreos/kube-prometheus/tree/master/manifests/k8s/self-hosted). I'm following the exactly same pattern on kops.
> Setup empty labels in controller

- cmd/nodepool/render.go
Folder is actually `node-pools`. Could you call nodePoolExportedStackTemplatePath() here instead, to ensure the correct path is in the message?
> Typo in node-pools render stack message

- config/templates/cloud-config-controller
/opt/bin/taint-and-uncordon had a syntax issue with the kubectl taint command. Was failing with `error: at least one taint update is required` and the controller node was still getting pods scheduled to it. PR fixes the syntax as per http://kubernetes.io/docs/user-guide/kubectl/kubectl_taint/
> Controller node not being properly tainted

- config/config.go
- config/templates/cluster.yaml
This feature is useful to experiment with new setups, have in house customizations etc without resorting to full '--export', so config still remains manageable and flexible.
Example use in stack-template.json:
```
{{ .CfgMap.myCustomOpt }}
```
> Add customSettings field

- config/templates/stack-template.json
As discussed in issue #214, stop blocking ICMP for the API ELB. Among other things ICMP is required for MTU discovery to for TCP / HTTPS connections with the API server.
> Don't block ICMP for API ELB

- config/templates/cloud-config-controller
Fixes issue #222 with the workaround proposed in https://github.com/kubernetes/kubernetes/issues/22770#issuecomment-266215007
> Fix kubectl logs problem due to apiserver config

- config/templates/cloud-config-worker
rkt has a gnarly bug (coreos/rkt#3181) that won't be fixed in a hurry (coreos/rkt#3486). It least to continuous task failures that eventually totally wreak worker nodes (#224). In the meantime we can use docker just as easily for this simple task. This work around was discussed in #199.
I tested deploying a node-pool or workers with this patch and the experimental.taint setting enabled and the right thing happened. The taint was applied and the node uncordoned. All looks good in the log and CPU load is nominal.
> Change taint-and-uncordon worker task to use docker for now

- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
Set of changes to for cleaner and more correct bash scripts.
Mainly changes are about adding `-e` to make startup scripts exit on errors encountered, which would prevent things like https://github.com/coreos/kube-aws/issues/215#issuecomment-271166798 and also some cosmetics where `; \` noise is removed where possible
> Bash improvements

- cluster/cluster.go
- cmd/init.go
- cmd/nodepool/init.go
- config/config.go
- config/templates/stack-template.json
- nodepool/config/templates/cluster.yaml
- nodepool/config/templates/stack-template.json
AWS CF reference that it is not mandatory to have one:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-keyname
> Do not require keyName if sshAuthorizedKeys are set

- cmd/nodepool/init.go
- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-etcd
- config/templates/cloud-config-worker
- config/templates/stack-template.json
- nodepool/config/config.go
- nodepool/config/templates/cluster.yaml
As part of effort to add support for provisioning into existing VPCs and subnets, kube-aws should stop trying to calculate static IPs itself: it is likely to cause conflicts for a first cluster in subnet and it is guaranteed not to work when provisioning second one.
This PR works by changing CF to save IP addresses  of InstanceEtcd in CF metadata which is then pulled by `cfn-init` scripts on nodes and placed in the right places.
It also adds explicit `AWS::EC2::NetworkInterface` resource which is then used as eth0 on Etcd instances.  Strictly speaking this change is not needed, but since `kube-aws`  decided not to manage Etcd instances after creation, in the real world they might need changes - having an explicit network interface resource allows instance to be recreated keeping same …
> Don't precalculate etcd static IP addresses

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-etcd
- config/templates/cloud-config-worker
- config/templates/stack-template.json
- e2e/run
- model/controller.go
- model/etcd.go
- model/worker.go
- nodepool/config/config.go
- nodepool/config/config_test.go
- nodepool/config/templates/cluster.yaml
- nodepool/config/templates/stack-template.json
- test/integration/aws_test.go
This is a follow up for the PR #226 "Don't precalculate etcd static IP addresses"
To see why this follow up was needed, read the maintainer's comment at #226 (comment)
P.S. As the result of some refactorings done in order to implement this, worker nodes powered by a spot fleet now supports the `awsEnvironment` experimental feature
fixes #261 
cc @redbaron
> Fix node pools on master

- cluster/cluster.go
- cmd/up.go
- config/config.go
- config/config_test.go
- config/templates/cluster.yaml
- config/templates/stack-template.json
- nodepool/config/config.go
- nodepool/config/templates/stack-template.json
If you define `subnetId` you can reuse existing subnets.
```
subnets:
- availabilityZone: us-east-1a
instanceCIDR: "10.0.1.0/24"
subnetId: "subnet-xxxxxxxx"
- availabilityZone: us-east-1b
instanceCIDR: "10.0.2.0/24"
subnetId: "subnet-xxxxxxxx"
...
```
there is still some work needed to support node-pools, but I would love to hear opinions or any suggestions on this approach.
It's backward compatible and it uses CF Parameters to overload Subnets with existing subnet id's or references to new resources.
linked to #52
> Use existing subnets when creating/updating cluster

- config/config.go
- config/config_test.go
- e2e/run
- nodepool/config/config.go
This PR includes the follow-up described in my comment https://github.com/coreos/kube-aws/pull/227#issuecomment-274651054, which is merged immediately after #227
> Follow up: Use existing subnets when creating/updating cluster

- Documentation/kubernetes-on-aws-limitations.md
- cmd/nodepool/up.go
- config/config.go
- config/config_test.go
- config/templates/cluster.yaml
- config/templates/stack-template.json
- model/controller.go
- model/etcd.go
- model/subnet.go
- model/worker.go
- nodepool/config/config.go
- nodepool/config/templates/stack-template.json
This PR belongs to issue #152 
The issue talks about the following use-cases supported by the PR:
- Place worker nodes in their own private subnet
- Place controller nodes in their own private subnet
- Place etcd nodes in their own private subnet
- Place node-pools on non pre-allocated private subnets
- Create NAT gateways to give Internet access to private subnets
- Use pre-allocated EIP's for the NAT gateways
- Use pre-allocated NAT gateways
> Create etcd and workers in private subnets, controllers in public subnet

- config/templates/stack-template.json
By default, when watching container logs using "kubectl logs -f" or
executing a command inside a container, the connection is terminated
after 60 seconds, resulting in errors like "error: unexpected EOF".
This happens because the AWS ELB in front of the k8s api server has the
"IdleTimeout" parameter set to 60. But can be increased up to 3600
seconds.
Here is the official documentation:
http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html
> Fix connection drop after 60 sec when executing commands inside containers

- config/config.go
- config/config_test.go
- config/stack_config_test.go
- config/templates/cluster.yaml
- config/templates/stack-template.json
- e2e/run
- model/controller.go
- model/etcd.go
- model/identifier.go
- model/internet_gateway.go
- model/nat_gateway.go
- model/subnet.go
- model/worker.go
- nodepool/config/config.go
- nodepool/config/templates/cluster.yaml
- nodepool/config/templates/stack-template.json
- test/integration/maincluster_test.go
This change allows us to define private and public subnets in the top-level of `cluster.yaml` to be chosen for worker/controller/etcd nodes and a controller loadbalancer.
Thanks to @neoandroid and @sasso for submitting the pull request #169 and #227 respectively which had been the basis of this feature.
Let me also add that several resources including subnets, NAT gateways, route tables can now be reused by specifying `id` or `idFromStackOutput`.
Thanks to @icereval for his PR #195 to firstly introducing the idea of `type Identifier` to add support for existing AWS resources in an universal way.
A minimum config utilizing this feature would look like:
```yaml
clusterName: mycluster
externalDNSName: mycluster.example.com
hostedZoneId: yourhostedzoneid
keyName: yourkeyname
kmsKeyArn: …
```
> Add support for customization of network topologies

- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
On workers nodes with calico enabled /etc/kubernetes/net.d/ can contain
directories which breaks `sed  -i '...' /etc/kuberneted/net.d/*`. It
runs smooth on first boot, but subseqent restarts are failing because
of newly created directory.
Change it to use `find -maxdepth 1 -type f | xargs ...` approach
which should be more robust.
> More robust etcd search and replace step

- config/templates/stack-template.json
Add a SecurityGroupIngress for controllers to access the kubelet
port (10250) on other controllers. This is needed for when there
are multiple masters.
Fixes #309
> controller-cfn: kubelet SecurityGroupIngress

- cmd/nodepool/up.go
- cmd/nodepool/update.go
- cmd/nodepool/validate.go
- cmd/up.go
- cmd/update.go
- cmd/validate.go
The error message should include the message from the original error, but
the original error is not included in error message.
This will be printed out when an error occurred:
```
Error: Failed to initialize cluster driver : <nil>
```
> Fix error message when failed to init cluster

- config/config.go
[As of Jan 19, these are no longer mutually exclusive](https://aws.amazon.com/about-aws/whats-new/2017/01/amazon-ec2-spot-instances-now-support-dedicated-tenancy/).
Will be testing this shortly and will report back here.
The two features that I added to `kube-aws`, together at last. 😃
> Remove checks for dedicated spot instances

- config/config.go
- config/templates/cluster.yaml
- config/templates/stack-template.json
Simple change to optionally provision worker nodes with sufficient privileges to run the cluster-autoscaler controller.
> Add ClusterAutoscaler experimental option to setup iam permissions

- config/templates/stack-template.json
- model/etcd.go
Having EBS volumes which survive node termination
makes them more manageable
> Create EBS volumes for Etcd nodes

- cmd/nodepool/up.go
- cmd/root.go
- cmd/up.go
- cmd/update.go
- cmd/validate.go
- config/config.go
- config/config_cluster_size_test.go
- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
- config/templates/cluster.yaml
- config/templates/stack-template.json
- e2e/README.md
- e2e/run
- model/worker.go
- nodepool/config/templates/stack-template.json
- test/integration/maincluster_test.go
- test/integration/nodepool_test.go
Add skip-wait flag
Enable feature waitSignal as default
Setup initial value for RollingUpdateMinInstancesInService as 1
Require s3-flag on validate command
Fix #259
@mumoshu, could you run your e2e tests and do some reviews? I'm writing some docs explaining how the signal works
> Wait for signals by default

- cfnstack/provisioner.go
- config/config.go
- config/templates/cluster.yaml
- config/templates/stack-template.json
- nodepool/config/templates/stack-template.json
- test/integration/maincluster_test.go
- test/integration/nodepool_test.go
If you plan to use kube2iam in existing kubeaws cluster you face two things:
- Default WorkerRole does not have the sts:assumeRole grant blocking kube2iam to assume the role for the container.
- target roles needs to change the trust policy to allow kube-aws worker IAM Role to assume the role. Because normally cloudformation generates the role with the role name and a random ID at the end makes the IAM Role less predictable and therefore more complicated to work with if you want to automate this trust.
This pr introduces kube2iam experimental flag, when kube2iam flag is enabled it will add sts:assumeRole to the worker IAM role to allow kube2iam to work, additionally you can specified a named role to generate a worker IAM Role more human and automation friendly as explained here …
> adding kube2iam experimental support

- config/templates/cloud-config-controller
- config/templates/cloud-config-worker
Fixes https://github.com/coreos/kube-aws/issues/134.
> Add DOCKER_OPTS environment variable to limit docker log files.

- config/config.go
- config/templates/cloud-config-controller
- config/templates/cluster.yaml
- test/integration/maincluster_test.go
- test/integration/nodepool_test.go
This PR adds experimental support for webhook token authentication, https://kubernetes.io/docs/admin/authentication/#webhook-token-authentication
To use add the following config:
```yaml
experimental:
authentication:
webhook:
enabled: true
cacheTTL: 1m0s
configBase64: base64-encoded-webhook-yaml
```
configBase64 is a base64 encoded webhook-yaml configuration.
> Experimental webhook token authentication support

- core/controlplane/config/tls_config.go
- tlsutil/x509.go
Fixes #344 
----
This is tested in so far as that it produces a seemingly correct subject in the admin certificate. I'm still replacing my cluster to confirm that this indeed is enough.
> credentials: Add /O=systems:master for kube-admin

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
This adds support for enabling pod security policies.
Note - this only enables the admission controller and does not create any pod security policies or bindings themselves. This is a similar issue to #230 in that one might argue kube-aws should also provide some minimal pod security policies so that basic pods can be admitted to the cluster before the administrator affects their own policies and rolebindings.
Unlike #230, however, enabling this doesn't result in a "broken cluster" at like the missing RBAC roles did; the kubernetes components work with PSPs enabled.
I have not done exhaustive testing about the ramifications of having PSPs enabled but having no policies, but I think it's worth having this patch in kube-aws so the administrator can make their own choices about how to …
> Add experimental support for pod security policies

- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/config/templates/stack-template.json
- model/node_pool_config.go
- model/root_volume.go
- model/spot_fleet.go
- model/volume_mount.go
- model/volume_mount_test.go
This adds a new feature that allows additional EBS volumes to be deployed and mounted on all specified worker nodes.
The template in cluster.yaml follows:
```yaml
volumeMounts:
- type: "gp2"
iops: 0
size: 30
device: "/dev/xvdf"
path: "/ebs"
```
Allowing the configuration of various parameters (which are validated).
Systemd .mount and .service resources are used to format the disks and mount them during runtime.
NOTE: The decision to not reformat the RootVolume struct (and create a new "VolumeMount" struct) was made to avoid issues regarding the naming convention of "rootVolumeSize", "rootVolumeType" ... etc. already implemented in the cluster .yaml.
Why have this feature?
The need for additional volumes arose when we realized we didn't want a situation where the root volume would reach …
> Add additional EBS volumes to worker nodes.

- core/controlplane/cluster/cluster.go
- core/controlplane/config/config.go
- core/controlplane/config/stack_config.go
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- core/controlplane/config/tls_config.go
- core/nodepool/config/config.go
- core/nodepool/config/templates/stack-template.json
- e2e/README.md
- e2e/run
- e2e/testinfra/stack-template.yaml
- filereader/texttemplate/texttemplate.go
- model/derived/etcd_cluster.go
- model/derived/etcd_cluster_test.go
- model/derived/etcd_node.go
- model/derived/etcd_nodes.go
- model/derived/network.go
- model/etcd.go
- model/etcd_cluster.go
- model/etcd_node.go
- model/region.go
- test/integration/aws_test.go
- test/integration/maincluster_test.go
This is a WIP pull request to achieve "Managed HA etcd cluster" with private IPs resolved via public EC2 hostnames stabilized with a pool of EBS and EIP pairs for etcd nodes.
After this change, EC2 instances backing "virtual" etcd nodes are managed by an ASG.
Supported use-cases:
* Automatic recovery from temporary Etcd node failures
* Even if all the nodes went down, the cluster recovers eventually as long as the EBS volumes aren't corrupted
* Rolling-update of the instance type for etcd nodes without downtime
* = Scaling-out of Etcd nodes via NOT modifying the ASG directly BUT indirectly via CloudFormation stack updates
* Other use-cases implied by the fact that the nodes are managed by ASGs
* You can choose "eip" or "eni" for etcd node(=etcd member) identity via the …
> Managed HA etcd cluster

- core/controlplane/cluster/cluster.go
- core/controlplane/cluster/cluster_test.go
- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
> Drop deprecated `hostedZone`(not `hostedZoneId`) in cluster.yaml

- core/controlplane/config/config.go
- model/node_pool_config.go
> Emit a warning message when `t2.nano` or `t2.micro` is set for `*instanceType`

- core/controlplane/config/templates/cluster.yaml
A few incorrect variable names were found lingering in the volumeMount set-up section of cluster.yaml (https://github.com/coreos/kube-aws/commit/1b37b13567135b48538b51f1968d0ce5bf246882).
Apologies for any inconvenience.
> Fix typos in cluster.yaml comments regarding volumeMounts

- core/controlplane/config/templates/cluster.yaml
This config moved from `workerSecurityGroupIds[]` to `worker.nodePools[].securityGroupIds[]`.
https://github.com/coreos/kube-aws/issues/333
> Fix an issue with glue security group documentation

- core/controlplane/config/templates/cloud-config-controller
Issues concerning conflicts between apiservers during leader allocation causes the (kubectl) kubernetes.service endpoint value to change arbitrarily (https://github.com/kubernetes/kubernetes/issues/19989) which we've encountered first-hand. The solution implemented sets the 'apiserver-count' parameter to the number of controllers used in the cluster .
The 'apiserver-count' value is set to the minimum number of controller nodes set in cluster.yaml (if controller auto-scaling is used).
> Add apiserver-count parameter in kube-apiserver config

- contrib/bump-version
- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
- e2e/kubernetes/Dockerfile
- e2e/kubernetes/Makefile
- model/derived/etcd_cluster_test.go
- model/region.go
This PR upgrades the kubernetes version to the most updated release v1.5.4 which solves some major bugs for AWS:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#changelog-since-v153
> Upgrade kubernetes version to v1.5.4

- core/controlplane/config/templates/cluster.yaml
Changed the attribute name to `enabled` so it matches the [expected name](https://github.com/coreos/kube-aws/blob/master/core/controlplane/config/config.go#L474) for that attribute when parsing the `cluster.yaml` file.
> Fix typo in ClusterAutoScalerSupport attribute name in template

- LICENSE
- OWNERS
- README.md
- RELEASE.md
- code-of-conduct.md
kube-aws is now a Kubernetes Incubator project under SIG AWS.
According to the [kubernetes template project](https://github.com/kubernetes/kubernetes-template-project), I've updated README.md and added the other necessary files:
* LICENSE
* code-of-conduct.md
* RELEASE
* OWNERS
From my own standpoint, the move is intended to make kube-aws grow further.
In a short term, it'll be done by attracting more users, feedbacks and contributors as an incubator.
In a long term, perhaps it'll be done by consolidating our fragmented efforts in the "k8s deployment tools" area by:
* Extracting common parts into another projects
* Transferring parts of kube-aws into another projects
* (Merge | Get merged into) another tools
* Graduate as a top-level Kubernetes project if kube-aws still turns out to be …
> Conform as a Kubernetes Incubator Project

- core/controlplane/config/templates/stack-template.json
with `kubernetes.io/role`.
Resolves #370
> Tag controller nodes appropriately

- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- model/etcd.go
- model/etcd_cluster.go
- test/integration/maincluster_test.go
Specify a custom KMS key ARN to use with an encrypted etcd data volume. If omitted the account default key will be used. Have also fixed up the IAM policy so encrypted volumes can be reattached to future etcd instances
Fixes #393
> Allow a custom KMS key with encrypted etcd volume

- core/controlplane/config/token_config.go
- core/controlplane/config/token_config_test.go
This PR improves UX after #418, hopefully avoiding issues like [this](https://github.com/kubernetes-incubator/kube-aws/issues/427#issuecomment-288551868).
> Automatically creates the token auth file if it isn't present

- ROADMAP.md
We'd need to wait for k8s to be shipped before finishing the "automatic recovery from permanent etcd node failures" work
> Update the roadmap before releasing v0.9.5

- cfnresource/naming.go
- cfnresource/naming_test.go
- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/config/config.go
- core/root/template_params.go
- test/integration/aws_test.go
- test/integration/maincluster_test.go
> Documentation and validation for too long IAM role names

- core/controlplane/config/token_config.go
@mumoshu addressing your comment in my last PR #439.
> Check for errors when trying to create the auth token file

- e2e/run
Set to same as kube-aws region
Otherwise if there we are deploying an e2e test cluster to a region different to the user's environment setup we get this:
```
+++ aws cloudformation --output json describe-stacks --stack-name kubeawstest1
+++ jq -r '.Stacks[].Outputs[] | select (.OutputKey == "ControlPlaneStackName").OutputValue'
An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id kubeawstest1 does not exist
++ aws cloudformation --output json describe-stack-resources --stack-name
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
aws help
aws <command> help
aws <command> <subcommand> help
aws: error: argument --stack-name: expected one argument
+ group_id=
+ aws ec2 …
```
> AWS CLI region default

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/config/deployment.go
Hi @mumoshu 
Made some small changes, mostly for China region.
1. Replace deprecated vars:
`KUBELET_VERSION` ==>   `KUBELET_IMAGE_TAG`
`KUBELET_ACI`.          ==>   `KUBELET_IMAGE_URL`
`RKT_OPT`                   ==>   `RKT_RUN_ARGS`
2. Fix `pause-amd64.service` to start at first boot.
3. Allow to pull **flannel** image from a docker repo In China region
sometimes it takes ~30 min to pull the image from quay.
Please review.
Thanks!
> China region improvements and update some deprecated vars.

- containerized-build-release-binaries
The containerized-build-release-binaries script file needs to be updated to reflect the new mount directory. (This is a consequence of the move kubernetes-incubator).
Otherwise the script fails:
```
main.go:6:2: cannot find package "github.com/kubernetes-incubator/kube-aws/cmd" in any of:
/go/src/github.com/coreos/kube-aws/vendor/github.com/kubernetes-incubator/kube-aws/cmd (vendor tree)
/usr/local/go/src/github.com/kubernetes-incubator/kube-aws/cmd (from $GOROOT)
/go/src/github.com/kubernetes-incubator/kube-aws/cmd (from $GOPATH)
```
> Fix mount directory for containerized-build-release-binaries script

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
This sysctl fix the nf_conntrack table 
**Logs**
```[2833841.216211] nf_conntrack: nf_conntrack: table full, dropping packet
[2833874.822698] nf_conntrack: nf_conntrack: table full, dropping packet
[2834097.097883] nf_conntrack: nf_conntrack: table full, dropping packet
[2834232.639992] nf_conntrack: nf_conntrack: table full, dropping packet 
``` 
This values are suggested in the docs of [project calico](http://docs.projectcalico.org/v2.0/usage/configuration/)
> Setup sysctl net.netfilter.nf_conntrack_max 

- Documentation/kubernetes-on-aws-render.md
- cmd/render.go
- cmd/up.go
- cmd/validate.go
- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/credential.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/tls_config.go
- core/controlplane/config/tls_config_test.go
- core/controlplane/config/token_config.go
- core/controlplane/config/token_config_test.go
- core/controlplane/config/user_data_config_test.go
- core/nodepool/config/config.go
- core/nodepool/config/deployment.go
- core/root/config/config.go
- core/root/render/credentials.go
- test/helper/helper.go
- test/integration/maincluster_test.go
This PR introduces an experimental feature for provisioning TLS certificates for worker nodes via the alpha [certificate signing requests](https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/) workflow.
If RBAC is enabled in `cluster.yaml`, I also made sure to set up the appropriate cluster role bindings so that the token used for sending the certificate signing requests can only make requests related to certificate provisioning, as instructed by the official documentation.
Checklist:
Closes #406.
> Kubelet TLS bootstrapping

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- core/root/config/config.go
- model/addons.go
- test/integration/maincluster_test.go
For https://github.com/coreos/kube-aws/issues/118.
- Currently using raw Pod as per [salt setup](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/rescheduler.manifest)
- Introduced `addons` section for components like this and future components mentioned in https://github.com/kubernetes-incubator/kube-aws/issues/118 (e.g. kube-state-metrics)
- Logging routed via standard streams, in the future we could support other log routing
- gcr image used, not sure if hyperkube has the rescheduler
- Aligned to https://github.com/kubernetes-incubator/kube-aws/pull/390 by allowing
image repo/tag to be overridden
> Introduce the rescheduler

- core/controlplane/config/templates/cloud-config-controller
Behaviour before this change is that the rescheduler does not get
deployed, in fact the entire `.Addons.Rescheduler.Enabled` block will
be missing from the controller file even when it is enabled.
Introduced by https://github.com/kubernetes-incubator/kube-aws/pull/472.
Should also fix some the cluster roles and TLS bootstrap, not tested that part but pretty certain it's currently broken.
> Correct file references

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- model/node_pool_config.go
This flag disables automatic security group rule management for ELBs.  
It requires that the user has setup a rule that allows inbound traffic on kubelet ports 
from the local VPC subnet so that load balancers can access it.
Disable setting a new security group rule for every ELB.
Set NodeMonitorGracePeriod <duration>.  Option on controller-manager (default 40s)
This is the amount of time which we allow running Node to be unresponsive before marking it unhealthy. 
Must be N times more than kubelet's nodeStatusUpdateFrequency.
> New settings: nodeMonitorGracePeriod, disableSecurityGroupIngress for controller-manager, nodeStatusUpdateFrequency for worker kubelet

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
Very rarely we see that docker can't pull any image with
errors like
```
Get https://gcr.io/v1/_ping: x509: certificate signed by unknown authority
```
produced in it's logfile. Basically nothing can be pulled and
docker acts as if CA bundle is not installed on a system. Simple
restart fixes the problem.
This is a poor attempt to automatically recover from this
situation. Unfortunately reloading daemon doesn't make it
to re-read /etc/ssl/certs/ca-certificates.crt
We've tried to run "update-ca-certificates" which regenerates
'/etc/ssl/certs/ca-certificates.crt' file in `ExecStartPre` for
few weeks, but today we triggered this strange edge condition
nevertheless, hence this PR
> Perform docker post-start check

- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
For https://github.com/kubernetes-incubator/kube-aws/issues/118.
The rescheduler has been updated for k8s 1.6+.
Here's some logs showing 0.3.0 working on latest master:
```
I0406 13:38:38.432791       1 rescheduler.go:140] Critical pod kube-system_heapster-v1.3.0-76786035-rw214 is unschedulable. Trying to find a spot for it.
W0406 13:38:38.441782       1 rescheduler.go:383] Skipping node ip-10-0-101-53.eu-west-1.compute.internal due to CriticalAddonsOnly taint with value: kube-system_heapster-v1.3.0-76786035-bsnx1
I0406 13:38:38.460355       1 rescheduler.go:159] Trying to place the pod on node ip-10-0-102-121.eu-west-1.compute.internal
I0406 13:38:38.474273       1 rescheduler.go:332] Pod default_nginx-test-2766461593-w7vlw will be deleted in order to schedule critical pod …
```
> Rescheduler to 0.3.0 which uses k8s 1.6

- core/controlplane/config/templates/stack-template.json
Pod environment variable `KUBERNETES_SERVICE_HOST` and DNS entry
`kubernetes.default.svc.cluster.local` should now function correctly
and be queryable from controllers.
For https://github.com/kubernetes-incubator/kube-aws/issues/512
> Fix API endpoint from HA controllers

- core/controlplane/config/config.go
- core/nodepool/config/config.go
Now, when e.g. AWS_ACCESS_KEY_ID is missing, the error looks like:
```
$ kube-aws validate --s3-uri ...
*snip*
Error: Failed to initialize cluster driver: failed to read/create TLS assets: UnrecognizedClientException: The security token included in the request is invalid.
```
Resolves #490
> Make the validation error message when KMS failed more friendly

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/kubeconfig.tmpl
- core/nodepool/config/config.go
- e2e/run
- model/derived/api_endpoints.go
- test/integration/maincluster_test.go
This fixes the issue which prevented a k8s cluster from being properly configured when multiple API endpoints are defined in cluster.yaml.
It was due to empty API endpoint URLs embedded across userdata and kubeconfig.
AdminAPIEndpointURL and APIEndpointURL are implemented and injected to kubeconfig and cloud-config-worker respectively to fix the empty URLs issue.
In order to implement AdminAPIEndpointURL, `adminAPIEndpointName` in cluster.yaml is added and now required in addition to `apiEndpoints` and `worker.apiEndpointName`
Resolves #527
cc @c-knowles
> Follow-up for the multi API endpoints support

- Documentation/kubernetes-on-aws-backup-restore.md
- README.md
- core/controlplane/cluster/cluster.go
- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/config/config.go
- core/nodepool/config/templates/stack-template.json
A new kube-system Deployment has been created which takes and uploads snapshots of all Kubernetes resources within the cluster to S3.
There are two containers:
**cluster-dump-dumper**:
- Uses kubectl to snapshot all Kubernetes resources (interval of 24 hours).
- Each snapshot resides in a timestamped folder
- The resources have several fields omitted such as _status_ , _uid_, etc ... this is to allow the possibility of restoring resources inside a fresh cluster
- Resources that reside within namespaces are grouped inside folders labeled with the namespace name
- Resources outside namespaces are grouped at the same directory level as the namespace folders
**cluster-dump-pusher**
- Uses aws to upload snapshots to S3
- The S3 path is constructed from the _S3URI_ passed into kube-aws binary; …
> 'Cluster-dump' feature to export Kubernetes Resources to S3

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- model/controller.go
- model/custom_file.go
- model/custom_systemd_unit.go
- model/etcd.go
- model/node_pool_config.go
This adds the capability to write user defined files and systemd units to the 3 main types of servers: Etcd, Controller, NodePool Worker as specified by the cluster.yaml configuration for the cluster.
> New options: customFiles and customSystemdUnits

- core/controlplane/cluster/cluster.go
This issue prevented the autosave to push to s3 since it was pushing to the wrong path.
> Bugfix: Add missing '/' when constructing the Autosave S3 put path

- core/controlplane/config/templates/cluster.yaml
For https://github.com/kubernetes-incubator/kube-aws/issues/520. `loadBalancer` was missing entirely.
Not sure where to put `worker.apiEndpointName`, does it default to anything? I'd like to resolve this documentation issue in the same PR as `worker.apiEndpointName` is not listed in the default cluster.yaml:
```
Error: Failed to initialize cluster driver: file cluster.yaml: worker.apiEndpointName must not be empty when there're 2 or more API endpoints under the key `apiEndpoints` and one of worker.nodePools[] are missing apiEndpointName
```
> Fix up API endpoints config

- core/controlplane/config/templates/cloud-config-controller
ETCD_ENDPOINTS tokens are not being replaced in the 10-calico.conf file
> Fix to calico configuration file etcd endpoints

- contrib/cluster-backup/README.md
- core/controlplane/config/templates/cluster.yaml
Minor fixes:
- Fix hyperlink to restore script in Readme.md.
- Reference 'autosave' rather than 'export' in comments of cluster.yaml.
> Fix hyperlink to restore script in Readme.md.

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
Due to https://github.com/rkt/rkt/issues/3465 no rkt containers can be GCed on
a node once kubelet is up and running.
Symptoms are that if you run following command, container can't be GCed:
```
rkt run  --insecure-options=image docker://busybox --exec date; rkt gc --grace-period=0;
```
So if any service periodically runs rkt containers, then node will eventually fill
up with many mounts and slow down operation.
As an extra-cleanup, also removing mounts of /tmp and rkt binary as they are
not used by kubelet
> Don't mount /var/lib/rkt into kubelet

- contrib/cluster-backup/restore.sh
- core/controlplane/config/templates/cloud-config-controller
Rather than concatenating json entries, store the resources as a list (which creates a valid JSON file).
i.e. Before:
```
{
"apiVersion": "v1",
"kind": "Namespace",
"metadata": {
"name": "default",
"namespace": ""
},
"spec": {
"finalizers": [
"kubernetes"
]
}
}
{
"apiVersion": "v1",
"kind": "Namespace",
"metadata": {
"name": "kube-system",
"namespace": ""
},
"spec": {
"finalizers": [
"kubernetes"
]
}
}
```
After
```
{
"apiVersion": "v1",
"items": [
{
"apiVersion": "v1",
"kind": "Namespace",
"metadata": {
"name": "default",
"namespace": ""
},
"spec": {
"finalizers": [
"kubernetes"
]
}
},
{
"apiVersion": "v1",
"kind": "Namespace",
"metadata": {
"name": "kube-system",
"namespace": ""
},
"spec": {
"finalizers": [
"kubernetes"
]
}
}
],
"kind": "List",
"metadata": {},
"resourceVersion": "", …
```
> Kubernetes-Autosave save as Kubernetes/List.

- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- e2e/README.md
- e2e/run
- model/cidr_range.go
- model/cidr_range_test.go
- model/controller.go
- model/etcd.go
- test/integration/maincluster_test.go
It has been hard-coded to `0.0.0.0/0` which isn't desirable for security.
From now on, you can use `sshAccessAllowedSourceCIDRs` to override the list of ranges allowed.
Explicitly setting it to an empty array would result in nodes unable to be SSHed. However, doing so while configuring `worker.securityGroupIds`, `controller.securityGroupIds` and `etcd.securityGroupIds` would allow you to fully customize how SSH accesses are allowed - including not only ranges but ports to be allowed.
Closes #338
cc @c-knowles @swestcott
> Allow customizing network ranges from which SSH accesses to nodes are allowed

- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- model/api_endpoint_lb.go
- model/api_endpoints.go
- model/derived/api_endpoint_lb.go
- test/integration/maincluster_test.go
It has been hard-coded to `0.0.0.0/0` which isn't desirable for security.
From now on, you can use `apiEndpoints[].loadBalancer.apiAccessAllowedSourceCIDRs` to override the list of ranges allowed.
Explicitly setting it to an empty array would result in a load balancer which is completely unable to be accessed. However, doing so while configuring `apiEndpoints[].loadBalancer.securityGroupIds` would allow you to fully customize how API accesses are allowed - including not only ranges but ports to be allowed.
Similar to/Depends on #551
Closes #544
> Allow customizing network ranges from which Kubernetes API accesses are allowed

- Documentation/kubernetes-on-aws-render.md
- cmd/init.go
- core/controlplane/config/config.go
- core/controlplane/config/stack_config_test.go
- core/controlplane/config/templates/cluster.yaml
- e2e/run
- model/api_endpoints.go
- model/derived/api_endpoints.go
In favor of recently added `apiEndpoints[]`.
Also adds the new flag `--hosted-zone-id` to the `kube-aws up` command to pre-populate `apiEndpoints[].loadBalancer.hostedZone.id`. It is useful if you'd been scripting like `echo "hostedZoneId: ${FOO}" >> cluster.yaml` to automatically enabling record set creation - your former method won't work anymore due to the fact that the new setting is deeply nested.
Closes #545
> Deprecate externalDNSName/createRecordSet/hostedZoneId

- core/controlplane/config/templates/cloud-config-controller
It appears that the userdata of controller is missing --node-labels on kubelet
even if it is specified in cluster config.
> Add controller node labels if specified

- core/controlplane/config/templates/cloud-config-controller
Since Kubernetes 1.6, the default storage backend is etcd3 if
not specified. If etcd version is set to '2' in cluster config,
we need to set --storage-backend=etcd2.
> Set --storage-backend to etcd2 if not using etcd3

- model/controller.go
- model/derived/api_endpoint_lb.go
- model/etcd.go
I noticed that the recent work to extend glue security groups to etcd/controllers/apiendpoints were missing the double quotes when being rendered into the stack json. I think I addressed all instances of this case.
I was getting the following error when enabling security groups for the controllers:
```
Error while rendering template : Error while rendering stack template : invalid character 's' looking for beginning of value:
json syntax error (offset=17339), in this region:
-------
,
"SecurityGroups": [
sg-af3da9d6
,
{"Ref":"SecurityGroupController"}
-------
```
> Quote security group refs for etcd, controller, and apiendpoints

- core/controlplane/config/templates/stack-template.json
A small amendment to the Persistent Volume created as EFS.
We found that the default policy for the pv is Reclaim. When you delete the VolumeClaim and try to recreate it, it enters a pending state unless the volume itself is deleted and recreated.
Using Recycle as a reclaim policy allows reruns of the volume claim without having to recreate the volume
> Add reclaim policy

- Documentation/kubernetes-on-aws-add-ons.md
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/templates/stack-template.json
- core/root/config/templates/stack-template.json
This allows node pool IAM roles to be referenced in external cloudformation
stacks that provide roles for kube2iam to use. The worker IAM role is required
to grant permissions to the worker instances in an AssumeRolePolicyDocument.
> Export worker stack names and worker IAM role ARNs

- core/controlplane/cluster/cluster.go
- core/controlplane/config/config.go
- core/controlplane/config/stack_config.go
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/config.go
- e2e/run
- model/s3_folders.go
Etcd snapshots are now persisted with a s3 prefix `kube-aws/clusters/<cluster name>/instances/<roo stack id/etcd-snapshots` rather than the former `kube-aws/clusters/<cluster name>/exported/stacks/etcd-snapshots`
Closes #562
> Fix etcd snapshots locations in S3

- contrib/dex/README.md
- contrib/dex/cleanup.sh
- contrib/dex/elb/external-elb.yaml
- contrib/dex/elb/internal-elb.yaml
- contrib/dex/expose-service.sh
- contrib/dex/ingress/dex.ingress.yaml
- contrib/dex/ingress/dex.svc.yaml
- contrib/dex/ingress/nginx-ingress-lb.yaml
- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/tls_config.go
- core/controlplane/config/tls_config_test.go
- model/dex.go
- test/helper/helper.go
- test/integration/maincluster_test.go
Hi @mumoshu I don't know if this is the best approach to integrate `dex` into `kube-aws` 
as I'm trying to make it as simple as possible but in the same time customisable and my skills with Go are limited. 
The current setup: 
* a Kubernetes "Deployment" + a minimal config in a "ConfigMap"
* all the parameters are set inside the "ConfigMap" which is generated from `cluster.yaml`
* after the cluster is up, the user can customize `dex` "ConfigMap" and "Deployment"
* upgrading/scaling the masters will not modify the "ConfigMap" or the "Deployment"
*`dex` is running on http on port 5556
* the user decide how to expose the service using a internal/public LoadBalancer, a Ingress Controller or a NodePort
* the required SSL certificates are managed by the user. In our case we prefer using a …
> Dex integration.

- core/controlplane/config/templates/cluster.yaml
fixies https://github.com/kubernetes-incubator/kube-aws/issues/586
> controller.loadBalancer is deprecated use apiEndpoints[].loadBalancer

- core/controlplane/config/templates/stack-template.json
The API endpoint ELB health check is set to "TCP:443". This causes
"TLS handshake error" in apiserver logs. Changing it to "SSL:443" will
perform the proper SSL handshake and make the error disappear from the log.
```
I0427 03:57:55.059255       1 logs.go:41] http: TLS handshake error from 172.24.14.156:11370: EOF
I0427 03:57:55.059952       1 logs.go:41] http: TLS handshake error from 172.24.2.59:6348: EOF
```
> Change API endpoint ELB health check to SSL:443

- core/controlplane/cluster/cluster.go
- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/stack_config.go
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/config.go
- core/nodepool/config/templates/stack-template.json
- core/root/config/templates/stack-template.json
- core/root/template_params.go
- model/controller.go
- model/iamconfig.go
- model/node_pool_config.go
- test/integration/maincluster_test.go
this PR aims to fix issue #500 allowing Node Pools to use an existing instance profile. It also includes a brief improvement for IAM Roles managed by kube-aws supporting customer managed policies (ref #340), it also makes IAM Roles fixed and not depending on the stack name if you have configured managedIAMRoleName.
If kube-aws manages the IAM Role it will create a customer managed policy for controllers and for workers, then it will create an IAM Role with this policy attached, that enables policy updates without the need to recreating the whole stack and kube-aws users can tailor the policies to their current needs.
if kube-aws uses an existing InstanceProfile it will not create an IAM Role and the InstanceProfile used should be attached to an IAM Role with the enough level of grants to …
> More flexible configuration for IAM and stable naming for roles

- core/controlplane/config/config.go
- core/root/config/config.go
- model/taint.go
- model/taint_test.go
- test/integration/maincluster_test.go
- test/integration/nodepool_test.go
This PR prevents users from creating clusters with invalid taints in both the controller and node pools.
These are the rules:
- Key must be provided
- Effect must be: `NoSchedule`, `PreferNoSchedule`, and `NoExecute`
- Key/effect pair must be unique
> Improve taints validation

- core/controlplane/config/templates/cloud-config-controller
Synchronizes the kube-dns config with changes in [upstream](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns).
Closes #584.
> kube-dns improvements

- core/controlplane/config/templates/cloud-config-controller
- Prefixes custom roles and bindings with `kube-aws:*`, following the conventions of other tools, like `kubeadm`
- Makes the `kube-worker` user behave like a member of `system:nodes` group by associating this user with the `system:node` cluster role. This effectively removes the association between the `kube-worker` user and the `cluster-admin` role, thus improving security by only granting the permissions nodes are supposed to have
- Associates the `kube-worker` user and the `system:nodes` group to `system:node-proxier` so that the kube-proxy works with TLS bootstrapping on and off. This is needed since nodes no longer have admin permissions (see previous bullet)
> RBAC setup improvements

- core/controlplane/config/templates/cloud-config-controller
The kube-resources-autosave script is unable to find the list of namespaces
and so it tries to backup resources from `null` namespace.
Log from kube-resources-autosave-dumper:
```
(...snip...)
++ jq -r .metadata.name
+ for ns in '$(jq -r '\''.metadata.name'\'' < ${DUMP_DIR}/namespaces.json)'
+ echo 'Searching in namespace: null'
+ mkdir -p /kube-resources-autosave/tmp/2017-05-09_15-18-57/null
Searching in namespace: null
(...snip...)
```
> Fix unable to backup namespaced resources

- Documentation/kubernetes-on-aws-prerequisites.md
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/templates/stack-template.json
- core/root/config/templates/stack-template.json
- etcdadm/etcdadm
KubernetesCluster is deprecated in favour of `kubernetes.io/cluster/$NAME`
> Use new K8S 1.6 AWS tagging scheme

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
It seems that kubelet silently converts `cluster_dns` into
`cluster-dns`, so nothing was broken, it is just a minor cleanup
> Make kubelet flags more consistent

- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- model/gpu.go
- model/node_pool_config.go
- test/integration/maincluster_test.go
Hello community!  Thank you for developing the great tool!  I'm glad to have opportunity to contribute this project because my colleague @mumoshu always encourages me.
As everybody know, AWS offers Nvidia GPU ready instance type families (P2 and G2).  And, of course Kubernetes supports GPU resource scheduling since 1.6.  However Nvidia drivers is not installed in default coreos ami used in kube-aws.  Then, let's support it!
This PR implements auto installation support of Nvidia GPU driver.  I borrowed some driver installation script from [/Clarifai/coreos-nvidia](https://github.com/Clarifai/coreos-nvidia/).
New configuration for this feature is really simple.  `worker.nodePool[i].gpu.nvidia.{enabled,version}` is introduced in `cluster.yaml`.
- default value of `enabled` is false.
- user …
> NVIDIA driver installation support on GPU instances

- Documentation/kubernetes-on-aws-add-ons.md
- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/config.go
- core/nodepool/config/templates/stack-template.json
- core/root/config/config.go
- e2e/run
- model/addons.go
- model/autoscaling.go
- model/controller.go
- model/node_labels.go
- model/node_pool_config.go
- test/integration/maincluster_test.go
In #151, we've introduced the initial, incomplete, almost theoretical support for cluster-autoscaler. The situation has changed considerably since then - Now we can finally complete the cluster-autoscaler support.
* Automatically scale out a node group by adding node(s) when one or more pods in the group become unschedulable due to insufficient resource.
* Automatically scales in a node group by removing node(s) that is safe to be done so. Basically, a node group is safe to be removed when it is not running a critical k8s component
* CA is now deployed automatically
* More concretely, a k8s deployment for cluster-autoscaler is automatically created on a k8s cluster when cluster-autoscaler addon is enabled in cluster.yaml
A valid cluster.yaml for a CA-enabled cluster would now look like: …
> Re: cluster-autoscaler support

- core/controlplane/config/templates/cloud-config-controller
Hi @mumoshu it looks that leaving the 
clusterAutoscaler:
enabled: false
will break the "install-kube-system" script. This is the error in journald: 
May 22 13:42:19 ip-10-0-1-49.ec2.internal install-kube-system[16493]: error: the path "/srv/kubernetes/manifests/cluster-autoscaler-de.yaml" does not exist
> Fix "install-kube-system" script when "clusterAutoscaler" is disabled.

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/config.go
- core/nodepool/config/templates/stack-template.json
- core/root/config/templates/stack-template.json
- model/node_drainer.go
- model/node_drainer_test.go
- test/integration/maincluster_test.go
**This PR is ready to review.**
This PR introduces a rewrite of the node draining logic (based on ASG lifecycle hooks) + a fix for a bug in RBAC-enabled clusters that causes pods not to be evicted (see #673).
Now, if the node drainer is enabled, the install script creates a DaemonSet that executes a control loop implemented in bash that checks the current state of each instance and, if the auto scaling group signals some instance must be terminated, the script will detect the change and will perform the node draining - with retries in case the drain command takes too long to finish.
The old node draining systemd unit was removed, as they don't really work in practice: since the node draining could take more than a few seconds to finish, it don't usually have time to finish draining the …
> Improved node drainer

- core/controlplane/config/templates/cloud-config-controller
For https://github.com/kubernetes-incubator/kube-aws/issues/685.
After this PR we still have these logs:
```
heapster-v1.3.0-2152587771-9cg3w heapster-nanny E0531 09:40:59.332643       1 nanny_lib.go:110] the server does not allow access to the requested resource (get deployments.extensions heapster-v1.3.0)
```
I agree with the comment https://github.com/kubernetes/heapster/issues/1589#issuecomment-291184395, it seems unwise to allow heapster to modify it's own config.
However, without this PR heapster constantly cycles replica sets when RBAC is enabled so at least this way it does not churn the pod and we have heapster running more constantly which is a start.
> Heapster service account and cluster role binding

- core/controlplane/config/templates/cloud-config-controller
When using taints in Node Pools together with calico the stack
always fail in Cloudformation since cfn-signal sytemd unit checks
if calico is up before signaling success
> calico-node - DaemonSet tolerating all taints

- core/nodepool/config/templates/stack-template.json
Added support for detailed monitoring as default behavior when creating a spot fleet node pool. Addresses issue https://github.com/kubernetes-incubator/kube-aws/issues/623
> Spot fleet detailed monitoring

- core/controlplane/config/templates/stack-template.json
Adds 's3:ListBucket' permission explicitly to statement with only bucket ARN.
Adds 's3:GetObject*' permission to statement with s3:prefix and bucket ARN.
Should fix `etcd3` `snapshot.db` recovery process.
This should fix S3 permission denied errors during `etcdadm-reconfigure` such as:
etcdadm[28736]: /opt/bin/etcdadm: info: member_remote_snapshot_exists: checking existence of s3://test-etcd-fail-example/kube-aws/clusters/etcd-fail/instances/9f6c6e20-400f-11e7
etcdadm[28736]: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
Fixes #660
> core: Add ListBucket explicitly to EtcdSnapshotsS3Bucket

- core/controlplane/config/config.go
This updates the image version for cluster-proportional-autoscaler to v1.1.2
This version uses client-go 3.0 beta which is fully compatible with k8s 1.6
References
- https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/blob/master/CHANGELOG.md
- https://github.com/kubernetes/client-go#compatibility-matrix
> core: update cluster-proportional-autoscaler to v1.1.2

- etcdadm/etcdadm
Motivation is to avoid serious memory leak on etcd nodes as in
* https://github.com/coreos/bugs/issues/1927
Also it potentially mitigates issues https://github.com/kubernetes-incubator/kube-aws/issues/691 and https://github.com/kubernetes-incubator/kube-aws/issues/660 as the symptoms looks similar to our case.
> Use docker instead of rkt for regular etcdadm tasks (#4)

- core/controlplane/config/templates/cloud-config-controller
Without this permission, the `kube-node-drainer` unit fails when the node being drained contain job pods:
```
User "system:node:<name>" cannot get jobs.batch in the namespace "<ns>". (get jobs.batch <job-name>): <pod-name>; User "system:node:<name>" cannot get jobs.batch in the namespace "<ns>". (get jobs.batch <job-name>): <pod-name>
```
> Fix node drain error when trying to evict pods from jobs

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
Kube-proxy, by default, [automatically sets](https://kubernetes.io/docs/admin/kube-proxy/) `nf_conntrack_max` to `<n-cores> * <value of conntrack-max-per-core>` when it starts, so it's useless to try to override `nf_conntrack_max` in some systemd unit.
If we wish to override this value, the best way to do so is by providing the `--conntrack-min` (or `--conntrack-max-per-core`) argument to kube-proxy, which also takes care of setting a proportional value to conntrack `hashsize`.
Closes #708
> Remove unused sysctl override for nf_conntrack_max

- Documentation/kubernetes-on-aws-journald-cloudwatch-logs.md
- README.md
- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/templates/stack-template.json
- core/root/config/templates/stack-template.json
- core/root/template_params.go
- e2e/run
- test/integration/maincluster_test.go
A service has been introduced which runs a dockerized image of journald-cloudwatch-logs. This service forwards journald logs to AWS CloudWatch to a LogGroup with the name of .ClusterName and is run on all nodes (Etcds, Controllers and Workers).
journald-cloudwatch-logs is a goLang project https://github.com/saymedia/journald-cloudwatch-logs.
This feature is disabled by default (with a retention period of 7 days) and configurable in cluster.yaml:
```
cloudWatchLogging:
enabled: false
imageWithTag: jollinshead/journald-cloudwatch-logs:0.1
retentionInDays: 7
```
> Send Journald logs to AWS CloudWatch

- core/root/config/config.go
> Report errors if empty nodepool is specified

- e2e/kubernetes/conformance.sh
This fix is required to run E2E against k8s v1.6.3+. More concretely, `cd e2e && ./run all` or more specifically `./run conformance` was consistently failing with the error.
> e2e: Fix `flag provided but not defined: -check_version_skew` error

- core/controlplane/config/templates/stack-template.json
Without this additional propagation `etcdadm` falls back to default `3.1.3` version as in
https://github.com/iflix-letsplay/kube-aws/blob/master/etcdadm/etcdadm#L88
In case when any other version is specified in `cluster.yaml` it will create the deviation between running etcd version and the one that is used for periodic snapshotting, e.g. running `3.1.8` in the main container and still using default `3.1.3` for `etcdadm` based operations.
This PR fixes the deviation.
> Propagate etcd version from cluster.yaml to etcdadm

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
Refactored node drainer code to also run in response to a spot instance termination notice.
Closes #734.
> Drain node on spot instance termination notice as well

- core/controlplane/config/templates/cloud-config-worker
- core/nodepool/config/templates/stack-template.json
- filereader/texttemplate/texttemplate.go
> Inject stack name  into userdata for nodepool workers

- core/root/config/templates/stack-template.json
- core/root/template_params.go
It's just an idea. We have few clusters of kubernetes which is managed by kube-aws but there is no way how to check with version of kube-aws is used for creating or updating this cluster. So we don't know if we need proceed update on this clusters.
Btw usage of CloudFormation output is just an idea we should use CloudFormation tags needer.
PS: I have no experience with Go so I'm just trying if this works.
> Add cluster kube-aws version to outputs

- Documentation/kubernetes-on-aws-journald-cloudwatch-logs.md
- core/controlplane/config/config.go
- core/nodepool/config/config.go
- core/nodepool/config/deployment.go
The worker nodes were using the default configuration for the CloudWatchLogging feature (default: disabled). Now they use overwriting values in the cluster.yaml file (if present).
The CloudWatchLogging documentation has been updated to reflect the most recent implementationn of the feature.
> Bugfix: CloudWatchLogging always disabled for Worker nodes

- core/controlplane/config/config.go
- core/controlplane/config/config_cluster_size_test.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/cluster/cluster_test.go
- core/nodepool/config/config.go
- model/controller.go
- model/deprecated_root_volume.go
- model/lauch_specification.go
- model/node_pool_config.go
- test/integration/maincluster_test.go
Except `externalDNSName`, `createRecordSet`, `recordSetTTL`, `hostedZoneId`, `controller.loadBalancer` as per https://github.com/kubernetes-incubator/kube-aws/issues/753#issuecomment-314357384
Ref #753 
This is verified manually by running E2E
> Remove deprecated keys in cluster.yaml

- core/controlplane/cluster/cluster.go
- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/config.go
- core/nodepool/config/deployment.go
- e2e/run
- model/vpc.go
- test/integration/maincluster_test.go
* Add `vpc.id` and deprecate `vpcId` instead
* kube-aws emits a warning message when `vpcId` is specified in `cluster.yaml`
* kube-aws emits a warning message when `.VPCID` is called in a control-plane stack template
* Add `vpc.idFromStackOutput` for cross-stack referencing vpc id
* Add `internetGateway.id` and deprecate `internetGatewayId` instead
* kube-aws emits a warning message when `internetGatewayId` is specified in `cluster.yaml`
* Add `internetGateway.idFromStackOutput` for cross-stack referencing internet gateway id
This is verified manually by running E2E in 2 ways:
1. Deployment to a managed VPC: `ETCD_DISASTER_RECOVERY_AUTOMATED=1 ETCD_SNAPSHOT_AUTOMATED=1 ETCD_COUNT=1 CONTROLLER_COUNT=1 KUBE_AWS_CLUSTER_NAME=vpcid1 bash -c './run all`
2. Deployment to an existing VPC: …
> Support cross-stack references of VPC, IGW

- containerized-test-run
Local `make test` fails for me miserably so
`containerized-test-run` was created in a similar
fashion to `containerized-build-release-binaries`
> Containerized test run

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
Deny host access through privileged containers with the help of
https://kubernetes.io/docs/admin/admission-controllers/#denyescalatingexec
> Deny direct command execution on privileged containers

- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- core/root/config/templates/stack-template.json
- core/root/template_params.go
- model/arn.go
- model/autoscaling_notification.go
- model/controller.go
- model/etcd.go
- model/iamconfig.go
- model/identifier.go
- model/node_pool_config.go
- test/integration/maincluster_test.go
* Add `etcd.iam.role.managedPolicies[].arn` for specifying additional managed policies associated to the kube-aws managed etcd IAM role
* Add `etcd.iam.instanceProfile.arn` for specifying an existing IAM instance profile used instead of kube-aws managed one. In other words, when it is specified, kube-aws doesn't create an instance profile for you
* Unlike `controller.iam` and `worker.iam`, `etcd.iam.role.name` isn't supported yet. The reason is that I'm still unsure what is the exact use-case for it
This is tested manually by running E2E WITHOUT custom IAM config. Testing with custom IAM configs is delegated to whom requested this feature due to that I'm short on time to set up an instance profile used for testing.
Resolves #747
> More flexible IAM configuration for etcd nodes

- core/controlplane/config/templates/cluster.yaml
- e2e/run
Values passed via the flag had been completely ignored, surprisingly.
Resolves #764
> Fix --ami-id

- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
Rather than being stored inside the container instance. For https://github.com/kubernetes-incubator/kube-aws/issues/118.
v0.3.1 has the fix for https://github.com/kubernetes/contrib/issues/2518.
I've deployed this on a dev cluster and I can see rescheduler logs in the cluster logs again.
> Rescheduler logs now piped to docker

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/config/deployment.go
- e2e/run
- test/integration/maincluster_test.go
Amazon SSM agent make us to quickly and easily execute remote commands or scripts against one or more EC2 instances: https://github.com/aws/amazon-ssm-agent
This feature is disabled by default and configurable in cluster.yaml:
```
#amazonSsmAgent:
```
> Install Amazon SSM Agent onto EC2 instances

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
This PR fixes the automatic approval of CSR requests made by worker nodes during the bootstrap process in Kubernetes 1.7 when RBAC is enabled.
Quoting the documentation:
> In 1.7 the experimental “group auto approver” controller is dropped in favor of the new csrapproving controller that ships as part of kube-controller-manager and is enabled by default. The controller uses the SubjectAccessReview API to determine if a given user is authorized to request a CSR, then approves based on the authorization outcome. To prevent conflicts with other approvers, the builtin approver doesn’t explicitly deny CSRs, only ignoring unauthorized requests.
So, for the kubelet bootstrap to work in Kubernetes 1.7, we need to add a cluster role+binding to instruct the CSR approver to auto-approve requests …
> Fix kubelet bootstrap for Kubernetes 1.7

- core/controlplane/config/templates/cluster.yaml
core/controlplane/config/templates/cluster.yaml: dnsMasqMetricsImage.repo
The `repo:` key for `dnsMasqMetricsImage` was missing
Fixes #796
> Issue #796 - cluster.yaml missing dnsMasqMetricsImage.repo key

- Documentation/kubernetes-on-aws-cloudformation-streaming.md
- README.md
- cfnstack/provisioner.go
- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
- core/root/cluster.go
This feature will allow CouldFormation stack events to be streamed to the console (stdout) during a `kube-aws up` or `kube-aws update` operation.
The format of the messages are:
```
TimePassed   StackName   ResourceStatus    LogicalResourceId   StatusReason
```
For example:
```
+00:02:45	Nodepoolb	CREATE_IN_PROGRESS      		WorkersLC             	"Resource creation Initiated"
+00:02:45	Nodepoolb	CREATE_COMPLETE         		WorkersLC
+00:02:48	Nodepoolb	CREATE_IN_PROGRESS      		Workers
```
> CloudFormation events stream to stdout during kube-aws up/update

- core/controlplane/config/templates/cloud-config-controller
This PR separates the node drainer into two components: the ASG watcher, and the node drainer itself.
The ASG watcher is the component (that runs as a Deployment) responsible for using the AWS AutoScaling API to check whether there are any instances waiting for termination; if anything is changed in the status of any ASG-controlled instances, the script updates the ASG status ConfigMap with the IDs of the instances being terminated. This ConfigMap is mounted in every node, and is used by the node drainer pods, which run as a DaemonSet.
The node drainer pods are responsible for checking whether the instance ID corresponding to the node they are running in are listed in the ASG status ConfigMap (it does that by mounting the ConfigMap as a volume in order to avoid hitting the API Server …
> Refactor node drainer implementation

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
Main motivation for us is to utilize
https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
Anything from https://kubernetes.io/docs/admin/kubelet/
can be potentially used as a value
> Ability to propagate custom options to kubelet

- core/controlplane/config/templates/cloud-config-controller
For https://github.com/kubernetes-incubator/kube-aws/issues/685.
Permission set taken from upstream
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/heapster-rbac.yaml
Remove a few inconsistencies in kube setup such as heapster version in
the name and dashboard not being a replication controller any more.
> Additional permissions for heapster nanny

- contrib/kube2iam/kube2iam-calico-ds.yaml
- contrib/kube2iam/kube2iam-flannel-ds.yaml
- contrib/kube2iam/rbac.yaml
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
When `kube2iam` support is enabled and the DaemonSet was deployed,
`kube-resources-autosave` will fail to save the cluster state to S3 due
to missing role.
I added a condition to assign the `controller` role to
`kube-resources-autosave` deployment and also created examples for
`kube2iam`configuration.
> Fix kube-resources-autosave when kube2iam is enabled

- proposals/plugins.md
For https://github.com/kubernetes-incubator/kube-aws/issues/509
> Initial plugins proposal

- README.md
git clone can make the directory automatically which is specified as the last argument
> Remove redundant step

- core/controlplane/config/templates/cloud-config-controller
These changes add the functionality so that cfn-signal fires if and only if the install-kube-system has finished successfully.
We add StartLimitInterval of 5m20s as a timeout value, so that the service does not cycle indefinitely on "ExecStartPre=/usr/bin/systemctl is-active install-kube-system.service"
> cfn-signal depends on install-kube-system

- cfnresource/naming.go
- cfnresource/naming_test.go
- core/controlplane/config/config.go
- core/nodepool/config/config.go
- test/integration/maincluster_test.go
When creating iam roles for the controller or node pools, validation checks for the whole string consisting of `<cluster_name>-<nested_stack_name>-<12_characters_random_alphanumeric_characters>-<region>-<iam_role_name>`. The validation works as intended if `iam.role.name` is not specified and auto-generated.
However when `iam.role.name` is specified, kube-aws is actually creating `<region_name>-<managed_role_name>` so for the following config it'll actually create a role named `<region>-myrole` so a new validation is needed.
```
iam:
role:
name: "myrole"
```
This allows for a little bit more leeway to have a more meaningful name for the fixed role.
> Fix managed role name validation

- book.json
They should be linked to https://github.com/kubernetes-incubator/kube-aws/tree/master/docs/* rather tha https://github.com/kube-aws/docs/tree/master/*
> "Edit This Page" links on the doc is linking to wrong places

- docs/getting-started/step-6-configure-add-ons.md
The "destroy your cluster" link doesn't work in https://kubernetes-incubator.github.io/kube-aws/getting-started/step-6-configure-add-ons.html
@c-knowles Merging this would result in the doc site automatically updated by #859
> doc: Fix the link from the getting-started/addons page to the next

- README.md
- docs/SUMMARY.md
- docs/guides/README.md
- docs/guides/developer-guide.md
Since we need to keep `CONTRIBUTING.md` as the contributors guide,
renamed the documentation version to Developer Guide.
> Tidy contributor/developer guide

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
After https://github.com/kubernetes/kubernetes/pull/48707, we can now add support for the node authorizer + node restriction admission controller to kube-aws without breaking our node drainer implementation.
In order to use this, Kubelets must use certificates that conform with the username/group restrictions documented [here](https://kubernetes.io/docs/admin/authorization/node/), which makes TLS bootstrapping a prerequisite.
Also, as noted in `cluster.yaml`, this feature can only be used in Kubernetes 1.7.4+. (See #853)
> Add support for Node Authorizer + Node Restriction admission controller

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
This also adds an extension point in `cluster.yaml` so the user can specify a custom version of Tiller.
@mumoshu I noticed the plugin system uses Helm, but it's hosted in a dedicated quay.io repository. If you update it with the latest Helm version, I'll update the references to the Helm image as well.
> Update tiller to v2.6.0

- hack/relnote.go
So that relnote.go will not classify a commit which changes nothing but files under docs/ to be an "other change".
> relnote: Also consider changes under docs/ to be documentation updates

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- etcdadm/README.md
- etcdadm/etcdadm
- etcdadm/test
- model/etcd.go
1. Configure tolerations for kube2iam DaemonSet.
2. Update ETCD version to 3.2.6
etcd v3.2.6 (2017-08-21)
- fix watch restore from snapshot
- fix etcd_debugging_mvcc_keys_total inconsistency
- fix multiple URLs for '--listen-peer-urls' flag
- add 'enable-pprof' to etcd configuration file format
> Configure tolerations for kube2iam DaemonSet. Update ETCD version to 3.2.6.

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
The kube2iam image and tag used for the kube-aws provided kube2iam installation
can be specified in cluster.yaml.
> core: add kube2iam image repo and tag

- hack/README.md
- hack/relnote.go
This is used for gathering the release note of kube-aws v0.9.8 final
> relnote: Add support for release notes of final versions

- core/controlplane/config/credential.go
- core/controlplane/config/encrypted_assets.go
- core/controlplane/config/encrypted_assets_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cloud-config-worker
1. Certificates are not secrets, they can be kept unencrypted
2. If only .enc file is provided and no unencrypted version is found
then don't try to load fingerprint files. This change allows .enc files
to be commited to Git and then used as-is
> Do not encrypt certificate files, dont' load fingerprints if no raw file available

- core/controlplane/config/credential.go
- core/controlplane/config/encrypted_assets.go
- core/controlplane/config/encrypted_assets_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cloud-config-worker
- test/helper/helper.go
TLSBootstap CA is now loaded from worker-ca.pem
Etcd trusted CA bundle is now loaded from etcd-trusted-ca.pem
Both files by default are symlinks to a well known ca.pem
This change enables advanced, more secure setup, where certificates
stored on worker nodes are trusted only by APIserver and NOT
Etcd server. This kind of setup is not yet supported by
"kube-aws render credentials" command out of the box, and
therefore currently requires users to be generating and
encrypting certs on their own to benefit from it.
Depends on  https://github.com/kubernetes-incubator/kube-aws/pull/882
> Dedicated worker CA and Etcd trusted CA bundle

- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/templates/stack-template.json
> Fix too permissive IAM policy for CA associated to controller nodes

- core/controlplane/config/templates/cloud-config-worker
Resolves #803
This is verified to work by seeing the appropriate annotation added on a worker node powered by a spot instance:
```
Annotations:		kube-aws.coreos.com/securitygroups=k8s72-Controlplane-1P1L3VDQ165MB-SecurityGroupWorker-Y3OMIAZXMEHQ
node.alpha.kubernetes.io/ttl=0
volumes.kubernetes.io/controller-managed-attach-detach=true
```
> Add spot fleet support for the `awsNodeLabels` feature

- core/controlplane/config/config.go
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/config.go
- core/nodepool/config/templates/stack-template.json
- test/integration/maincluster_test.go
by fixing the conditional in stack-template.json for worker and controller stacks, while making configuration easier.
Resolves #897
The intended way of enabling cluster-autoscaler on your cluster has been to:
1. Set `addons.clusterAutoscaler.enabled` to `true`
2. Set `experimental.clusterAutoscalerSupport.enabled` to `true` to allow CA to be run on controller nodes, while providing appropriate IAM permissions to the controller nodes
3. Set `worker.nodePools[].clusterAutoscalerSupport.enabled` to `true` to allow CA to be run on worker nodes, while providing appropriate IAM permissions to the worker nodes
4. Finally, set `worker.nodePools[].autoscaling.clusterAutoscaler.enabled` to `true` for registering the node pool(s) as the scaling targets
Note that:
* 1. is required in order to deploy …
> Fix the scheduling and permissions issue of CA

- core/controlplane/config/encrypted_assets.go
> Fix the hard-coded duration until an etcd cert generated by kube-aws expires

- core/controlplane/config/config.go
- core/controlplane/config/encrypted_assets.go
- core/controlplane/config/encrypted_assets_test.go
- core/controlplane/config/user_data_config_test.go
- core/nodepool/config/config.go
- core/root/render/credentials.go
- e2e/run
- test/helper/helper.go
It seems to have broken at some point.
This is verified to fix the problem by creating a cluster with a configuration which requires ca-key.pem to be deployed on controller nodes:
```
cd e2e && EXISTING_CA=1 RBAC=1 NODE_AUTHORIZER=1 KUBE_AWS_USE_CALICO=1 ETCD_DISASTER_RECOVERY_AUTOMATED=1 ETCD_SNAPSHOT_AUTOMATED=1 ETCD_COUNT=1 CONTROLLER_COUNT=1 KUBE_AWS_CLUSTER_NAME=clustername bash -c './run all'
```
and an another one which doesn't require ca-key.pem on controller nodes:
```
cd e2e && EXISTING_CA=1 ETCD_COUNT=1 CONTROLLER_COUNT=1 KUBE_AWS_CLUSTER_NAME=clustername bash -c './run all'
```
Fixes #839
cc @danielfm @kamatama41
> Fix the existing TLS CA support

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- e2e/run
- test/integration/maincluster_test.go
Resolves #655
**Release note**:
* If you had never enabled RBAC before, you might have not configured appropriate cluster role/role binding/service account for your apps. It is strongly recommended to do so before upgrading your cluster or otherwise your apps may fail due to missing RBAC permissions.
* Although it isn't recommended for security, you can also retain the existing behavior that all the service accounts have all the permissions by running the following command to create permissive RBAC permissions:
```
kubectl create clusterrolebinding permissive-binding \
--clusterrole=cluster-admin \
--user=admin \
--user=kubelet \
--group=system:serviceaccounts
```
> Enable RBAC by default

- core/controlplane/config/config.go
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
> Remove `experimental.plugins.rbac` from cluster.yaml

- core/nodepool/config/config.go
- test/integration/maincluster_test.go
> Emit errors when unknown keys are specified under `worker.nodePools[]`

- core/controlplane/cluster/cluster_test.go
- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/nodepool/config/deployment.go
- model/controller.go
- model/derived/api_endpoint_lb.go
- model/etcd.go
- model/subnets.go
- model/subnets_test.go
- test/integration/maincluster_test.go
Resolves #929
**Release note**:
* `mapPublicIPs` is removed in favor of `apiEndpoints[].loadBalancer.private`
* `mapPublicIPs: true` should be migrated to `private: false` and vice versa
* `routeTableId` is removed in favor of `subnets[].routeTable.id` in order to reduce gotchas and implications in configuring controller and etcd subnets
> Remove `mapPublicIPs` and `routeTableId` in the top-level of cluster.yaml

- cmd/init.go
- core/controlplane/cluster/cluster.go
- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/cluster/cluster_test.go
- docs/getting-started/step-2-render.md
- model/api_endpoint_lb.go
- model/api_endpoints.go
- test/integration/aws_test.go
- test/integration/maincluster_test.go
- test/integration/nodepool_test.go
- test/integration/plugin_test.go
by preventing the Route53 misconfiguration.
The `--hosted-zone-id` flag and the corresponding `hostedZone.id` key in cluster.yaml are now required by default. You can explicitly omit them by setting `--no-record-set` or `recordSetManaged: false`. This way, one can't omit hosted zone id without knowing the implication of omitting the hosted zone id.
Resolves #928
> Remove `createRecordSet` to help newcomers bring up their first clusters

- core/controlplane/cluster/describer.go
- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- model/api_endpoint_lb.go
- model/api_endpoints.go
- model/derived/api_endpoint_lb.go
- model/derived/api_endpoints.go
- model/region.go
- test/integration/maincluster_test.go
This adds support for an optional `type` attribute to `apiEndpoints[].loadBalancer`, which supports the following values:
- _undefined_ (defaults to Classic ELBs, just like before)
- `type: classic` (same as above)
- `type: network` (provisions a Network Load Balancer instead of a Classic ELB)
The idea is to use NLB-backed API endpoints for worker nodes in an attempt to mitigate issues like #598.
The first version implemented in this PR has a few limitations:
- It can only be used if load balancer is managed by kube-aws, that is, we cannot set `type: network` when specifying the load balancer `id`
- It allows inbound connections to TCP port 443 from the VPC CIDR to the controller security group if at least one NLB-backed API endpoint is defined (see below)
A few considerations regarding …
> Add initial support for NLB API endpoints

- core/controlplane/config/templates/stack-template.json
The nodeDrainer was broken and complaining about this IAM permission when we disabled experimental.clusterAutoscalerSupport in our cluster.
> Add in missing ASG IAM permission for experimental.nodeDrainer.

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
This PR changes the way of deploying kube-proxy; instead of deploying it via a Pod manifest on every node, it creates a `DaemonSet` that tolerates every possible taint.
The way this was implemented does not break any kube-aws feature, most notably the ability to use different API endpoints in different node pools. (This is why the kube-proxy kubeconfig file was not deployed as a `ConfigMap`, [as is done by kubeadm](https://github.com/kubernetes/kubernetes/blob/9d725da4c38ddbce5f8aec6b881df1e2f310c457/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L22-L48))
Closes #793.
> Convert kube-proxy to a DaemonSet

- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- model/gpu.go
- test/integration/maincluster_test.go
This PR fixes the build process for building NVIDIA drivers. It also adds support for P3 and G3 instances.
> GPU Build Fix + Adding G3 and P3 Instances

- core/controlplane/config/templates/cloud-config-controller
An issue was encountered where RBAC was turned on in cluster and the new controllers started rejecting all communication from the 'old' workers.
The controllers have no check for problems like this, so their cfn-signal returned 'true' to cloud-formation, which triggered the update of the worker nodepools.
The controllers should not be considered healthy/deployed-successfully if a new apiserver instance cannot receive communication from the existing workers.
> Check to ensure new API servers can receive communication from workers

- core/controlplane/cluster/cluster_test.go
- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/cluster/cluster_test.go
- model/root_volume.go
- model/volume_mount.go
- test/integration/nodepool_test.go
Max IOPS is `20000` not `2000` according to https://github.com/kubernetes-incubator/kube-aws/blob/master/vendor/github.com/aws/aws-sdk-go/models/apis/autoscaling/2011-01-01/api-2.json#L970 and https://aws.amazon.com/ebs/details/
> Fix max iops typo

- core/controlplane/config/templates/cloud-config-controller
We had noticed that there wasn't a check for the kube-proxy healthz endpoint in the cfn-signal service.
We hit an issue where the cfn-signal was firing, but the proxy was not healthy (it could not talk to the API-server). We've added this check to make sure the proxy is healthy before allowing the cfn-signal to fire.
Out of interest -- was there a reason this check wasn't included in the command before?
The port used for the kube-proxy healthz can be seen here: https://github.com/kubernetes/kubernetes/blob/v1.7.0/pkg/master/ports/ports.go#L41-L43
> Add kube-proxy health check

- core/controlplane/config/templates/cluster.yaml
They all have `enabled` flags so uncommenting them means:
- Highlighting in IDE/text editor works right away and we can easily spot validation problems (current indentation is actually wrong in our comments)
- Easier to diff between newly generate cluster.yaml and existing ones in source control as not hundreds of different lines changes, just some boolean values. Changes to default values are more obvious.
- We don't have comments in comments
We could extend this pattern to other properties. Empty strings could mean off/disabled and other defaults could be uncommented rather than spread here and throughout the code base.
> Experimental addons can all be uncommented

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
This adds an experimental option to enable the "AlwaysPullImages" admission plugin.
Per https://kubernetes.io/docs/admin/admission-controllers/#alwayspullimages as of now:
> This plug-in modifies every new Pod to force the image pull policy to Always. This is useful in a multitenant cluster so that users can be assured that their private images can only be used by those who have the credentials to pull them. Without this plug-in, once an image has been pulled to a node, any pod from any user can use it simply by knowing the image’s name (assuming the Pod is scheduled onto the right node), without any authorization check against the image. When this plug-in is enabled, images are always pulled prior to starting containers, which means valid credentials are required.
> Adding AlwaysPullImages admission controller option

- core/controlplane/config/credential.go
- core/controlplane/config/encrypted_assets.go
Fixes #1003 
@c-knowles Would this work for you?
> Fix the render command to not wipe ca.pem

- core/controlplane/config/credential.go
- core/controlplane/config/encrypted_assets.go
- core/controlplane/config/templates/cloud-config-controller
- check-worker-connection was failing when audit logging is disabled
- In addition to that, it was failing since K8S v1.8 due to the change in K8S that no audits are logged when missing an audit policy file
Follow-up for #991 and #996 
Fix for https://github.com/kubernetes-incubator/kube-aws/pull/991#commitcomment-25459898
Depends on #1014
>  Fix kubelet-to-apiserver connection checks on controller nodes not to fail in certain cases

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cloud-config-worker
Tested and working.  This is the same defaults for sshd_config taken from the upstream CoreOS alpha with the addition of:
```
PasswordAuthentication no
ChallengeResponseAuthentication no
```
> fixes #990 disable sshd password authentication

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-worker
kube-node-label now retries until at most 10 seconds pass.
It is 7 seconds longer for controllers and 10 seconds longer for workers.
Resolves #866
cc @danielfm This is a fix for the issue you've reported before.
> Make kube-node-label more reliable

- core/controlplane/config/templates/cloud-config-controller
This commit removes "rbac.authorization.k8s.io/v1beta1=true" from "--runtime-config" option as well.
Fixes #955
> Update RBAC API version to v1 from v1beta1

- core/controlplane/config/templates/cloud-config-controller
Use templated image for metrics-server
Fix a bug in `install-kube-system.service` introduced in #973
> Use templated image for metrics-server.

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- model/spot_fleet.go
Closes #1022
Depends on #1023
Please see [the third commit](https://github.com/kubernetes-incubator/kube-aws/pull/1024/commits/e15af51297f2edad5736d014e56a95920ac7ec3a) for reviewing changes independently from the PR this is dependent on.
> Fix the default FleetIamRole

- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/templates/stack-template.json
- model/ec2_instance.go
- model/spot_fleet.go
@c-knowles Would this be what you had needed?
This feature will be handy when e.g. your monitoring tools discovers EC2 instances and then groups resource metrics with EC2 instance tags.
Changes:
- Add support for stackTags to SpotFleet-based node pool
- Add a new configuration key `instanceTags` to cluster.yaml per `worker.nodePools[]`, `controller` and `etcd`.
I recomment to use `stackTags` for adding cluster-wide metadata to all the resources managed by Cfn, whereas `instanceTags` are by definition used for node-group-wide metadata to EC2 instances(node pool name, node role, and anything configurable per node pool for example).
A typical cluster.yaml using both `stackTags` and `instanceTags` would look like:
```yaml
worker:
nodePools:
- name: pool1
instanceTags:
myrole: worker
type: …
```
> Support EC2 instance tags per node role

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cloud-config-worker
A case was encountered where the journald-cloudwatch-logs service was failing, and this caused an issue where the rkt gc cannot unmount the containers and then the number of mountpoints causes the kernel to be unresponsive.
This change adds a cleanup step, so that the container is removed in the case that the service functionality has been interrupted.
> Add rkt container cleanup to journald-cloudwatch-logs service

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
In order to properly support Pod Priorities and Preemption (kubernetes 1.8 https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) we need the Priority admission controler
> Added Priority to the admissioncontrol list

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
Add [experimental] option to use IPVS kube-proxy mode instead of [default] iptables one.
Hope to address performance issues of iptables mode for clusters with big number of nodes and services!
(>20 nodes, >5k services is a big cluster to me)
_We also hope IPVS will handle UDP traffic better (This needs to be validated, a hope-based guess only)_
> Add [experimental] option for using IPVS proxy mode

- core/controlplane/config/templates/cloud-config-controller
According to the [docs](https://kubernetes.io/docs/admin/admission-controllers/), it's strongly recommended to also add the `PersistentVolumeLabel` and `DefaultTolerationSeconds` admission controllers for Kubernetes versions >= 1.6.0.
> Add missing admission controllers

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/config/config.go
Added a flag to enable automatic cert rotation when TLS Bootstraping
is used.
> controlplane config: Rotate Certificates on workers kubelet

- core/controlplane/config/templates/cloud-config-controller
The coreos awscli container image is ancient and unmaintained and defaults to the old V2 signatures. We need to explicitly set V4 signatures to enable this feature to function in all regions, e.g. us-east-2 where only V4 is supported.
> Set V4 signatures to enable kube-resources-autosave to work in all regions

- docs/troubleshooting/known-limitations.md
Update that fixed since Kubernetes 1.7.0 (as noted in the upstream issue)
I've been testing with 1.8 and not see this problem there either.
> Update documentation that hostPort issue fixed since Kubernetes 1.7.0

- core/controlplane/config/templates/cluster.yaml
Following on from #1106, add a small warning that a blank 'amiId' can lead to all instances being rolled during any 'kube-aws update'.
> Warn that 'kube-aws update' can replace all if 'amiId' is blank

- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
- model/addons.go
Continuation of https://github.com/kubernetes-incubator/kube-aws/pull/1032
Added the yaml option and rebased onto the current master.
> Allow exposing several ports so that external Prometheus can scrape K8S system components' metrics

- core/controlplane/config/templates/cluster.yaml
- core/nodepool/config/config.go
- core/nodepool/config/config_test.go
This PR implements what was discussed in 
https://github.com/kubernetes-incubator/kube-aws/pull/1086#discussion_r159886263
In short: When we enable `rotateCerts` apart from the required flag, the feature gate `RotateKubeletClientCertificate` should be also added automatically.
> Add RotateKubeletClientCertificate feature gate automatically when rotating certificates

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
I have an scenario where kube-dns needs to be deployed on controllers instead of K8s workers. I have added a flag to allow this configuration.
> conditionally deploy kube-dns to controllers

- cfnstack/provisioner.go
- core/controlplane/cluster/cluster.go
- core/controlplane/config/config.go
- core/nodepool/cluster/cluster.go
- core/root/cluster.go
- core/root/destroyer.go
- model/cloudformation.go
An optional setting named `cloudformation.roleARN` is added to `cluster.yaml` to instruct CloudFormation to use the specific IAM role to manage the IAM policy associated to it.
This is useful when your own IAM role is not open enough to access all the APIs and resources required by a stack operation.
Resolves #1082
> Add support for CloudFormation service role

- core/controlplane/config/templates/cloud-config-controller
This adds a baseline priority of `system-node-critical` to system critical pods, instead of the default value of `0`.
[`system-node-critical`](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/priority/admission.go#L48) is a System Priority class, which is used by system critical pods that should not be preempted by workload pods.
`priorityClassName` is only set if the priority feature is enabled.
> Add priorityClassName to cloud-config-controller

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- model/node_drainer.go
Add [optional] explicit IAM role specification to NodeDrainer.
If you are happy **kube2iam** user depending on your setup you may want **no AWS credentials** being available on pods having no IAM role specifications. At least I believe default access is an evil thing to be avoided.
> Add [optional] explicit IAM role specification to NodeDrainer

- core/controlplane/config/templates/cloud-config-controller
Resolves https://github.com/kubernetes-incubator/kube-aws/issues/1125.
Also both curl and wget used within these scripts, better to use just one of them.
I went with the option to fail fast if the curl fails.
> Swap out wget for curl in node drainer scripts

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
We need to customise these values in our cluster. Seeing as it's always deployed (and not optional) I have just uncommented the `kubeDns` section in `cluster.yaml` and added an `autoscaling` key with the values in it. If you would rather I can add default values in the template so we can keep the config commented out.
> Template kube-dns-autoscaler parameters

- core/controlplane/config/templates/cluster.yaml
The template cluster.yaml references ```kubeDashboardImage```, but throws an ```Error: Failed to initialize cluster driver: file cluster.yaml: unknown keys found: kubeDashboardImage``` when uncommented.  Code appears to read the key from ```kubernetesDashboardImage```
> Fix Key name for kubernetesDashboardImage

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
In order to support Istio automatic sidecar injection in Kubernetes 1.9, these two experimental admission controllers are required.
https://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use
https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection
> Add Mutating/ValidatingAdmissionWebhook to Admission Control List

- core/controlplane/config/templates/stack-template.json
core/controleplane/config/templates
When scaling from 0 -> n nodes we require DescribeAutoscalingGroups in order to scale up based on docs: https://github.com/kubernetes/autoscaler/blob/5302c37d6d6e89a2eeac0c74b4afe6caadfa3340/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0
fixes: https://github.com/kubernetes-incubator/kube-aws/issues/1169
> added autoscaling:DescribeAutoScalingGroups to stack-template

- core/nodepool/cluster/cluster.go
- core/nodepool/cluster/cluster_test.go
Improved tests and code to respect changes in EC2 validate volume API. We can no longer submit IOPS 0 as being synomous with unset field / null.
In `core/nodepool/cluster.go`, the function: `validateWorkerRootVolume` is changed to call an another function to generate EC2 volume parameters. Also tweaked tests around that.
> Fix validation failure on gp2 volume type for node pools

- core/controlplane/config/templates/stack-template.json
core/controleplane/config/templates
When scaling from 0 -> n nodes we require DescribeAutoscalingGroups in order to scale up based on docs: https://github.com/kubernetes/autoscaler/blob/5302c37d6d6e89a2eeac0c74b4afe6caadfa3340/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0
fixes: https://github.com/kubernetes-incubator/kube-aws/issues/1169
> Enable DescribeLaunchConfigurations

- README.md
- cmd/calculator.go
- cmd/init.go
- cmd/up.go
- cmd/update.go
- cmd/validate.go
- core/controlplane/cluster/cluster.go
- core/controlplane/cluster/cluster_test.go
- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cluster.yaml
- core/nodepool/cluster/cluster_test.go
- core/nodepool/config/config_test.go
- core/root/cluster.go
- core/root/options.go
- docs/cli-reference/README.md
- docs/getting-started/step-2-render.md
- docs/getting-started/step-3-launch.md
- docs/getting-started/step-4-update.md
- docs/getting-started/step-5-add-node-pool.md
- docs/tutorials/quick-start.md
- test/integration/aws_test.go
- test/integration/maincluster_test.go
- test/integration/nodepool_test.go
- test/integration/plugin_test.go
Integrates `--s3-uri` flag into the cluster.yaml. Only `init` command require this flag now.
I'm not a go expert, so, help wanted here ;)
> Integrate s3-uri flag into cluster.yml

- core/controlplane/config/templates/cloud-config-controller
Currently Tiller Deploy is running as a cluster admin through the default service account.
This PR gives the tiller deploy its own service account binded to a cluster role with only the correct permission scope (taken from here).
Resolves #878
For the future, it would be worth checking if anything else is running with the default service account binded to a role with more permissions than it needs.
> Dedicated Service account / Cluster Role for Tiller Deploy

- cmd/init.go
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
> Make CoreOS AMI ID mandatory in cluster YAML

- core/controlplane/config/templates/cloud-config-controller
is a workaround for #1196 when metrics server is disabled
> do not use metric server when metricsServers addon is disabled

- core/controlplane/config/templates/cloud-config-controller
This is a modification of #1202. Originally tiller ran with the default service account bound to cluster-admin which is quite bad when you consider that everything that is created without a specified service account will be assigned the default and thus be able to do ANYTHING with the cluster. That's no longer the case.
I ran into an issue when attempting to install the prometheus-operator chart with these new permissions. These permissions are too restrictive and thus don't allow for the creation of service-accounts and cluster role bindings, which it will need when installing these kind of charts.
The easy fix is to bind the new tiller service account added in #1202 to cluster-admin. Ideally, I'd like this to prompt a discussion about what exactly tiller should have permission to do by …
> Fix issue with tiller having to restrictive permissions

- core/controlplane/config/credential.go
- core/controlplane/config/encrypted_assets.go
- core/controlplane/config/templates/cloud-config-controller
kube-aws presently assumes that we will always use the apiservers key for signing service-accounts.  This change separates the service-account-signing-key into its own asset.
Behaviour:-
* New clusters get separately generated apiserver-key.pem and service-account-key.pem keys.
* Where deploying to an existing cluster the service-account-key.pem will be copied from the apiserver-key.pem file.
* Where users specify their own service-account-key.pem file, that will be used.
Related issue: https://github.com/kubernetes-incubator/kube-aws/issues/1226
> Enable user provided service-account-signing-keys

- core/controlplane/config/templates/cloud-config-controller
We have seen an issue where an attempted update to tiller roll bindings is causing a cluster roll/update to fail.
There are some objects and fields in kubernetes that you can not update with a kubectl apply, for example ClusterRoleBindings.  I've added a little logic to handle the failure of kubectl apply by attempting a delete followed by a create when an apply fails.  If the create also fails then the unit will go into a failed state which will prevent cfn-signal from firing and therefore a roll-back.
This change add resilience to the install-kube-system script and will prevent cluster update failures.
> handle kubectl apply failures by trying delete+create

- core/nodepool/config/deployment.go
Apologies, I found another bug with the Self Hosting Networking, this one does not cause any failures, but it does prevent nodes from rolling (and the local flannel becoming de-activated).  When I moved the feature from Experimental to Kubernetes.Networking.SelfHosting, I didn't realise that the settings from the Controlplane do not automatically propagate down to the nodes.
This change corrects this by ensuring that the Kubernetes top level object gets propagated from the control-plane to node.
> Inherit controlplane Kubenetes-Newtworking config in node pools.

- core/controlplane/config/templates/cloud-config-controller
We want to change the version of the KIAMServer but found that the image is hardcoded whereas the client isn't.  Both the client and server should use the same image.
> KIAMImage should affect server as well as client.

- core/controlplane/config/templates/cloud-config-controller
When tainting worker in cluster.yaml, canal daemonset cannot be scheduled on
tainted worker
> [Canal] Support tainted worker

- docs/getting-started/step-2-render.md
I found type at Getting Started. Fix markdown.
> Fix typo of Getting Started.

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
In the present implementation of Kubernetes.Networking.SelfHosting, I have had to work around an issue where if Typha came up before any Calico nodes that it would write a bad global cluster information record which would prevent calico/typha from subsequently correctly starting.
I raised an upstream issue, https://github.com/projectcalico/typha/issues/118, which has now been resolved with the latest releases.  Given that the issue is resolved, this change bumps Calico and Typha to the latest releases and removes my work-around for Typha bug (which was polling for the record via an init container).
> Bump Calico/Typha Versions now Typha Issue resolved.

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/cloud-config-worker
- core/controlplane/config/templates/cluster.yaml
> Disable coreOS auto-updates

- core/controlplane/config/templates/cloud-config-controller
Stops cfn-signal service from failing in circumstances where the cloud-formation stack has succeeded as in issue https://github.com/kubernetes-incubator/kube-aws/issues/1273
> Allow cfn-signal.service to cleanly start under certain circumstances

- core/controlplane/config/templates/cloud-config-controller
Batch has been beta since k8s 1.8.
Without this it's possible to start getting this error using latest kubectl.
```
{  cronjob} matches multiple kinds [batch/v1beta1, Kind=CronJob batch/v2alpha1, Kind=CronJob]
```
> Disable alpha batch APIs by default

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
- test/integration/maincluster_test.go
The `auditLog.(logpath|maxage)` attribute names were normalized to `auditLog.(logPath|maxAge)`, and added support for the `maxBackup` (which was hard-coded to `1`) and `maxSize` flags.
Also, the `cluster.yaml` now uses the same default value for `auditLog.logPath` as the one defined in the struct.
> Normalize audit log attribute names in cluster.yaml + add support for missing attributes

- core/controlplane/config/templates/cloud-config-etcd
**PROBLEM**
Running a `kube-aws upgrade` on a working cluster fails to properly restart `etcd` instances, causing a (again failing on the same issue) `UPDATE_ROLLBACK` of the CloudFormation stack.
**CAUSE**
When replacing `etcd` instances, the mounted volume is detached from the old instance and attached to the new one. This however can take a few minutes. `Systemd` service `cfn-etcd-environment.service` fails when the volume is not yet available and restarts itself.
Unfortunately depending services are failing because of `systemd` not capable of waiting for restarting failed services! (see snippet below).
After a while the attaching of the volume succeeds, but the depending services are not executed and the instance is not working properly.
```
May 04 15:00:48 …
```
> Fix failing etcd volume attach when upgrading etcd instances

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cluster.yaml
- core/controlplane/config/templates/stack-template.json
Basic tests for cluster autoscaler config.
Bug fix also found during testing - only label the controller nodes if `experimental.clusterAutoscalerSupport.enabled` is set to true (which is the default).
Improved cluster autoscaler documentation as well which will fix https://github.com/kubernetes-incubator/kube-aws/issues/1045
> Cluster autoscaler docs/tests

- cmd/show.go
- core/controlplane/cluster/cluster.go
- core/controlplane/config/encrypted_assets.go
- core/root/credentials.go
- core/root/stack.go
- tlscerts/cert.go
- tlscerts/cert_test.go
- tlsutil/cert.go
- tlsutil/cert_test.go
- tlsutil/pem.go
- tlsutil/pem_test.go
- tlsutil/x509.go
Started with tlsutil - adding tests and cleaning up.
> tlsutil cleanup plus added tests

- core/network/config/templates/stack-template.json
It appears flannel traffic is not permissible among controllers. This pull
request fix this by adding a security group ingress which allows 8472/udp
from other controllers.
When kiam support is enabled, kiam-server tries to discover grpclb by querying
DNS. If kube-dns is running on controllers and there are multiple controllers,
the DNS name may not be resolved becuase kiam-server cannot contact kube-dns
running on the other controller.
> Fix flannel traffic among controllers

- core/controlplane/config/templates/cloud-config-controller
Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1336 by adding `--configure-cloud-routes=false` when `--allocate-node-cidrs=true`
Added `--cluster-name` to ensure it's set correctly on controller manager.
Grouped mandatory and optional flags together.
> Disable configure of cloud route when allocate-node-cidrs is enabled

- core/controlplane/config/templates/cloud-config-controller
The canal and flannel daemonsets should land on ALL nodes, including those with taints.
Correction of a syntax bug when retrying kubectl commands in add-node-cidrs.
> Make sure that canal and flannel land on all tainted nodes

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/root/config/templates/cluster.yaml
Add support for CoreDNS as DNS provider. Fix https://github.com/kubernetes-incubator/kube-aws/issues/1075
> Add support for CoreDNS as DNS provider

- core/nodepool/config/templates/stack-template.json
- filereader/texttemplate/texttemplate.go
Feature done by looking for instance types that do NOT support EBS optimisation from the AWS page https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html and few extra instances I found from AWS console.
PR for https://github.com/kubernetes-incubator/kube-aws/issues/1252
> Automatically enable EBS optimization

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/nodepool/config/config.go
- core/nodepool/config/templates/cloud-config-worker
- core/root/config/templates/cluster.yaml
I decided to PR back support to [reserve resources](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/) to kube-aws.
If you want more background, the author of a related Kops PR does a fantastic job of documenting his journey/struggle with very similar issues to ours:
https://github.com/kubernetes/kops/pull/2982
I realise this is already been possible with $KUBELET_OPTS but believe the config options important enough to warrant being promoted to first class citizens to give them more visibility alongside the other kubelet config options.
We’ve had problems with Docker daemons locking with loads of orphaned/dead containers lying around not being cleaned up - this is most definitely a docker daemon problem caused by our usage of old AMIs. 
During these …
> Promote compute reservation options [Small] 

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/root/config/templates/cluster.yaml
- test/integration/maincluster_test.go
This is a consolidation of kiam parts into the kiamSupport configuration
It adds the listeners for server and agent as configurable options
The previously KIAMImage type is now underneath kiamSupport, so this is a possible breaking change to existing cluster.yaml files
Now looks like this
```
kiamSupport:
enabled: true
image:
repo: quay.io/uswitch/kiam
tag: v2.8
server: localhost
agent: kiam-server
```
The original DNS health check/server settings are preserved as defaults
The kiam image is bumped to v2.8
> Consolidate kiam configuration

- .gitignore
- cfnstack/cfnstack.go
- cfnstack/cfnstack_test.go
- core/controlplane/cluster/cluster_test.go
- core/controlplane/config/config.go
- core/etcd/cluster/cluster.go
- core/etcd/config/templates/stack-template.json
- core/root/cluster.go
- core/root/config/config.go
- model/etcd.go
- test/helper/cfn.go
- test/integration/maincluster_test.go
- test/integration/plugin_test.go
Checks for the existence of the etcd stack and will bring the etcd servers up in parallel if the stack does not exist, i.e. it is a fresh cluster (or upgrade to nested stacks).  
Behavoir and benefits: -
* Performs lookup of cloudformation stacks before rendering stack templates - cusomises the resource dependencies based the on this result.
* New clusters start up quicker (servers start in parallel)
* Cluster updates still go through etcd one node at-a-time
* Removes the need to concoct a cfn-signal on the early nodes before etcd quorum and healthy cluster is achieved.
> Bring etcd's up in parallel on new cluster / Fail-fast to update 0.10.x clusters with newer kube-aws

- cmd/apply.go
- cmd/up.go
- cmd/update.go
- core/root/cluster.go
Make integration with CI/CD automation tools simpler by having a single 'apply' command that handles the correct cloud formation create or update depending on whether the cluster stacks exists or not.
This change adds an apply command and puts a deprecation message on 'up' and 'update' which then proceed to do an 'apply'.  This is to allow a period of backwards compatibility for people that have existing automations around 'up' and 'update' so they can have a notice period to change over to apply.
> Implement 'apply' command and deprecate 'up' and 'update'

- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/templates/stack-template.json
This change is against the 0.10.x branch, not master, working towards an intended point release of 0.10.x with work to smooth the migration from etcds in the control-plane stack to their own stack in the 0.11.x release.
Remove etcd ENI/EIP outputs from the control plane stack and etcd-environment metadata section on the nodepools if Kubernetes.Networking.SelfHosting is Enabled.
This is not ready for a 0.10.x release - I expect a few more changes will be required.
> Break dependency on etcd from the nodepools

- core/nodepool/config/templates/stack-template.json
Clean up cross-stack dependency that is not needed when use kubernetes as backing store for flannel/calico.
> Remove node dependency on ETCD Stack when Networking.SelfHosting is Enabled.

- build
When doing development/testing of kube-aws the inclusion of the branch in the kube-aws version will be a great help in quickly identifying the binary you are working with.  Now that we display the kube-aws version in the motd this also helps us confirm the geneology of an existing running cluster.
Tag releases unchange - this is only added for untagged developement builds.
> Add branch to build version when not a tagged release

- build
- cfnstack/ec2.go
- core/controlplane/cluster/cluster.go
- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-etcd
- core/controlplane/config/templates/stack-template.json
- core/nodepool/config/templates/stack-template.json
- core/root/config/config.go
- model/derived/etcd_node.go
- test/helper/cfn.go
- test/integration/maincluster_test.go
- test/integration/plugin_test.go
This update to the 0.10.x branch needs to be run in order to allow an in place upgrade from kube-aws 0.10.x to the new 0.11.x release with separate 'network' and 'etcd' stacks.
The following changes have been made:
* When Kubernetes.Networking.SelfHosting is enabled the references to outputs from the control plane stack for etcd ip addresses are removed (they are not needed)
* A Warning is printed when you perform an upgrade without SelfHosting enabled that you won't be able to update to future releases.
* I lookup the CIDRs for the subnets containing the etcd servers and relax the incoming rule to allow connections to the etcds on port 2379 from any servers in the same subnets.  This is needed because the etcds in the new stack need to be able to connect across to the existing etcds. …
> 0.10.x migration preparation release

- docs/getting-started/step-2-render.md
the region specified should be `us-east-1` to match the description above it.
> getting started: fix typo in bucket creation

- logger/logger.go
This was bugging me, especially on the streamed logs from cloudwatch.  By adding the colour off character after the output string (which included the newline) the logging library Output method will add another new line: -
e.g.
logger.Infof("My log message contains a newline\n") -> "CyanOn" + "My log message contains a newline\n" + DefaultColour + "\n"
Colourize the log line and add the colour off character before any trailing whitespace/newlines.  Now the logs are in colour without the double line spacing!
> Fix colour causing extra newlines

- core/controlplane/config/templates/cloud-config-controller
- core/nodepool/config/templates/cloud-config-worker
A small change to make it easier to quickly differentiate different nodepools of kube-aws clusters.   Presently we label all nodes with the role of 'node', which we can see when we call kubectl get nodes: -
```
NAME                                         STATUS    ROLES     AGE       VERSION
ip-10-29-12-160.us-west-2.compute.internal   Ready     node      2d        v1.10.4
ip-10-29-12-162.us-west-2.compute.internal   Ready     master    1d        v1.10.4
ip-10-29-16-25.us-west-2.compute.internal    Ready     node      15d       v1.10.4
ip-10-29-20-142.us-west-2.compute.internal   Ready     master    1d        v1.10.4
ip-10-29-21-214.us-west-2.compute.internal   Ready     node      15d       v1.10.4
ip-10-29-28-38.us-west-2.compute.internal    Ready     node      15d       v1.10.4 …
```
> Better identification of nodes

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/nodepool/config/templates/cloud-config-worker
- core/root/config/templates/cluster.yaml
- Bump calico images for self hosted Calico (non-self hosted is EOL)
- Include latest CRDs and RBAC for canal from https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/flannel
- Correct the self hosted flannel images to self hosted config (previously unused)
- Mount calico dirs in canal and kubelet to fix pod init issue, ref https://github.com/projectcalico/calico/issues/1795#issuecomment-390171235
Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1396
> Self hosted calico v3.1.3

- core/controlplane/config/templates/cloud-config-controller
- core/etcd/config/templates/cloud-config-etcd
- core/nodepool/config/templates/cloud-config-worker
- model/custom_file.go
- model/custom_file_test.go
We want to remove our customisations to kube-aws from our forked branch and would like to move some of those customisations from the kube-aws code into our cluster.yaml files.  Some of these customisations need to lookup cluster configuration information and so need to be templates rather than simple strings.
This change extends to the CustomFile type to add a template field and adds a new Render function that will automatically render the template if it is present or render our the simple content as before (plus some tests of these operations).
> 0.11.x Extend CustomFiles to be able to render go templates

- core/controlplane/config/templates/cloud-config-controller
- core/controlplane/config/templates/cluster.yaml
Please can we include this change in the 0.10.x release?  It would help us greatly if we can include these two customFile changes so that we can move some of our code out of our fork of kube-aws and closer to using the upstream version instead.
This change patches 'install-kube-system' so that it will kubectl apply any manifest files written to /srv/kubernetes/manifests/custom/*.yaml
> 0.10.x Add kubernetes manifests from customfiles

- core/controlplane/config/templates/cloud-config-controller
- core/root/config/templates/cluster.yaml
We would like to be able to install kubernetes objects through kube-aws using our customFile directives on the controller, giving us a way of extending kube-aws without maintaining our own fork of it.
This PR adds the functionality into install-kube-system to pick up any manifests that have been written to /srv/kubernetes/manifests/custom/*.yaml.  This is intended for only advanced users as failing to install these manifests will cause the update to fail and roll back.
Also fixed an issue with the code where a variable 'mfdir' was redeclared mid-way through the script confusing maintainers as to its correct value.
> 0.11.x Add kubernetes manifests from customfiles

- core/controlplane/config/templates/cloud-config-controller
At least in our setup, most containers are named after the application and these just show as `main` in the Datadog monitoring.
> Differentiate the node drainer containers

- core/controlplane/config/config_test.go
- core/root/config/templates/cluster.yaml
It seems `storage` is no longer a valid value since k8s 1.8.
Fixes `failed to run Kubelet: cannot reserve "storage" resource`
Ref https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/ and https://github.com/kubernetes/kops/issues/3576 and https://github.com/kubernetes/website/pull/9532.
> Update reserved storage flag name

- core/controlplane/config/templates/stack-template.json
Upgrading can cause cfn error and rollback: 
```
+00:00:14    UPDATE_FAILED                   Controlplane              "Embedded stack arn:aws:cloudformation:us-west-2:034324643013:stack/ko-Controlplane-U7SB0W9VL40E/8bd91500-6e32-11e8-871f-50a68af39629 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: Export ko-Controlplane-U7SB0W9VL40E-Etcd0PrivateIP cannot be deleted as it is in use by ko-Nodepoola-ACYQ1L68QT9X, ko-Nodepoolb-25KUVVCIZCN1 and ko-Nodepoolc-9GE9825UJZHU"
```
This is because the v0.10.1 release tries to remove some outputs from the controlplane stack before the nodepools have remove their use of it.
This resolves issue https://github.com/kubernetes-incubator/kube-aws/issues/1411
Apologies, I think this might have to be a quick 0.10.2 …
> Resolve CFN dependency issue when updating to v0.10.x

- core/controlplane/config/templates/cloud-config-controller
- core/etcd/config/templates/cloud-config-etcd
- core/nodepool/config/templates/cloud-config-worker
- model/custom_file.go
Fix - pass whole context not just the current context
Use kube-aws texttemplate pkg so that all kube-aws funcmaps can be used, e.g. default, fingerprint etc.
> Improve customFile templating

- build
I had an cluster roll failed with the cloudformation failure...
```
+00:08:02	UPDATE_FAILED           		APIEndpointDefaultELB 	"One or more tags are not valid"
+00:08:03	UPDATE_FAILED           		IAMRoleController     	"Resource creation cancelled"
+00:08:03	UPDATE_ROLLBACK_IN_PROGRESS		davem-lab-secure-Controlplane-1RO8IL4N198PU	"The following resource(s) failed to update: [APIEndpointDefaultELB, IAMRoleController]. "
+00:08:10	UPDATE_FAILED           		Controlplane          	"Embedded stack arn:aws:cloudformation:us-west-2:034324643013:stack/davem-lab-secure-Controlplane-1RO8IL4N198PU/77ca9b10-8a7a-11e8-a97b-50d5ca789e4a was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [APIEndpointDefaultELB, …
```
> Remove invalid aws tag symbols from branch names

- core/root/config/templates/cluster.yaml
the line configuring the maxBatchSize in the waitSignal config contained one
whitespace too much which made the kube-aws validation step fail if the config
was used
> cluster.yaml: removed whitespace in waitSignal configuration

- core/network/config/config.go
When embedding kube-aws in another go tool we want to be able to pull it in using dep ensure.  dep refuses to pull in empty packages and so does not like the network/config package which is empty until a build is performed and the templates.go file generated.
Committing this stub file satisfies dep and allows it to successfully pull in kube-aws.
> Fix dep ensure empty package issue

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/root/config/templates/cluster.yaml
- model/addons.go
- test/integration/maincluster_test.go
Exposing cluster autoscaler options via cluster.yaml
I'd like to be able to configure the cluster-autoscaler to make it more sensitive.
We have a lot of clusters of different shapes/sizes/responsibilities. One cluster in particular runs only 1 app (don’t ask :sadpanda:) which I believe makes it incompatible with the cluster-autoscaler default settings. We recently incurred the following outage:
- cluster-autoscaler scaled down the cluster to give just enough nodes to accommodate the 15 replicas of our app.
- team deployed new app version
- rolling update strategy of maxSurge=20% caused 3 new replica's to be added
- these 3 new replica's couldn't fit in the cluster
- cluster-autoscaler kicked in and started to provision new nodes, but new resources weren’t available in time and created a …
> Add ability to configure flags for cluster-autoscaler-de.yaml [Small]

- core/controlplane/config/templates/cloud-config-controller
This PR is to solve the reported issue: https://github.com/kubernetes-incubator/kube-aws/issues/1424
The fix is to move the installation of kube-proxy up in the install-kube-system script, so it gets
a chance to start before the installation checks for it and goes into a loop.
> Fix kube-proxy startup race condition when metric server is enabled.

- core/etcd/config/templates/stack-template.json
- core/root/config/templates/cluster.yaml
- model/etcd.go
- model/etcd_test.go
- test/integration/maincluster_test.go
This Pull request is to address the option of passing arguments to `/usr/local/bin/etcd` such as setting `--quota-backend-bytes` accordingly to the size of the etcd nodes. 
Apologize for my rusty Golang and I am pretty sure there are more places I need to change. Really appreciate your feedback.
> [Feature] Add more etcd options

- core/nodepool/cluster/cluster_test.go
- core/root/config/config.go
- core/root/config/templates/cluster.yaml
- core/root/config/templates/stack-template.json
- core/root/template_params.go
- model/node_pool_config.go
- test/integration/maincluster_test.go
Ability to toggle in your `cluster.yaml`  file at a `nodePool:` or `worker:` level whether nodePools are going to be rolled out / rolled in sequentially or concurrently
After doing a fair share of rolls, it was noticed that at times, platforms are more resilient to a full `Availability Zone` going down rather than having 1 `nodePool` going down in each respective `Availability Zone`. Since sometimes it is needed to roll out nodePools in sequential order, it would be easier to have it as a toggleable option in your `cluster.yaml`.
This should allow for easier switching between rolling out workers sequentially or concurrently.
* In the root stack-template, I made it so that when we loop through our currently declared `nodePools` we store their index. In the `DependsOn` field, I have added …
> feat: Ability to toggle node pool rolling strategy between Sequential and Parallel

- core/controlplane/config/templates/cloud-config-controller
This PR fixes a bug I found, where a controller install fails if you do not have kiam support enabled. This is due to the fact that mfdir was not being set before the kube-proxy-ds.yaml was being applied because the setting was locked above in the kiam section.
I don't feel there is a need to set it twice (in cases where kiam is enabled), and because it's required I just placed it near the top of the script below vols.
> Fix mfdir setting to prevent controller install failure w/ KIAM disabled

- core/controlplane/config/templates/cloud-config-controller
Our perf team flagged up some repeated dns failures under load and tracked the issue down to the kube-dns dnsmasq configuration. This has since started hitting us hard in clusters running CI builds, causing lots of intermitted failures.
We believe the issues is resolved in [dnsmasq 2.79](https://github.com/PowerDNS/dnsmasq/blob/ebedcbaeb8c0e356077fba126f22a4049d52638b/src/dnsmasq.c#L225) so we've put in a [PR to kube-dns](https://github.com/kubernetes/dns/pull/262) to hopefully get a new kube-dns image built/released.
I plan on removing this explicit flag once the underlying dnsmasq is updated and the image is released.
I've chosen to PR this into kube-dns now as we view the failures pretty annoying and hard to debug, plus we don't have a hard timeline on a fresh kube-dns being cut.
That …
> Explicitly set default dnsmasq min-port [Tiny]

- core/controlplane/config/templates/stack-template.json
When I worked on the custom kiam role PR I overlooked the fact that kube-aws autogenerates the controller policy:
* By default, kube-aws will create an `IAMManagedPolicy` for the controller, after it creates an `IAMControllerRole` and attaches the ManagedPolicy to it.
* If you use a pre-existing role (through the `useStrict` feature implemented in the custom kiam role PR), the `IAMManagedPolicy` gets generated, but it does not get attached to any role. It would be up to the developer to manually attach it in the console or through the aws cli. Moreoever, since the controller policy will always have a randomly generated name it complicates things.
In my personal opinion this is a bug. When using a pre-existing IAM role everything should work just as before.
To fix this, I added an `if` …
> fix: Attach kube-aws controller policy to pre-existing IAM role

- Gopkg.lock
- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/network/config/templates/stack-template.json
- core/nodepool/config/deployment.go
- core/nodepool/config/templates/cloud-config-worker
- core/nodepool/config/templates/stack-template.json
- core/root/cluster.go
- core/root/config/templates/cluster.yaml
The 0.11 release completed the migration from legacy flannel and calico networking to the newer Self Hosting 'canal' or 'flannel' networking daemonsets.
This change is clean up all of the **old code** for that supports the legacy flannel and calico installation and which enabled the migration from legacy to the network daemonsets and makes self-hosting always enabled.  The worker nodes no longer have to have any knowledge/access to the etcd servers as SelfHosting uses the kubernetes api for storage.
This simplifies kube-aws, which is always nice! :)
> 0.12 release: remove legacy networking (less is more)

- core/controlplane/config/templates/cloud-config-controller
The applyall function in the /opt/bin/install-kube-system fails when only one value is
contained in the braces. This corrects the problem by moving the kubernetes-dashboard
role & rolebindings to a dedicated entry.
Fixes #1460
> fix: `KubernetesDashboard.Enabled: false` should not break controllers

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
In looking at whether the networking was working post the 0.11.x upgrade I did find some issues and have have bumped the versions of the images forwards and altered the readiness/liveness checks in line with new behavoir around pods running in the host network.  I also found a couple of init containers that were responsible for writing semaphore files to trigger network migration that can be cleaned up.
> Bump calico/typha/flannel, fix cause of calico/typha restarts

- core/controlplane/cluster/cluster.go
- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- plugin/clusterextension/extras.go
- plugin/pluginmodel/config.go
Plugins can set apiserver command line flags but not kube-controller-manager flags.  This enables these as well.
Intended as part of moving some core functionality into plugins https://github.com/kubernetes-incubator/kube-aws/issues/1469
> Allow plugins to add kube-controller-manager command line flags.

- core/controlplane/config/templates/cloud-config-controller
Improve the handling of kube-dns during node drains / cluster rolls by defining a pod disruption budget that allows 1 instance to be down.
> Add a Pod Disruption Budget on kube-dns

- core/controlplane/config/templates/stack-template.json
- core/root/config/templates/cluster.yaml
- model/iamconfig.go
- test/integration/maincluster_test.go
Separate using a strict name for the control iam role with allowing it to be completely managed externally
- Renames `useStrict: [true|false]` to `managedExternally: [true|false]` changing it to toggle only external management
- Adds `strictName: [true|false]` for toggling only strict naming
This is a cherry-pick of #1474
> 0.12.x: Allow user control over controller.iam.role.name

- OWNERS
When he kindly proposed himself as a maintainer, I couldn't agree more!
@davidmccormick is a long-time contributor to the kube-aws project who has contributed many user-support efforts and patches, enchancements, features, and so on. 
I officially express my appreciation to him and his efforts made so far and my wish that we could together and better maintain kube-aws. Let's add him to the list of approvers and reviewers now. Welcome David!
> Adding davidmccormick as a maintainer of kube-aws

- cfnstack/cfnstack.go
- cfnstack/cfnstack_test.go
- test/helper/cfn.go
Rather than ListStacks without any paging.
Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1479
> Check stack existence via DescribeStacks

- core/controlplane/cluster/cluster.go
- core/controlplane/cluster/cluster_test.go
- core/controlplane/config/config.go
- core/etcd/cluster/cluster.go
- core/network/cluster/cluster.go
- core/root/config/templates/cluster.yaml
- model/cloudformation.go
- model/stack_name_override.go
- model/stack_name_overrides.go
Kube-aws 0.11.x introduced a separate CloudFormation network stack. AWS VPCs are not movable between two CloudFormation stacks. This means that Kube-aws 0.11.x will create a new VPC when upgrading.
Because we added some extra LoadBalancers and RDS Databases that we cannot easily migrate to another VPC without downtime, creating a new VPC is not desired for us.
Therefore, we decided to keep the network stack in the original control plane stack and instead moved the control plane to a new separate stack. This means that we can stick with the original VPC.
The easiest way to do this with Kube-aws without adding legacy code, is by allowing the user to override the CF stacks names of the control plane, network and etcd stacks in cluster.yaml.
This PR adds an option in cluster.yaml to override …
> feat: add CF stackNameOverride in cluster.yaml

- core/controlplane/cluster/cluster.go
- core/controlplane/cluster/cluster_test.go
- core/controlplane/config/config.go
- core/etcd/cluster/cluster.go
- core/network/cluster/cluster.go
- core/root/config/templates/cluster.yaml
- model/cloudformation.go
- model/stack_name_override.go
- model/stack_name_overrides.go
See https://github.com/kubernetes-incubator/kube-aws/pull/1484 for details/comments.
> v0.12.x: feat: add CF stackNameOverride in cluster.yaml

- cfnstack/cfnstack.go
@c-knowles when we changed to using `DescribeStacks` instead of `ListStacks` it now returns an error if the stack does not exist.  This change detects if the error was caused by the stack not existing and returns `false` and `nil` error instead.
This helps prevent errors like when running `validate` or `apply`...
```
kube-aws validate -v
Called RenderStackTemplateAsString on network
testing whether cf stack perf1-XXXbackend-lab-secure exists
calling AWS cloudformation DescribeStacks ->
<- AWS Responded with an error: ValidationError: Stack with id perf1-XXXbackend-lab-secure does not exist
status code: 400, request id: 2c838630-ed7a-11e8-8f78-a39daf096ab7
Error does not match 'ValidationError: Stack with id perf1-XXXbackend-lab-secure does not exist'
failed to initialize cluster driver: …
```
> Change StackExists behaviour

- README.md
- docs/tutorials/quick-start.md
* Add missing backslash to multi-line command
* Reorder kube-aws commands in README to match Quick Start
* Newline end of file
> Minor fixes in documentation

- cmd/render.go
- credential/generator.go
- pkg/model/credentials_test.go
- pki/ca.go
CA self-genereted cert: add the cn flag
all self-signed CA have the samee CN and this can confuse clients like
Chrome. Now we can set different CN
Fixes #463
> CA self-genereted cert: add the cn flag

- builtin/files/stack-templates/network.json.tmpl
- builtin/files/stack-templates/root.json.tmpl
- pkg/api/worker_node_pool.go
fix issue with nodepool names containing a - character.
Properly pass cloudwatch logging arn from root stack into the network stack
> A couple of fixes for nodepool resources and cloudwatch logging

- builtin/files/stack-templates/node-pool.json.tmpl
Found an issue where the network and nodepool stacks are using not using the same name for the worker arn.  Correct by using santized name for both.
> bug: Nodepool stack needs to use the nodepool logical name

- pkg/api/controller.go
Correction/Bug - the IAMRoleController should always be a reference to the cloudformation role object unless it is managed externally, not just because we have used a strict name.
> Fix for using StrictName to define a specific Controller Role Name

- builtin/files/etcdadm/README.md
- builtin/files/etcdadm/etcdadm
- builtin/files/stack-templates/node-pool.json.tmpl
- builtin/files/userdata/cloud-config-etcd
- pkg/api/controller.go
- pkg/api/etcd.go
- pkg/api/etcd_test.go
- Bump etcd version to 3.3.10
- Enable auto-compaction at 1hour by default
- Add etcdadm *compact* and *defrag* commands to allow cluster admins to manually clean up their etcd instances
> Etcd 3.3.10, compaction and defrag

- core/controlplane/config/templates/cloud-config-controller
When running a cluster with the node based dnsmasq resolver enabled, `nodeLocalResolver: true` it is possible that some unqualified names are sent to the upstream name servers for resolution.  This happens when the unqualified name does not match anything in kubernetes.
The `/etc/resolv.conf` in each pod looks like this when using this feature (assuming we're in the default namespace): -
```
nameserver 10.29.15.242
search default.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```
And the `dnsmasq-node` is configured with the following settings: -
```
containers:
- args:
- -v=2
- -logtostderr
- -configDir=/etc/k8s/dns/dnsmasq-nanny
- -restartDnsmasq=true
- --
- -k
- --min-port=1024
- --cache-size=1000
- --server=/cluster.local/192.168.0.3
- …
```
> Do not leak unqualified dns requests to upstream dns servers

- builtin/files/userdata/cloud-config-worker
Always write a kubeconfig file - even when using the TLS bootstrapping feature
Failure to specify a kubeconfig file will result in a failed startup and cryptic "file not found" error message on the kubelet.
> Fix for kubelet startup on nodes when using TLS bootstrapping

- builtin/files/cluster.yaml.tmpl
- builtin/files/stack-templates/root.json.tmpl
- builtin/files/userdata/cloud-config-worker
- core/root/rolling_strategy.go
- core/root/template_params.go
- pkg/model/compiler.go
The default 'Parallel' nodepool rolling strategy is a bit dangerous because it can take down nodes across multiple availability zones and so, if you are unlucky and have an application with only a 1, 2 or 3 pods the parallel roll could take down all of your instances of at the same time - which is definitely not desirable!
The 'Sequential' nodepool rolling strategy is a lot safer because it will only roll a single nodepool at a time, but is slow as a result.  When you have multiple different node pools, or large clusters, you may find that your rolls, although safe, take a long time to complete.
The new 'AvailabilityZone' nodepool rolling strategy fits between the two.  It will roll all of nodepools that belong to the same AWS AvailabilityZone at the same time and roll the availability …
> 'AvailabilityZone' nodepool rolling strategy

- core/root/cluster.go
Hello, I saw this typo when I encountered a problem when running `kube-aws validate`. 😇
> Fixes typo initizlie -> initialize

- builtin/files/userdata/cloud-config-worker
Systemd in newer versions of CoreOS disallows unknown % characters in config files.  Escape the % character used to configure raid0Mounts.
Fixes #1525
> Fix to escape % character in systemd config for raid0Mounts

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/root/config/templates/cluster.yaml
After some issues with DNS in our AWS environments we noticed that we were caching negative DNS responses for longer than we would have expected. This PR is quite general in that it allows us to add our own options for the node local dnsmasq daemonset (which allows us to fine tune our settings, such as the negative ttl setting).
```
kubeDns:
nodeLocalResolver: true
nodeLocalResolverOptions:
- --neg-ttl=10
```
> v0.11.x: Add DnsMasq (node local resolver) command-line arguments/options

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/types.go
After some issues with DNS in our AWS environments we noticed that we were caching negative DNS responses for longer than we would have expected.  This PR is quite general in that it allows us to add our own options for the node local dnsmasq daemonset (which allows us to fine tune our settings, such as the negative ttl setting).
```
kubeDns:
nodeLocalResolver: true
nodeLocalResolverOptions:
- --neg-ttl=10
```
> Master: Add DnsMasq (node local resolver) command-line arguments/options

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/root/config/templates/cluster.yaml
After some issues with DNS in our AWS environments we noticed that we were caching negative DNS responses for longer than we would have expected. This PR is quite general in that it allows us to add our own options for the node local dnsmasq daemonset (which allows us to fine tune our settings, such as the negative ttl setting).
```
kubeDns:
nodeLocalResolver: true
nodeLocalResolverOptions:
- --neg-ttl=10
```
> v0.12.x: Add DnsMasq (node local resolver) command-line arguments/options

- core/root/cluster.go
- core/root/operation_targets.go
https://github.com/kubernetes-incubator/kube-aws/pull/1487 introduced a
bug when doing a partial stack upgrade with a stack name override.
This is fixed by using the actual stack names in operation targets
instead of the hard coded constants.
> fix: Partial upgrades with stack name overrides

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- docs/advanced-topics/kubernetes-dashboard.md
- pkg/api/cluster.go
We ran into some issues with the dashboard being slow at version v1.8.3 and these seem to have gone away in v1.10.1
However in v1.10.1 the skip login option is now disabled by default and requires the use of `--enable-skip-login` flag to bring it back. This has been added in as an option `AllowSkip` in the `KubernetesDashboard` struct and takes a default value of `false`
> Master: Bump default Kubernetes Dashboard version and add AllowSkipLogin option

- core/controlplane/config/config.go
- core/controlplane/config/templates/cloud-config-controller
- core/root/config/templates/cluster.yaml
- docs/advanced-topics/kubernetes-dashboard.md
We ran into some issues with the dashboard being slow at version v1.8.3 and these seem to have gone away in v1.10.1
However in v1.10.1 the skip login option is now disabled by default and requires the use of --enable-skip-login flag to bring it back. This has been added in as an option AllowSkipLogin in the KubernetesDashboard struct and takes a default value of false
> v0.12.x: Bump default Kubernetes Dashboard version and add AllowSkipLogin option

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/nodepool/config/config.go
- test/integration/maincluster_test.go
- test/integration/plugin_test.go
Adding the ability to add feature gates to controller components.
//From kube 1.11 PodPriority and ExpandPersistentVolumes have become enabled by default,
//so making sure it is not enabled if user has explicitly set them to false.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#changelog-since-v1110
This PR ensures PodPriority is disabled if specified in the config
> Porting "Adding the ability to add feature gates to controller components" to 0.11.X

- core/etcd/config/templates/stack-template.json
- core/network/cluster/cluster.go
- plugin/clusterextension/extras.go
- plugin/pluginmodel/config.go
- test/integration/plugin_test.go
Based on the existing test, it seems that the intent was that etcd and networking stacks both could benefit from the cloud formation resources included in the plugins. Unfortunately, there was a bug in the template (in the case of etcd) and missing logic in the case of the networking stack that prevented it from happening.
This PR aims to fix both issues:
- Enable plugin cf resources for networking stack
- Fixing etcd template to add plugin cf resources
> Fixing adding cf resources to etcd and networking stack v.0.11.x

- core/etcd/config/templates/stack-template.json
- core/network/cluster/cluster.go
- plugin/clusterextension/extras.go
- plugin/pluginmodel/config.go
- test/integration/plugin_test.go
Based on the existing test, it seems that the intent was that etcd and networking stacks both could benefit from the cloud formation resources included in the plugins. Unfortunately, there was a bug in the template (in the case of etcd) and missing logic in the case of the networking stack that prevented it from happening.
This PR aims to fix both issues:
- Enable plugin cf resources for networking stack
- Fixing etcd template to add plugin cf resources
> Fixing adding cf resources to etcd and networking stack v.0.12.x

- builtin/files/cluster.yaml.tmpl
- builtin/files/etcdadm/README.md
- builtin/files/etcdadm/etcdadm
- builtin/files/stack-templates/etcd.json.tmpl
- pkg/api/etcd.go
- pkg/api/etcd_test.go
- pkg/api/plugin.go
- pkg/model/stack_new.go
- plugin/clusterextension/extras.go
- test/integration/plugin_test.go
Etcd was upgraded from version 3.2.13 to version 3.3.10 on this PR https://github.com/kubernetes-incubator/kube-aws/commit/e8b7380d95c30239f252eb7ebad7586dd03b0716.
After testing an upgrade from a cluster created with kube-aws 0.12.X to kube-aws master, we have found that, if there is a problem during the upgrade, cloud formation is not able to rollback cleanly, and etcd cluster is left on an unavailable state due to being unable to downgrade etcd.
This is PR Is to revert the etcd upgrade version back to 3.2.13 until a two ways migration is implemented.
> Revert etcd upgrade

- builtin/files/stack-templates/etcd.json.tmpl
- pkg/api/plugin.go
- pkg/model/stack_new.go
- plugin/clusterextension/extras.go
- test/integration/plugin_test.go
Based on the existing test, it seems that the intent was that etcd and networking stacks both could benefit from the cloud formation resources included in the plugins. Unfortunately, there was a bug in the template (in the case of etcd) and missing logic in the case of the networking stack that prevented it from happening.
- Enable plugin cf resources for networking stack
- Fixing etcd template to add plugin cf resources
> Fixing adding cf resources to etcd and networking stack - master

- core/controlplane/config/templates/cloud-config-controller
- core/root/config/templates/cluster.yaml
- model/addons.go
- test/integration/maincluster_test.go
We've exposed the cluster-autoscaler deployment resources and made them configurable via cluster.yaml using the same approach taken regarding the kube-dashboard
We've started to experience OOM issues & CPU throttling in our bigger environments.
> Make cluster-autoscaler resource request/limit configurable

- core/controlplane/config/templates/cloud-config-controller
- core/etcd/config/templates/cloud-config-etcd
- core/nodepool/config/templates/cloud-config-worker
"set -e" will capture when a line of code fails.  However, for a
pipeline such as "false | true", it will only handle the exit code
of the last command. In this case, the exit code will always be 0.
"set -o pipefail" will ensure that any failure in the pipeline results
in the whole line failing, which will then be handled correctly by
"set -e"
For example:
$ set +o pipefail ; false | true ; echo $?
0
$ set -o pipefail ; false | true ; echo $?
1
> Capture failures in decrypting assets

- builtin/files/userdata/cloud-config-controller
kubeletOptions can be set at the cluster level, then they are injected on a file /etc/default/kubelet that is referenced on the kubelet systemd unit. Although the file gets created in the controller nodes, it is never referenced on the systemd unit. Hence kubeletOptions does not really work on Controllers.
> BUGFIX: kubeletOptions not applied on controller nodes.

- builtin/files/userdata/cloud-config-controller
- builtin/files/userdata/cloud-config-worker
- pkg/api/kubernetes.go
- pkg/api/types.go
- pkg/model/compiler.go
- pkg/model/config.go
- pkg/model/node_pool_config.go
- pkg/model/stack_new.go
- plugin/clusterextension/extras.go
- test/integration/plugin_test.go
This PR Is to allow adding specific configuration flags to the kube-proxy, kubelet and kube-scheduler through plugins, it is an extension of the currently existing functionality to add fags to the kubeapi and kube-controller-manager.
In the plugin.yaml you can add flags like follows:
Then they will be injected on the configuration of the specific components:
> Allowing adding arbitrary flags to kubernetes core components through plugins

- builtin/files/stack-templates/node-pool.json.tmpl
Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1581 introduced by https://github.com/kubernetes-incubator/kube-aws/pull/1531
Removed LaunchTemplateName from the LaunchTemplate. LaunchTemplateName must be unique pr AWS account pr region.
> Remove LaunchTemplateName from the LaunchTemplate

- builtin/files/stack-templates/node-pool.json.tmpl
Launch Templates introduced in https://github.com/kubernetes-incubator/kube-aws/pull/1531 did not enable monitoring. This PR adds detailed monitoring, so that worker nodes will behave the same way they did prior to kube-aws 0.13
> Enable detailed monitoring

- builtin/files/cluster.yaml.tmpl
- credential/generator.go
- pkg/api/cluster.go
- pkg/model/credentials.go
- test/integration/maincluster_test.go
- Adds the ability to define custom SANs to the APIServer. Internally we found this incredibly useful when trying to roll changes to CIDRs inside of the cluster.
> Custom APIServer SANs

- pkg/model/stack_new.go
- etcd subnets are not respected when generating a new etcd stack, this ensures we at least look at the declared etcd subnets and try to match them up.
Resolves #1579
> Etcd Subnets not honoured on stack render.

- builtin/files/stack-templates/control-plane.json.tmpl
- builtin/files/stack-templates/etcd.json.tmpl
- builtin/files/stack-templates/node-pool.json.tmpl
- filereader/texttemplate/texttemplate.go
- pkg/api/subnet.go
- pkg/api/subnets.go
- pkg/model/stack.go
- pkg/model/stack_new.go
- pkg/model/types.go
Subnets in the controller stack not being referenced against the network stack when being managed by kube-aws.  Map subnets back to the looked up set by name.  Various additional log messages to debug level.  Remove some helper functions on tempCtx types by calling the correct path in the stack templates.
> Issue when kube-aws manages/creates subnets

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- test/integration/maincluster_test.go
The Kiam server and agent command line flags changed in v3.0.
Although we install Kiam v3.2 by default - allow users to deploy older versions with the different command line options.
Tested deploying v2.7 and then upgrading to v3.2
> Allow setting Kiam version <3.0

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
- Allows a configurable TTL for CoreDNS.
> [v0.13.x] Configurable CoreDNS TTL

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
- Allows a configurable TTL for CoreDNS.
> [v0.14.x] Configurable CoreDNS TTL

- builtin/files/userdata/cloud-config-controller
We have found a bug in 1.13.x where mirror pods get evicted when the node is under pressure. This PR sets the priority directly so that those pods won't get evicted. We don't believe that this is required with 1.14+. 
Relates to this issue https://github.com/kubernetes/kubernetes/issues/73572
> adding in priority value in podSpec for controller, scheduler and apiserver

- builtin/files/userdata/cloud-config-worker
- Moving the `-` to the left curl braces ensures we get the formatting we want from the formatting by removing a linebreak.
Resolves #1647
> [v0.14.x] Fix trailing slash in Taint templating.

- builtin/files/userdata/cloud-config-worker
- Moving the `-` to the left curl braces ensures we get the formatting we want from the formatting by removing a linebreak.
Resolves #1647
> [v0.13.x] Fix trailing slash in Taint templating.

- builtin/files/userdata/cloud-config-worker
- Moving the `-` to the left curl braces ensures we get the formatting we want from the formatting by removing a linebreak.
Resolves #1647
> Fix trailing slash in Taint templating.

- builtin/files/userdata/cloud-config-controller
- Updates the CoreDNS service deployment to allow scraping by Prometheus.
- This matches the Kubernetes upstream CoreDNS addon deployment, shown [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/coredns/coredns.yaml.in)
> [v0.14.x] - Expose CoreDNS to Prometheus

- builtin/files/userdata/cloud-config-controller
- Updates the CoreDNS service deployment to allow scraping by Prometheus.
- This matches the Kubernetes upstream CoreDNS addon deployment, shown [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/coredns/coredns.yaml.in)
> Expose CoreDNS to Prometheus

- builtin/files/userdata/cloud-config-controller
- Updates the CoreDNS service deployment to allow scraping by Prometheus.
- This matches the Kubernetes upstream CoreDNS addon deployment, shown [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/coredns/coredns.yaml.in)
> [v0.13.x] - Expose CoreDNS to Prometheus

- core/controlplane/config/templates/cloud-config-controller
> v0.11.x: A migration helper to disable core controller services when needed

- core/controlplane/config/templates/cloud-config-controller
> v0.12.x: A migration helper to disable core controller services when needed

- builtin/files/userdata/cloud-config-controller
> master: A migration helper to disable core controller services when needed

- builtin/files/userdata/cloud-config-controller
> v0.13.x: A migration helper to disable core controller services when needed

- builtin/files/userdata/cloud-config-controller
> v0.14.x: A migration helper to disable core controller services when needed

- builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
- Fixes the formatting used by the Go Templates when creating the option set for cluster-autoscaler, with the current setup the formatting will index the text too far as shown below.
```
- --expander=least-waste
- --a=b
- --c=d
```
Bumping them a little to the right fixes the formatting.
Resolves #1653
> Fix formatting with cluster-autoscaler

- builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
- Fixes the formatting used by the Go Templates when creating the option set for cluster-autoscaler, with the current setup the formatting will index the text too far as shown below.
```
- --expander=least-waste
- --a=b
- --c=d
```
Bumping them a little to the right fixes the formatting.
Resolves #1653
> [v0.13.x] Fix formatting with cluster-autoscaler

- builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
- Fixes the formatting used by the Go Templates when creating the option set for cluster-autoscaler, with the current setup the formatting will index the text too far as shown below.
```
- --expander=least-waste
- --a=b
- --c=d
```
Bumping them a little to the right fixes the formatting.
Resolves #1653
> [v0.14.x] Fix formatting with cluster-autoscaler

- builtin/files/cluster.yaml.tmpl
- builtin/files/etcdadm/etcdadm
Change how etcd versions are specified, to resemble etcd project releases.
> Etcd version

- filereader/texttemplate/texttemplate.go
- plugin/plugincontents/template.go
add insertTemplateFile template function which allows embedding a template file within any templatable plugin object, e.g. within in stack resource: -
```
"prometheus-server-cloud-int": {
"files": {
"/var/run/coreos/cloud_config": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/cloud-config.yaml" $ | toJSON }}
}
},
"/var/run/coreos/prometheus.yaml": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/prometheus-config.yaml" $ | toJSON }}
}
},
"/var/run/coreos/nginx_config": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/nginx-config" $ | toJSON }}
}
},
"/var/run/coreos/script_exporter.yaml": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/script-exporter-config.yaml" $ | toJSON }}
}
} …
```
> v0.13.x: Plugin enhancement - allow embedding templates within templates

- filereader/texttemplate/texttemplate.go
- plugin/plugincontents/template.go
add insertTemplateFile template function which allows embedding a template file within any templatable plugin object, e.g. within in stack resource: -
```
"prometheus-server-cloud-int": {
"files": {
"/var/run/coreos/cloud_config": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/cloud-config.yaml" $ | toJSON }}
}
},
"/var/run/coreos/prometheus.yaml": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/prometheus-config.yaml" $ | toJSON }}
}
},
"/var/run/coreos/nginx_config": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/nginx-config" $ | toJSON }}
}
},
"/var/run/coreos/script_exporter.yaml": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/script-exporter-config.yaml" $ | toJSON }}
}
} …
```
> master: Plugin enhancement - allow embedding templates within templates

- filereader/texttemplate/texttemplate.go
- plugin/plugincontents/template.go
add insertTemplateFile template function which allows embedding a template file within any templatable plugin object, e.g. within in stack resource: -
```
"prometheus-server-cloud-int": {
"files": {
"/var/run/coreos/cloud_config": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/cloud-config.yaml" $ | toJSON }}
}
},
"/var/run/coreos/prometheus.yaml": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/prometheus-config.yaml" $ | toJSON }}
}
},
"/var/run/coreos/nginx_config": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/nginx-config" $ | toJSON }}
}
},
"/var/run/coreos/script_exporter.yaml": {
"content": {
"Fn::Sub": {{ insertTemplateFile "plugins/prometheus/assets/script-exporter-config.yaml" $ | toJSON }}
}
} …
```
> v0.14.x: Plugin enhancement - allow embedding templates within templates

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/networking.go
Calico-typha does not have any reserved resource so it works in a best effort mode. Since it is a 'system service' it should have some resources reserved. What do you think?
> Reserve resources for calico typha

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/networking.go
* Reserve resources for calico typha
* Parametrize typha computing resources
* Defaults typha resources in new cluster fuction
('backport' of https://github.com/kubernetes-incubator/kube-aws/pull/1607)
> v0.13.x-Reserve resources for calico typha (#1607)

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/networking.go
* Reserve resources for calico typha
* Parametrize typha computing resources
* Defaults typha resources in new cluster fuction
Backport of https://github.com/kubernetes-incubator/kube-aws/pull/1607
> v0.14.x-Reserve resources for calico typha (#1607)

- builtin/files/stack-templates/etcd.json.tmpl
The dependency on the other stack gives errors. Starting the etcd node
before the natgateway is deployed is not a big issue as it keeps
restarting its proces to fetch its data. Wait signal should be long
enough for this to be resolved.
Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1332
> Etcd cannot depend on resources in another stack

- builtin/files/stack-templates/etcd.json.tmpl
The dependency on the other stack gives errors. Starting the etcd node
before the natgateway is deployed is not a big issue as it keeps
restarting its proces to fetch its data. Wait signal should be long
enough for this to be resolved.
Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1332
See also https://github.com/kubernetes-incubator/kube-aws/pull/1667
> Cannot depend on resources in another stack

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
- Adds a preferred scheduling anti-affinity to try and target nodes in different AZs if enabled. 
Useful in situations where we have autoscaling enabled or are deploying DNS pods to nodes.
> Allow an AntiAffinty tolerant to help ensure even spread of DNS pods

- pkg/api/plugin.go
- pkg/model/stack_new.go
- plugin/clusterextension/extras.go
- plugin/plugincontents/loader.go
- plugin/plugincontents/template.go
- provisioner/remote_file.go
- provisioner/remote_file_loader.go
- test/integration/plugin_test.go
Changed Machine.SystemdUnits to inline rather than needing contents->content.
Fixed issue rendering systemd unit templates.
Fixed issue when RemoteFileSpec contains Template and not content.
Refactored extras.go to clean up repetitive code.
> v0.13.x: fixes for rendering plugin systemd units

- pkg/api/plugin.go
- pkg/model/stack_new.go
- plugin/clusterextension/extras.go
- plugin/plugincontents/loader.go
- plugin/plugincontents/template.go
- provisioner/remote_file.go
- provisioner/remote_file_loader.go
- test/integration/plugin_test.go
Systemd unit content is no longer: -
```
units:
- name: xyz
contents:
content: |
abc
```
but is now...
```
units:
- name: xyz
content: |
abc
```
This is more in-line with how files and manifests are working.
Fixed issue rendering systemd unit templates.
Fixed issue when RemoteFileSpec contains Template and not content.
Refactored extras.go to clean up repetitive code.
> master: Fixes for rendering plugin systemd units

- pkg/api/plugin.go
- pkg/model/stack_new.go
- plugin/clusterextension/extras.go
- plugin/plugincontents/loader.go
- plugin/plugincontents/template.go
- provisioner/remote_file.go
- provisioner/remote_file_loader.go
- test/integration/plugin_test.go
Changed Machine.SystemdUnits to inline rather than needing contents->content.
Fixed issue rendering systemd unit templates.
Fixed issue when RemoteFileSpec contains Template and not content.
Refactored extras.go to clean up repetitive code.
> v0.14.x: fixes for rendering plugin systemd units

- builtin/files/cluster.yaml.tmpl
- builtin/files/plugins/upgrade-helper/assets/restore-webhooks.sh
- builtin/files/plugins/upgrade-helper/assets/upgrade-helper.sh
- builtin/files/plugins/upgrade-helper/plugin.yaml
Implement a simple upgradeHelper plugin which will disable existing controllers when a new kubernetes release is being rolled out.
Save mutating and validating webhooks before install-kube-system runs and restore again afterwards.
Webhook feature can be toggled using 'disableWebhooks' boolean plugin config entry.
> v0.13.x: Plugin: upgrade-helper

- builtin/files/cluster.yaml.tmpl
- builtin/files/plugins/upgrade-helper/assets/restore-webhooks.sh
- builtin/files/plugins/upgrade-helper/assets/upgrade-helper.sh
- builtin/files/plugins/upgrade-helper/plugin.yaml
Implement a simple upgradeHelper plugin which will disable existing controllers when a new kubernetes release is being rolled out.
Save mutating and validating webhooks before install-kube-system runs and restore again afterwards.
Webhook feature can be toggled using 'disableWebhooks' boolean plugin config entry.
> master: plugin: upgrade-helper

- builtin/files/cluster.yaml.tmpl
- builtin/files/plugins/upgrade-helper/assets/restore-webhooks.sh
- builtin/files/plugins/upgrade-helper/assets/upgrade-helper.sh
- builtin/files/plugins/upgrade-helper/plugin.yaml
Implement a simple upgradeHelper plugin which will disable existing controllers when a new kubernetes release is being rolled out.
Save mutating and validating webhooks before install-kube-system runs and restore again afterwards.
Webhook feature can be toggled using 'disableWebhooks' boolean plugin config entry.
> v0.14.x: plugin: upgrade-helper

- builtin/files/userdata/cloud-config-controller
When nodes are unavailable rolling out daemonsets with only 1 allowed to be unavailable can lead
to issues where the update can get stuck.  Kube-aws DaemonSets are critical to the opertation of the
cluster and stuck roll-outs, particularly to sets like kube-proxy, can cause a world of pain.
Update all kube-aws DaemonSets to allow all instances of the DaemonSets to be updated at once.
> v0.14.x: daemonset roll out settings

- builtin/files/userdata/cloud-config-controller
When nodes are unavailable rolling out daemonsets with only 1 allowed to be unavailable can lead
to issues where the update can get stuck.  Kube-aws DaemonSets are critical to the operation of the
cluster and stuck roll-outs, particularly to sets like kube-proxy, can cause a world of pain.
Update all kube-aws DaemonSets to allow all instances of the DaemonSets to be updated at once.
> daemonset roll out settings

- core/controlplane/config/config.go
- core/controlplane/config/config_test.go
- core/controlplane/config/templates/cloud-config-controller
- core/root/config/templates/cluster.yaml
When touching the coredns configmap a cluster upgrade will overwrite the changes. This PR introduces a way to configure the changes inside the cluster config so no need to touch manually the config.
It will be ignored when other provider is specified
> Allow extra Coredns configuration

- builtin/files/userdata/cloud-config-controller
The kiam agent flags `--whitelist-route-regexp=.*` and `--gateway-timeout-creation=1s` are not supported on kiam < 3.0. So removing them from the "base" set of flags, as they are added if kiam version > 3.0 is specified in cluster.yaml.
> Remove duplicated kiam agent flags

- builtin/files/stack-templates/network.json.tmpl
- pkg/model/config.go
- pkg/model/stack_new.go
VPCRef isn't set correctly when kube-aws manages your VPC, i.e:
"VpcId": {
"Ref": "VPC"
}
Instead of:
"VpcId": {
"Fn::ImportValue": {
"Fn::Sub": "${NetworkStackName}-VPC"
}
By setting Config.VPC this will be fixed.
However, this will break configurations with existing/external VPCs.
Therefore, we added VPCRefFromNetworkStack to set this correctly as
well from the network stack.
> Fix VPCRef

- builtin/files/stack-templates/network.json.tmpl
- pkg/model/config.go
- pkg/model/stack_new.go
VPCRef isn't set correctly when kube-aws manages your VPC, i.e:
"VpcId": {
"Ref": "VPC"
}
Instead of:
"VpcId": {
"Fn::ImportValue": {
"Fn::Sub": "${NetworkStackName}-VPC"
}
By setting Config.VPC this will be fixed.
However, this will break configurations with existing/external VPCs.
Therefore, we added VPCRefFromNetworkStack to set this correctly as
well from the network stack.
> Fix VPCRef (#1668)

- build
- builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
- builtin/files/stack-templates/control-plane.json.tmpl
- builtin/files/stack-templates/node-pool.json.tmpl
- builtin/files/userdata/cloud-config-controller
- builtin/files/userdata/cloud-config-worker
Update master to deploy kubernetes v1.15.3
Deploys separate `cloud-controller-manager`
Fixes Kiam repeated command-line args
Changes taints on the masters from`node.alpha.kubernetes.io/role=master:noschedule` to `node.kubernetes.io/role=master:noschedule`
> master: Kubernetes v1.15.3

- builtin/files/userdata/cloud-config-controller
Moving the prometheus annotations from svc level to deployment level
> CoreDNS prometheus metric annotations exposed at deployment level 

- builtin/files/userdata/cloud-config-controller
Just the same as #1718 & #1720 - moving the prometheus annotations to the deployment instead of the service so they can be properly used on pods. As it is currently does not work.
> [v0.13.x] CoreDNS prometheus metric annotations exposed at deployment level

- builtin/files/userdata/cloud-config-controller
Just the same as #1719 & #1720 - moving the prometheus annotations to the deployment instead of the service so they can be properly used on pods. As it is currently does not work.
> [v0.14.x] CoreDNS prometheus metric annotations exposed at deployment level

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
- Allows CoreDNS resources to be configured through `cluster.yaml`.
> Allow CoreDNS resources to be configured

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
- Allows CoreDNS resources to be configured through `cluster.yaml`.
> [v0.13.x] Allow CoreDNS resources to be configured

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
- Allows CoreDNS resources to be configured through `cluster.yaml`.
> [v0.14.x] Allow CoreDNS resources to be configured

- builtin/files/userdata/cloud-config-controller
In a previous PR (#1722) I had attempted to stop node drainer scheduling on cordoned nodes once the timeout had elapsed (300s/5m). This is beneficial to me as otherwise nodeDrainer tries to redeploy itself onto the node after the 5 minutes have elapsed, and goes into a restart loop as kubelet is preventing things from being scheduled. When this happens our alerts go off.
This proved more difficult than planned, and I can not think of any other way to do so than placing a taint on all nodes that the daemonset does not have a toleration for. This is IMO not feasible and way too heavyweight. 
We already have drainTimeout specified [here in cluster.yml](https://github.com/kubernetes-incubator/kube-aws/blob/9fe0077b7fd08e2df7462512caf1ce4024dd4bcc/builtin/files/cluster.yaml.tmpl#L1467) so it …
> Referencing the drainTimeout value in the NodeDrainer daemonset 

- builtin/files/userdata/cloud-config-controller
In a previous PR (#1722) I had attempted to stop node drainer scheduling on cordoned nodes once the timeout had elapsed (300s/5m). This is beneficial to me as otherwise nodeDrainer tries to redeploy itself onto the node after the 5 minutes have elapsed, and goes into a restart loop as kubelet is preventing things from being scheduled. When this happens our alerts go off.
This proved more difficult than planned, and I can not think of any other way to do so than placing a taint on all nodes that the daemonset does not have a toleration for. This is IMO not feasible and way too heavyweight.
We already have drainTimeout specified here in cluster.yml so it makes sense to use this value in the drain command also. This way I can increase the timeout allowing the node to drain and terminate …
> [v0.13.x] Referencing the drainTimeout value in the NodeDrainer daemonset 

- builtin/files/userdata/cloud-config-controller
In a previous PR (#1722) I had attempted to stop node drainer scheduling on cordoned nodes once the timeout had elapsed (300s/5m). This is beneficial to me as otherwise nodeDrainer tries to redeploy itself onto the node after the 5 minutes have elapsed, and goes into a restart loop as kubelet is preventing things from being scheduled. When this happens our alerts go off.
This proved more difficult than planned, and I can not think of any other way to do so than placing a taint on all nodes that the daemonset does not have a toleration for. This is IMO not feasible and way too heavyweight.
We already have drainTimeout specified here in cluster.yml so it makes sense to use this value in the drain command also. This way I can increase the timeout allowing the node to drain and terminate …
> [v0.14.x] Referencing the drainTimeout value in the NodeDrainer daemonset 

- builtin/files/plugins/kube2iam/manifests/daemonset.yaml
After 2y running this we faced some issues with the default kube2iam resources values.
CPU limits cause applications to run up to 100% slower, in this case can end in race conditions while touching the ip tables and also in timeouts.
Default CPU requests and memory are not enough for +50 nodes.  
You can run the next query in prometheus to see if your kube2iam instances are throttling:
```
100
* sum by(container, pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{container!=""}[5m]))
/ sum by(container, pod, namespace) (increase(container_cpu_cfs_periods_total[5m]))
> 25
```
> kube2iam resources improvement

- builtin/files/cluster.yaml.tmpl
- pkg/api/cluster.go
This updates the versions of the networking components to their latest. There is actually a bug in Typha version `3.6.1` and Callico Node `3.6.1` which can end up causing service disruption if there is a problem with the Kubernetes apiserver.
If Typha is under stress it attempts to write a glog message to a mounted tmp dir, or at least that’s the expected behaviour of release 3.6.1 (https://github.com/projectcalico/typha/releases/tag/v3.6.1).
However, if that tmp dir does not exist (it does not in kube-aws) then Typha bombs out ( https://github.com/projectcalico/typha/issues/196) and causes network connectivity to drop.
> Networking Version Updates

- builtin/files/cluster.yaml.tmpl
- pkg/api/cluster.go
This updates the versions of the networking components to their latest. There is actually a bug in Typha version `3.6.1` and Callico Node `3.6.1` which can end up causing service disruption if there is a problem with the Kubernetes apiserver.
If Typha is under stress it attempts to write a glog message to a mounted `tmp` dir, or at least that’s the expected behaviour of release 3.6.1.
However, if that `tmp` dir does not exist (it does not in kube-aws) then Typha bombs out ( https://github.com/projectcalico/typha/issues/196) and causes network connectivity to drop.
- Bumps patch version of networking components from `.1` to `.3` so fix for `tmp` dir issue is resolved.
> [0.13.x] Networking Version Updates

- builtin/files/cluster.yaml.tmpl
- pkg/api/cluster.go
This updates the versions of the networking components to their latest. There is actually a bug in Typha version `3.6.1` and Callico Node `3.6.1` which can end up causing service disruption if there is a problem with the Kubernetes apiserver.
If Typha is under stress it attempts to write a glog message to a mounted `tmp` dir, or at least that’s the expected behaviour of release 3.6.1.
However, if that `tmp` dir does not exist (it does not in kube-aws) then Typha bombs out ( https://github.com/projectcalico/typha/issues/196) and causes network connectivity to drop.
- Bumps patch version of networking components from `.1` to `.3` so fix for `tmp` dir issue is resolved.
> [0.14.x] Networking Version Updates

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/kubernetes.go
- Allows resource configuration for pod deployment.
- Allows configuration for `targetRamMb` to limit size of watch cache.
> Allow resource configuration for APIServer

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/kubernetes.go
- Allows resource configuration for pod deployment.
- Allows configuration for `targetRamMb` to limit size of watch cache.
> [v0.14.x] Allow resource configuration for APIServer

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/kubernetes.go
- Allows resource configuration for pod deployment.
- Allows configuration for `targetRamMb` to limit size of watch cache.
> [v0.13.x] Allow resource configuration for APIServer

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- core/root/cluster.go
- pkg/api/cluster.go
- pkg/api/node_volume_mount_test.go
- pkg/api/types.go
- pkg/model/cluster_test.go
When touching the coredns configmap a cluster upgrade will overwrite the changes. This PR introduces a way to configure the changes inside the cluster config so no need to touch manually the config
Also realigned with gofmt
> [v0.13.x]Allow extra Coredns configuration

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- core/root/cluster.go
- pkg/api/cluster.go
- pkg/api/node_volume_mount_test.go
- pkg/api/types.go
- pkg/model/cluster_test.go
When touching the coredns configmap a cluster upgrade will overwrite the changes. This PR introduces a way to configure the changes inside the cluster config so no need to touch manually the config
Also realigned with gofmt
> [v0.14.x] Allow extra Coredns configuration

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- core/root/cluster.go
- pkg/api/cluster.go
- pkg/api/node_volume_mount_test.go
- pkg/api/types.go
- pkg/model/cluster_test.go
When touching the coredns configmap a cluster upgrade will overwrite the changes. This PR introduces a way to configure the changes inside the cluster config so no need to touch manually the config
Also realigned with gofmt
> [Master] Allow extra Coredns configuration

- builtin/files/stack-templates/control-plane.json.tmpl
- builtin/files/stack-templates/etcd.json.tmpl
- builtin/files/stack-templates/root.json.tmpl
- core/root/template_params.go
- pkg/model/etcd_node.go
… this prevents us from ever removing or changing these values.  The best practice is to pass variables as parameters between nested stacks (via the root stack) but we currently pass knowledge of the etcd FQDNs via CF cross-stack references.   This prevents us from removing or changing their values.
This PR breaks the cross-stack reference and passes the FQDN as a parameter instead, and allows us to change the FQDNs in the future (e.g. to spin up new etcd clusters in etcd major version upgrades)
> v0.14.x: Remove the control-plane stacks dependence on cross stack references

- pki/x509.go
In the recent versions of golang, etcd and kubernetes etc. the cert key usages are more strictly observed, e.g. an ectd server may not connect to another etcd server using a cert with only TLS Server Authentication - it also needs the Client Authentication usage.
> v0.13.x: Allow server certs to also be used for client authentication

- builtin/files/userdata/cloud-config-controller
These annotations would previously never be rendered because they
were added under the kube-dns section (rather than CoreDNS's).
Additionally, the annotations are now added to the Pods themselves
rather than the Deployment.
Fixes #1768
> master: CoreDNS prometheus metric annotations exposed at pod level

- builtin/files/userdata/cloud-config-controller
These annotations would previously never be rendered because they
were added under the kube-dns section (rather than CoreDNS's).
Additionally, the annotations are now added to the Pods themselves
rather than the Deployment.
Fixes #1768
> v0.13.x: CoreDNS prometheus metric annotations exposed at pod level

- builtin/files/userdata/cloud-config-controller
These annotations would previously never be rendered because they
were added under the kube-dns section (rather than CoreDNS's).
Additionally, the annotations are now added to the Pods themselves
rather than the Deployment.
Fixes #1768
> v0.14.x: CoreDNS prometheus metric annotations exposed at pod level

- builtin/files/userdata/cloud-config-controller
Calico experiencing issues post version upgrade due to missing new crd object and RBAC permission
> Add missing calico networkset crd and rbac permission

- build
- builtin/files/etcdadm/etcdadm
- builtin/files/plugins/dashboard/manifests/deployment.yaml
- builtin/files/stack-templates/etcd.json.tmpl
- builtin/files/userdata/cloud-config-etcd
- pkg/api/etcd.go
- pkg/api/etcd_cluster.go
- pkg/model/context.go
- pkg/model/etcd_cluster.go
- pkg/model/etcd_node.go
- test/integration/aws_test.go
- test/integration/maincluster_test.go
Safer major etcd upgrades by spinning up new etcds and performing a migration (copy of all kubernetes data)
Similar to the approach used during the stack migration but this time the major/minor version of etcd is used to control migration e.g 3.2.x -> 3.3.x will cause a migration and the migration is handled within the same etcd stack.  It is safer because should the CF roll fail the previous etcd's should still be available to roll-back to.  It works by embedding the version into the etcd cloudformation logical names so that version upgrades generates a new set of etcds, e.g.
```
+00:00:58	CREATE_IN_PROGRESS      		Etcdv3dot3i2ENI
+00:00:58	CREATE_IN_PROGRESS      		Etcdv3dot3i2LC
+00:00:58	CREATE_IN_PROGRESS      		Etcdv3dot3i0LC
+00:00:58	CREATE_IN_PROGRESS      		Etcdv3dot3i1LC …
```
> Allow major Etcd upgrades with safe roll-back

- core/controlplane/config/templates/cloud-config-controller
For cluster of +50 nodes kube2iam is throttling all the time with current limits. This one add some more margin and also remove the cpu limits what cause a performance issue
> Kube2iam resources adjustment

- contrib/dex/README.md
- docs/advanced-topics/use-an-existing-vpc.md
- docs/getting-started/step-2-render.md
- docs/getting-started/step-5-add-node-pool.md
- e2e/README.md
Fix several broken links:
- https://github.com/nginxinc/kubernetes-ingress/tree/master/nginx-controller moved to >> https://github.com/nginxinc/kubernetes-ingress/tree/master/cmd/nginx-ingress , see https://github.com/nginxinc/kubernetes-ingress/pull/357
- https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cluster.yaml moved to >> https://github.com/kubernetes-incubator/kube-aws/blob/master/builtin/files/cluster.yaml.tmpl, see 
https://github.com/kubernetes-incubator/kube-aws/pull/1490
- http://kubernetes.io/docs/admin/multiple-zones/ moved to >> https://kubernetes.io/docs/setup/best-practices/multiple-zones/, see https://github.com/kubernetes/website/pull/9140 and https://github.com/kubernetes/website/pull/14826
- …
> fix broken links

- builtin/files/stack-templates/node-pool.json.tmpl
cherry-picking Pull Request: https://github.com/kubernetes-incubator/kube-aws/pull/1799
***
The Pod of `kube-node-drainer-asg-status-updater` outputs the following error.
```
$ kubectl logs kube-node-drainer-asg-status-updater-b88545d8f-79c8h -n kube-system
+ updated_instances_to_drain=
+ [  ==  ]
+ continue
+ sleep 10
+ asg describe-auto-scaling-groups
+ aws --region=ap-northeast-1 autoscaling describe-auto-scaling-groups
+ jq -r [.AutoScalingGroups[] | select((.Tags[].Key | contains("kube-aws:")) and (.Tags[].Key | contains("kubernetes.io/cluster/cluster-name"))) | .Instances[] | select(.LifecycleState == "Terminating:Wait") | .InstanceId] | sort | join(",")
An error occurred (AccessDenied) when calling the DescribeAutoScalingGroups operation: User: …
```
> Add autoscaling:DescribeAutoScalingGroups policy for node drainer.

- core/controlplane/config/templates/cloud-config-controller
With this fix, in our company we close the 0.12 branch. So next PRs will go to ^0.13
> [0.12.x Only] Fix ExtraCoreDNSConfig typo in stack template

- builtin/files/userdata/cloud-config-controller
When using more than one line of extra config, the indentation was not right and generated YAML was not valid
This should fix this issue
> Add proper indentation to extra CoreDNS config

- .travis.yml
Bump travis build config to use latest golang.
We have already shipped this in Homebrew  v0.14.3 (https://github.com/Homebrew/homebrew-core/pull/47394)
> Bump golang version to v1.13.5

- build
- builtin/files/plugins/aws-iam-authenticator/manifests/daemonset.yaml
- builtin/files/plugins/cluster-autoscaler/manifests/deployment.yaml
- builtin/files/plugins/dashboard/manifests/deployment.yaml
- builtin/files/plugins/kiam/manifests/agent-daemonset.yaml
- builtin/files/plugins/kiam/manifests/server-daemonset.yaml
- builtin/files/plugins/kube2iam/manifests/daemonset.yaml
- builtin/files/userdata/cloud-config-controller
- builtin/files/userdata/cloud-config-worker
- contrib/dex/dex.de.yaml
- contrib/dex/ingress/dex.nginx.ing.yaml
- pkg/api/cluster.go
- pkg/api/plugin.go
ETCD_VERSION="v3.4.3"
KUBERNETES_VERSION="v1.16.4"
Decommission old v1beta1 apis
Add selectors to all DaemonSets and Deployments
Kubelet moves into a Docker container (issues with rkt fly container)
Calico bumped to version 3.11.1
> Kubernetes 1.16 Support

- builtin/files/cluster.yaml.tmpl
This changes cluster.yaml initial skeleton to avoid the use of (not available) Config struct
> Fix for #1823

- builtin/files/cluster.yaml.tmpl
This changes cluster.yaml initial skeleton to avoid the use of (not available) Config struct
> template: use of InitialConfig to build cluster.yaml

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-etcd
- pkg/api/cluster.go
- pkg/api/types.go
When provisioning ETCDs with EBS volumes and provisioned IOPS
the default check will wait for a full monitorization of the EBS
volume. This actually checks two things, io-enabled and io-performance
(See
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-volume-status.html)
The io-performance checks that the EBS volume is actually able to deliver
the provisioned IOPS. Since it is based on cloudwatch it is very slow
and usually takes more than 5m to be passed. The other check, io-enabled, is usually quite fast.
Since I have to constantly create and destroy clusters (sometimes with 3
or more ETCD nodes) I can save more than 15m per cluster skiping the io-performance verification and trusting io-enabled.
> Added an option to Skip IOPS verification in ETCD

- pkg/api/cluster.go
Seems that typha resources is lacking an "m" for refer to milicores.
In a normal cluster (without >250 cores per node) you get an error when
trying to create typha pods:
```
message: 'pods "calico-typha-857fd4bc7d-62jq6" is forbidden: maximum cpu usage
per Container is 1, but limit is 250'
```
> incorrect typha resources

- build
- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- builtin/files/userdata/cloud-config-worker
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/node_pool_compile.go
- pkg/model/node_pool_config.go
- test/integration/maincluster_test.go
Fix issues caused by the v0.15.x release and the cloud-controller-manager breaking physical volume support.  This feature wasn't tested sufficiently and wasn't ready for release, apologies!  This PR makes it an experimental feature which is `disabled` by default.
I've added CSI provisioning for EBS volumes as another experimental feature so that the cloud-controller-manager and CSI can be tested together for the potential replacement of the in-tree drivers in the future (1.21 has been mooted for the removal of the in-tree drivers).  Again, this is disabled by default and should only be used by the brave.  My testing shows that it works but the migration of existing PVs is not working for me.
> v0.15.x branch: Make cloud-controller-manager an experimental feature

- builtin/files/userdata/cloud-config-controller
Adds back in `--configure-cloud-routes=false` on the `cloud-controller-manager`.
See #1833
> Added back in --configure-cloud-routes=false

- build
- builtin/files/cluster.yaml.tmpl
- builtin/files/etcdadm/etcdadm
- builtin/files/userdata/cloud-config-controller
- builtin/files/userdata/cloud-config-worker
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/node_pool_compile.go
- pkg/model/node_pool_config.go
- test/integration/maincluster_test.go
Allow cloud-controller-manager and CSI in master branch for further testing.
Both are disabled by default.  We need to test these in readiness for when EBS volume provisioning will be removed from the kube-controller-manager in-tree drivers.
By adding CSI we can provision EBS volumes without the in-tree drivers.
Both cloud-controller-manager and CSI are working in new clusters but the migration code is problematic and can get stuck detaching a volume from a removed non-csi node...
```
E0217 22:32:13.112266       1 reconciler.go:238] attacherDetacher.DetachVolume failed to start for volume "pvc-5b937379-4cf4-4cb9-877d-c978ca30626f" (UniqueName: "kubernetes.io/aws-ebs/aws://eu-west-2a/vol-05515c17b1d470bdd") on node "ip-172-31-30-191.eu-west-2.compute.internal" : …
```
> cloud-controller-manager/CSI - experimental features

- builtin/files/plugins/cluster-autoscaler/plugin.yaml
- builtin/files/stack-templates/root.json.tmpl
Having these values as "true" causes stack drift, as we later update them to be "owned". In order to ensure we don't needlessly roll pools we should update the CloudFormation so that "owned" is the expected value.
> [v0.14.5] Ensure kubernetes.io/cluster/X tags are "owned".

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/types.go
The port name grpclb breaks installations of Isito, as kiam-server is running on 443, this causes all external SSL traffic to blackhole.
> [v0.14.5] Allow custom port name for kiam server

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/kubernetes.go
- pkg/api/types.go
- Allows us to enable `--horizontal-pod-autoscaler-use-rest-clients` without requiring us to use the metrics-server addon.
> [v0.14.x] Allow use of PodAutoscalerUseRestClient without addon metrics-server.

- builtin/files/userdata/cloud-config-controller
- This explicitly enables the default admission controllers expected in Kubernetes 1.14.x
> [v0.14.x] Add default v1.14.x Kubernetes admission controllers.

- builtin/files/userdata/cloud-config-controller
This takes the canal configuration from kops, and moves installation into a initContainer as oppose to trying to run both the installation and canal containers side-by-side.
> [v0.14.x] Improve Canal Configuration

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/networking.go
We had an issue in a big cluster (around 200 nodes) when rolling upgrade a change and replacing instances we ran out of subnet leases, that causes that new workers were unable to get a flannel lease and hence setting up the network  and were killed due to not sending the cfn-signal in time.
This patch aims to make subnetLen configurable for big clusters, using kube-aws default flannel config the maximum is 255 nodes which means around 127 nodes and a rolling upgrade that replaces all instances (like updating the base AMI).
In the case of being unset, flanneld will keep using the default which is /24 per node.
> make flannel subnetLen configurable for big clusters

- cmd/render.go
> Fix ApiServerAggregatorKeyPath unnamed flag

- builtin/files/userdata/cloud-config-controller
I was creating a cluster from latest and it seems that flannel expects an int
> bugfix: flannel SubnetLen expects an int not an string

- builtin/files/cluster.yaml.tmpl
- builtin/files/stack-templates/control-plane.json.tmpl
- builtin/files/stack-templates/network.json.tmpl
- pkg/api/cluster.go
Currently kube-aws includes a rule in its security group to allow ping from all traffic (0.0.0.0/0). Unless this is necessary for a reason I have not foreseen, it is an inherent security risk, violates CIS compliance, and is probably superfluous if SG's are managed appropriately.
Therefore, I have created a switch in cluster.yaml to allow removal of this rule. I have left it enabled by default but am conscious that anyone upgrading needs to ensure this is in their cluster.yaml, so am happy to adjust the logic so that there's no impact unless you explicitly ask for it to be disabled. 
I don't think I've missed any other spots where this rule is used.
> [v0.16.0] Creating a switch to disable ICMP Ping instead of the default allow 0.0.0/0

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- This PR explicitly lists the admission controllers enabled by default as described [here]https://v1-16.docs.kubernetes.io/docs/reference/access-authn-authz/admission-controllers/).
- We also remove the `Initializer` admission controller, it hasn't existed since Kubernetes v1.10.x.
> [v0.16.0] Default Admission Controllers

- builtin/files/plugins/cluster-autoscaler/plugin.yaml
- builtin/files/stack-templates/root.json.tmpl
Having these values as "true" causes stack drift, as we later update them to be "owned". In order to ensure we don't needlessly roll pools we should update the CloudFormation so that "owned" is the expected value.
> [v0.16.0] Switch kubernetes.io/cluster/X tag value to "owned".

- builtin/files/cluster.yaml.tmpl
- builtin/files/plugins/dashboard/manifests/deployment.yaml
- builtin/files/plugins/kiam/manifests/service.yaml
- builtin/files/plugins/kiam/plugin.yaml
- builtin/files/userdata/cloud-config-controller
The port name grpclb breaks installations of Isito, as kiam-server is running on 443, this causes all external SSL traffic to blackhole.
> [v0.16.0] Allow custom port name for kiam

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/kubernetes.go
- pkg/api/types.go
- pkg/model/cluster_test.go
- Allows us to enable `--horizontal-pod-autoscaler-use-rest-clients` without requiring us to use the metrics-server addon.
> [v0.16.0] Allow use of PodAutoscalerUseRestClient without addon metrics-server.

- builtin/files/userdata/cloud-config-controller
This takes the canal configuration from kops, and moves installation into a initContainer as oppose to trying to run both the installation and canal containers side-by-side.
> [v0.16.0] Improve Canal Configuration

- pkg/api/assets.go
- pkg/api/region.go
Path based access has been deprecated and now returns a redirect error to bucketname.s3.amazonaws.com
as explained in this post:
https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/
This makes cloudformation to fail as it refers to the now redirected s3
bucket path, and raises the message:
S3 error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. For more information check http://docs.aws.amazon.com/AmazonS3/la
There is no strong documentation about what are the updates in China and
Gov regions, consider it follows the same logic.
> Migrate to new s3 URL method

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
The existing `kubeDns.autoscaler.extraCoreDNSConfig`  allows the user to
inject additional values into the coredns configmap's root zone (".").
This commit allows the user to additionally specify a string to
`kubeDns.autoscaler.additionalZoneCoreDNSConfig` which will be injected
into the configmap after the root zone to allow the user to specify
configuration for additional zones. As an example, this might be used
to forward traffic for the .global zone to the istiocoredns service.
> Allow injection of CoreDNS configuration for non-root zones

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
This PR adds proper indentation to the additional zone CoreDNS change introduced with https://github.com/kubernetes-incubator/kube-aws/pull/1875.
> Add proper indentation to additional zone CoreDNS config

- .travis.yml
- builtin/files/cluster.yaml.tmpl
- builtin/files/stack-templates/network.json.tmpl
- builtin/files/userdata/cloud-config-controller
- builtin/files/userdata/cloud-config-worker
- make/test
- pkg/api/assets.go
- pkg/api/cluster.go
- pkg/api/networking.go
- pkg/api/region.go
- Canal is EOL, and the only other option we offered was AWS CNI. This borrows (steals) the Calico configuration for kops, and dumps it into kube-aws so that we can use that as an option too.
- This PR also fixes node labelling issues that changed between v1.15.x and v1.16.x, as we can no longer use `kubelet` to self label `kubernetes.io` tags, making nodes difficult to differentiate.
- This PR also removes quay.io as the core provider for calico networking images because they keep falling over.
- This PR also opens ports 4789 to allow for vxlan networking between ports, and opens communication between workers & controllers for IPnIP tunnelling used by Calico's BGP (also requiring port 179) setup.
> [v0.16.x] Setup Calico Networking Option

- builtin/files/userdata/cloud-config-controller
* With WS stripping character in place configs would be malformed, ie
* `--volume opt-bin,kind=host,source=/opt/bin \--mount volume=var-log,target=/var/log \`
* This code has been refactored in 0.16.x and master. As far as I'm aware, this is the only branch with this bug.
* Now there's an extra newline, but this function is only called once  and the the sh environment formatting is more forgiving, ie
```sh
--volume opt-bin,kind=host,source=/opt/bin \
--mount volume=var-log,target=/var/log \
```
> Keep newline, so apiserver starts

- builtin/files/plugins/aws-iam-authenticator/files/authentication-token-webhook-config.yaml
- builtin/files/plugins/aws-iam-authenticator/files/controller-kubeconfig.yaml
- builtin/files/plugins/aws-iam-authenticator/files/worker-kubeconfig.yaml
- builtin/files/plugins/aws-iam-authenticator/manifests/aws-auth-cm.yaml
- builtin/files/plugins/aws-iam-authenticator/manifests/clusterrole.yaml
- builtin/files/plugins/aws-iam-authenticator/manifests/clusterrolebinding.yaml
- builtin/files/plugins/aws-iam-authenticator/manifests/daemonset.yaml
- builtin/files/plugins/aws-iam-authenticator/manifests/serviceaccount.yaml
- builtin/files/plugins/aws-iam-authenticator/plugin.yaml
- builtin/files/stack-templates/control-plane.json.tmpl
- docs/getting-started/step-6-configure-add-ons.md
- pkg/api/cluster.go
* Fix bug in stack-template for controller, around `OpenICMP` and ssh security groups
* Upgrade to aws-iam-authenticator 0.5.1
* Resolve issue introduced in 941fd29, where the context cluster name didn't match
* Fix formatting issue with controller and worker kubeconfig files
* Add clusterrole, binding, and service account
* Allow aws-iam-auth to be scheduled on k8s 1.15 and 1.16
* I have successfully created a new stack, on master
* I have not tested this on v0.16.x
* I have successfully created a new stack, on v0.15.x
* This can be safely merged into v0.15.x after #1874 and #1886
AWS authenticator expects IAM roles for controllers and workers already exist. As it is currently configured, the aws-iam-authenticator must be enabled *after* the initial `kube-aws apply`. This is because the …
> Upgrade aws auth, fix CF template bug

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
The existing `kubeDns.extraCoreDNSConfig`  allows the user to
inject additional values into the coredns configmap's root zone (".").
This commit allows the user to additionally specify a string to
`kubeDns.additionalZoneCoreDNSConfig` which will be injected
into the configmap after the root zone to allow the user to specify
configuration for additional zones. As an example, this might be used
to forward traffic for the .global zone to the istiocoredns service.
> [v0.15.x] Allow injection of CoreDNS configuration for non-root zones

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
The existing `kubeDns.extraCoreDNSConfig`  allows the user to
inject additional values into the coredns configmap's root zone (".").
This commit allows the user to additionally specify a string to
`kubeDns.additionalZoneCoreDNSConfig` which will be injected
into the configmap after the root zone to allow the user to specify
configuration for additional zones. As an example, this might be used
to forward traffic for the .global zone to the istiocoredns service.
> [v0.16.x] Allow injection of CoreDNS configuration for non-root zones

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
This commit allows the user to specify that dnsmasq should be backed by a pod-local copy of CoreDNS rather than relying on the global CoreDNS service. If enabled, the dnsmasq-node DaemonSet will be configured to use a local copy of CoreDNS for its resolution while setting the global CoreDNS service as a fallback. This is handy in situations where the number of DNS requests within a cluster grows large and causes resolution issues as dnsmasq reaches out to the global CoreDNS service.
Additionally, several values passed to dnsmasq are now configurable, including its `--cache-size` and `--dns-forward-max`.
See [this postmortem](https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/docs/postmortems/jan-2019-dns-outage.md) for an investigation into this situation which was …
> [v0.14.x] Allow dnsmasq to be backed by a local copy of CoreDNS

- builtin/files/userdata/cloud-config-controller
When in large clusters memory allocation can be a challenge if `memory limit != memory requests`. Because of that we've some internal requirements for the platform and we're committing to be more aggressive and taking this very seriously in our platform.
We've some tooling around this in prometheus and as part of our memory allocation cleanup process we've found kube-dns-autoscaler consuming 250% times the requested memory. As we've this alert in our side, this component will trigger an alert: 
```
(
avg(
container_memory_usage_bytes{
container!="POD",
image!="",
}
) by (container, namespace) 
* 100
) / max(
kube_pod_container_resource_requests_memory_bytes{
job="kube-state-metrics",
}
) by (container, namespace) > 90
```
I've increased the memory request up to 50Mi and added a proper …
> [v0.17.x] Increase DNS autosacaler memory and add memory limit

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
This commit allows the user to specify that dnsmasq should be
backed by a pod-local copy of CoreDNS rather than relying on
the global CoreDNS service. If enabled, the dnsmasq-node
DaemonSet will be configured to use a local copy of CoreDN
for its resolution while setting the global CoreDNS service as
a fallback. This is handy in situations where the number of DNS
requests within a cluster grows large and causes resolution issues
as dnsmasq reaches out to the global CoreDNS service.
Additionally, several values passed to dnsmasq are now configurable
including its `--cache-size` and `--dns-forward-max`.
See [this postmortem](https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/docs/postmortems/jan-2019-dns-outage.md)
for an investigation into this situation which was instrumental …
> [v0.17.x] Allow dnsmasq to be backed by a local copy of CoreDNS

- pkg/model/etcd_cluster.go
- pkg/model/etcd_cluster_test.go
The AWS Cloud Controller does not support private zones, so if you use it with etcd >=v2.4..5 then you will run into issues with cluster initialization, because of a feature introduced the does a reverse dns look up to ensure the IP making requests matches a host on the certificate SANs.
Worse, even if you add all reverse zones so that this *does* work with your private zone, the aws controller _does not_ name nodes after your private zone, and they instead come up using .compute.internal nodeNames. This causes problem elsewhere in the kube-aws stack where we try to update nodes using hostname, but in this scenario hostname != nodename. (*.myprivate.zone vs *...compute.internal). 
This is a hack that allowed us to move forward, but a better implementation is needed & should be revisited.
> [v0.16.x] Fix etcd certificates when using private zones

- builtin/files/userdata/cloud-config-controller
The dnsmasq-node ServiceAccount must exist whether or not CoreDNS-local
has been enabled. Therefore, it is created alongside the DaemonSet rather
than as part of the coredns-local manifest.
Additionally, always create dnsmasq-node-coredns-local.yaml. If this file
does not exist (as would be the case if the CoreDNS local feature has
not been enabled), controller nodes will fail to come up with the error:
> error: the path "/srv/kubernetes/manifests/dnsmasq-node-coredns-local.yaml" does not exist
This is caused when `kubectl delete` is called against the file because
of the line `remove "${mfdir}/dnsmasq-node-coredns-local.yaml`.
This manifest must always be generated because the CoreDNS-local
feature cannot be enabled and then later disabled without otherwise
requiring manual operator …
> [v0.17.x] Always create required dnsmasq resources

- builtin/files/userdata/cloud-config-controller
If this file does not exist (as would be the case if the CoreDNS local
feature has not been enabled), controller nodes will fail to come up
with the error:
> error: the path "/srv/kubernetes/manifests/dnsmasq-node-coredns-local.yaml" does not exist
This is caused when `kubectl delete` is called against the file because
of the line `remove "${mfdir}/dnsmasq-node-coredns-local.yaml`.
This manifest must always be generated because the CoreDNS-local
feature cannot be enabled and then later disabled without otherwise
requiring manual operator intervention.
---
Additionally, a previous change added a serviceaccount reference to the
dnsmasq-node daemonset; this PR updates the cloud-config-controller
template to create this SA alongside the daemonset.
> [v0.14.x] Always create dnsmasq-node-coredns-local.yaml

- builtin/files/userdata/cloud-config-controller
- builtin/files/userdata/cloud-config-worker
- make/test
- New restrictions on the kubelets ability to label nodes means that we can no longer label worker nodes, from the worker nodes. Instead, we need to apply a temporary label & then have the masters properly label the nodes.
> [v0.16.x] Fix node name labelling in v0.16.x clusters.

- builtin/files/cluster.yaml.tmpl
- builtin/files/userdata/cloud-config-controller
- pkg/api/cluster.go
- pkg/api/types.go
- pkg/model/cluster_test.go
This commit allows the user to specify that dnsmasq should be
backed by a pod-local copy of CoreDNS rather than relying on
the global CoreDNS service. If enabled, the dnsmasq-node
DaemonSet will be configured to use a local copy of CoreDN
for its resolution while setting the global CoreDNS service as
a fallback. This is handy in situations where the number of DNS
requests within a cluster grows large and causes resolution issues
as dnsmasq reaches out to the global CoreDNS service.
Additionally, several values passed to dnsmasq are now configurable
including its `--cache-size` and `--dns-forward-max`.
See [this postmortem](https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/docs/postmortems/jan-2019-dns-outage.md)
for an investigation into this situation which was instrumental …
> [v0.16.x] Allow dnsmasq to be backed by a local copy of CoreDNS

- builtin/files/userdata/cloud-config-controller
Depending on the options combination you use, the controller
template may generate the kubelet.service unit with extra
white lines that break the format hence making it to fail.
I have hacked an example in playground comparing the previous
combination of - for trimming whitespaces and the new one
https://play.golang.org/p/OO5T7TZA1qR
> Fix trailing whitespaces in template
