config/templates/cloud-config-controller
config/templates/cloud-config-worker

Also see https://github.com/coreos/coreos-kubernetes/issues/744

Use hosts' DNS resolvers instead of Google

---

config/config_test.go

fix(test): rkt+stable is supported now

---

.gitignore
.travis.yml
Makefile
test

repo: Enable Codecov integration

---

Documentation/kubernetes-on-aws.md
README.md
containerized-build-release-binaries

[docs] change github repo uri references

---

config/templates/cloud-config-controller
config/templates/cloud-config-worker
e2e/kubernetes/Makefile
e2e/run

Fix instability while starting kubelet on worker/controller nodes

---

config/templates/cloud-config-controller
config/templates/cloud-config-worker

See upstream https://github.com/kubernetes/kubernetes/pull/29999

Use non-deprecated parameter for pod manifests.

---

config/templates/cloud-config-controller
config/templates/cloud-config-worker

fix: Persist /var/lib/cni between kubelet restarts

---

README.md

docs(README): Clarify signed release details

---

config/templates/cloud-config-controller
config/templates/cloud-config-worker

fix #65
The details and test results can be seen in comments in #65

fix: flanneld startup slowness

---

config/config.go
config/templates/cluster.yaml
contrib/bump-version
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile

Bump Kubernetes version to v1.4.6+coreos.0

---

config/templates/cloud-config-controller
config/templates/cloud-config-worker

Make decrypt-tls-assets faster by consolidating multiple `rkt run`s into one shot

---

config/templates/cloud-config-controller

Not the cleanest but it's better than restarting multiple times per second :laughing:
Fixes #85

Wait 10 seconds between install-kube-system restarts

---

cfnstack/cfnstack.go
cfnstack/provisioner.go
cluster/cluster.go
cluster/cluster_test.go

for the preparation to reuse it in the upcoming node pools feature

refactoring: Extract CloudFormation stack provisioning into its own package

---

config/config.go
config/templates/cloud-config-controller
config/templates/cluster.yaml

This flag enable the authorization rbac plugin.
http://kubernetes.io/docs/admin/authorization/

Add experimental feature to enable rbac authorization plugin

---

nodepool/config/templates/cluster.yaml

So explain the fact in the very beginning of cluster.yaml for node pools according to what we've discussed in https://github.com/coreos/kube-aws/issues/46#issuecomment-265106641
ref #46

Node Pool is still an experimental feature

---

nodepool/config/templates/stack-template.json

Name the node pool subnets after the node pool

---

config/config.go
config/config_test.go
config/templates/cluster.yaml
config/templates/stack-template.json
test/integration/aws_test.go

fix: Support EBS volumes other than standard magnetic disks for controller and etcd nodes

---

test/helper/helper.go

Stop polluting git workspace with temporary files created while running unit tests

---

config/config.go
config/templates/cloud-config-worker
e2e/run
nodepool/config/config.go

Fix consistent failures in cfn-signal.service and set-aws-environment.service

---

config/config.go
config/templates/cloud-config-controller
config/templates/cluster.yaml
contrib/bump-version
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile
e2e/kubernetes/README.md
e2e/kubernetes/conformance.sh

Kubernetes v1.5.1

---

Documentation/kubernetes-on-aws-node-pool.md

Typo: AZ for second pool should be us-west-1b

---

config/templates/cloud-config-controller
e2e/run

DNS horizontal autoscaling

---

config/config.go
nodepool/config/config_test.go

Add missing validations for a node pool powered by Spot Fleet

---

Documentation/kubernetes-on-aws-render.md

See http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html#vpc-dns-hostnames

Fix the SAN for non-us-east-1 AWS regions

---

Documentation/kubernetes-on-aws-render.md

Fix broken links referenced in #203

Docs kubernetes on aws render

---

Documentation/kubernetes-on-aws-render.md
README.md

Fixes https://github.com/coreos/kube-aws/issues/206

document different account may have different supported AZs and solutions

---

config/templates/cloud-config-controller

Release Notes: https://github.com/kubernetes/dashboard/releases/tag/v1.5.1

Update the kubernetes-dashboard to 1.5.1

---

config/templates/cluster.yaml

to controller.loadBalancer.private

Make it clear in cluster.yaml that controllerLoadBalancerPrivate flag is renamed

---

config/config.go
model/nat_gateway.go
model/subnet.go
test/integration/maincluster_test.go

Fix the bug which was causing a private subnet to have no route to an existing nat gateway

---

config/templates/cloud-config-controller

Calico 2.0.1 was released with some bug fixes, more details here:
http://docs.projectcalico.org/v2.0/releases/

Updating Calico images to Calico 2.0.2

---

core/controlplane/config/templates/cloud-config-controller

Allow cluster services to talk with apiserver with minimal rbac policies
Fix #230

Minimal RBAC policies

---

cfnstack/cfnstack.go
cfnstack/provisioner.go
cmd/calculator.go
core/root/cluster.go

I'm introducing a command to calculate the cost of the cluster. Just edit your cluster.yaml and run ```kube-aws calculator```.
```
$ ./bin/kube-aws
Manage Kubernetes clusters on AWS
....
calculator  Discovery the monthly cost of your cluster  
....
```
```
$ ./bin/kube-aws calculator
Open the link http://calculator.s3.amazonaws.com/calc5.html?key=cloudformation/2174c0-f007-4360-a9ba-ec49fe66 in your browser to verify your cluster cost
```
I'll wait few days for community feedback, before merging.
ps. Also, I fixed a warning when kms is enable

Calculate my costs

---

cfnstack/provisioner.go

Fix typo in provisioner.go

---

core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml
core/nodepool/config/config.go
core/nodepool/config/templates/stack-template.json
e2e/run
e2e/testinfra/stack-template.yaml
test/integration/maincluster_test.go
test/integration/nodepool_test.go

Adding support for assign workers to Application LoadBalancer Target Group

Add support for ALBs Target Groups

---

cmd/status.go
core/controlplane/cluster/cluster.go
core/controlplane/cluster/describer.go
core/controlplane/cluster/info.go
core/root/cluster.go
core/root/describer.go
core/root/options.go
e2e/run
test/integration/maincluster_test.go

Fix missing Name and ControllerHost in `status` and `up` commands

---

cfnstack/assets.go
cfnstack/provisioner.go
cfnstack/s3_uri.go
core/controlplane/cluster/cluster.go
core/nodepool/cluster/cluster.go
core/root/cluster.go
core/root/template_params.go
test/integration/aws_test.go
test/integration/maincluster_test.go

Fix the inconsistent S3 object prefix issue

---

core/controlplane/config/templates/cluster.yaml
model/node_pool_config.go
test/integration/maincluster_test.go

Fix customSettings unavailability for node pools

---

ROADMAP.md

Let's revisit our roadmap at least once for every release and revise it if necessary.

Update ROADMAP per v0.9.4

---

README.md

Update file paths in readme

---

core/controlplane/config/config.go
core/nodepool/config/config.go
e2e/run
test/integration/maincluster_test.go

Allow disabling wait signals

---

core/controlplane/config/templates/stack-template.json
test/integration/maincluster_test.go

fix: etcdDataVolumeEncrypted not creating encrypted volumes

---

model/derived/etcd_cluster_test.go
model/region.go

Fix assumed public hostnames for EC2 instances in us-east-1

---

core/controlplane/config/templates/cloud-config-etcd

Stop locksmithd errors on etcd nodes

---

coreos/amiregistry/amiregistry.go
coreos/amiregistry/reliable_http.go
coreos/amiregistry/reliable_http_test.go

Make Container Linux AMI fetching a bit more reliable

---

core/controlplane/cluster/cluster_test.go
core/controlplane/config/config.go
core/controlplane/config/config_test.go
core/root/config/config.go
e2e/run
model/asg.go
model/controller.go
model/etcd.go
model/node_pool_config.go
model/spot_fleet.go
model/unknown_keys.go
model/unknown_keys_test.go
test/integration/maincluster_test.go

Emit errors when kube-aws sees unexpected keys in cluster.yaml

---

DCO

Add the missing DCO

---

core/controlplane/cluster/cluster.go
core/controlplane/cluster/cluster_test.go
core/controlplane/config/stack_config.go
core/controlplane/config/templates/stack-template.json
core/nodepool/cluster/cluster.go
core/nodepool/cluster/cluster_test.go
core/nodepool/config/stack_config.go
core/nodepool/config/templates/stack-template.json
fingerprint/sha256.go
fingerprint/sha256_test.go

Repair CF rollbacks to work after the S3 userdata improvement

---

cmd/render.go
core/controlplane/config/credential.go
core/controlplane/config/encryption.go
core/controlplane/config/tls_config.go
core/controlplane/config/tls_config_test.go
core/controlplane/config/token_config.go
core/controlplane/config/token_config_test.go
core/controlplane/config/user_data_config_test.go
core/root/render/credentials.go
test/helper/helper.go

Automatic invalidations of *.enc files

---

core/controlplane/config/config.go

Make node labels ordering stable

---

core/controlplane/config/config.go

fix https://github.com/projectcalico/k8s-policy/issues/81

bump policy-controller to v0.5.4

---

contrib/bump-version
core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile

Upgrade k8s version, which solves a security issue- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v155

K8s v1.5.5

---

coreos/amiregistry/reliable_http.go
coreos/amiregistry/reliable_http_test.go

Retry on 504 errors when fetching Container Linux AMIs

---

core/controlplane/config/config.go
test/integration/aws_test.go
test/integration/maincluster_test.go

Add a validation to clusterName

---

Documentation/kube-aws-cluster-updates.md
Documentation/kubernetes-on-aws-add-ons.md
Documentation/kubernetes-on-aws-launch.md
Documentation/kubernetes-on-aws-node-pool.md
Documentation/kubernetes-on-aws-prerequisites.md
Documentation/kubernetes-on-aws-render.md
Documentation/kubernetes-on-aws.md
README.md

Add documentation about kube2iam support

---

core/controlplane/config/credential.go

Fix a panic on a kms encryption failure

---

Documentation/kubernetes-on-aws-limitations.md
Documentation/kubernetes-on-aws-node-pool.md
Documentation/kubernetes-on-aws-prerequisites.md
Documentation/kubernetes-on-aws.md
README.md
ROADMAP.md
build
core/controlplane/config/templates/cluster.yaml
e2e/run
glide.yaml

Bug fixes after https://github.com/kubernetes-incubator/kube-aws/pull/451.
Currently on master e2e tests fail and possibly the build will not be the correct package.

Fix references to coreos/kube-aws

---

cfnstack/provisioner.go
core/controlplane/cluster/cluster.go
core/nodepool/cluster/cluster.go
core/root/cluster.go

Stop uploading redundant stack.json to S3

---

core/controlplane/config/config.go

If we set
```
ManageCertificates: false
```
the method ```HasTokens``` is not resolvable to evaluate the expression
```
{{ if .AuthTokensConfig.HasTokens }}
```
since the ```AuthTokensConfig``` type is not initialised.
_Error message:_
```
executing "userdata/cloud-config-controller" at <.AuthTokensConfig.Ha...>: can't evaluate field HasTokens in type *config.CompactAuthTokens
```
**Fix implemented**: put the initialization of the auth token file asset outside of that ```if c.ManageCertificates```

Initialize Config.AuthTokensConfig

---

Documentation/kubernetes-on-aws-render.md
cmd/render.go
core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml
core/controlplane/config/token_config.go
core/controlplane/config/token_config_test.go
core/controlplane/config/user_data_config_test.go
core/root/render/credentials.go
test/helper/helper.go
test/integration/maincluster_test.go

~~This is mostly done (I still want to add a few more tests to newly added code though), so it's pretty much ready to be reviewed.~~
You guys should be able to review this one commit at a time; I tried to be careful to explain the reasons behind each change. Ask me if something is not clear.
/cc @mumoshu @c-knowles 
Closes #484.

Improve auth tokens / TLS bootstrapping UX

---

coreos/amiregistry/reliable_http.go

Make AMI fetching even more reliable

---

core/controlplane/config/templates/stack-template.json
core/nodepool/config/templates/stack-template.json

Retry userdata download

---

core/controlplane/config/templates/cloud-config-etcd

Fix a race between systemd services: cfn-etc-environment and etcdadm-reconfigure

---

core/root/config/config.go

Ref https://github.com/kubernetes-incubator/kube-aws/issues/520#issuecomment-292885972
cc @c-knowles

Fix incorrect validations on apiEndpoints

---

core/controlplane/config/templates/cloud-config-controller

Wait until kube-system becomes ready

---

core/nodepool/config/deployment.go
test/integration/maincluster_test.go

Fix elasticFileSystemId to be propagated to node pools

---

core/controlplane/config/templates/cloud-config-etcd

when wait signal is enabled.
Resolves #525

Fix the dead-lock while bootstrapping etcd cluster

---

Documentation/kubernetes-on-aws-backup-and-restore-for-etcd.md
README.md
e2e/run
etcdadm/README.md

Add documentation for administrating etcd cluster

---

core/controlplane/config/templates/cloud-config-etcd

nothing major, just small nits found while moving to new master

Minor fixup for etcd unit files

---

core/controlplane/cluster/cluster_test.go
core/controlplane/config/config.go
core/controlplane/config/templates/stack-template.json
test/integration/maincluster_test.go

Fix unwanted AWS resource creation/Add extra validation on internetGatewayID + vpcID

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cloud-config-worker
model/taint.go
test/integration/maincluster_test.go

Update kubelet flags

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
e2e/run
test/integration/maincluster_test.go

Fix no space left on device when audit loggin enabled for apiserver

---

core/controlplane/config/templates/cloud-config-controller

Fix syntax error

---

core/controlplane/config/templates/cloud-config-worker

Fix certs path when TLS bootstrapping is enabled

---

Documentation/kubernetes-on-aws-backup.md

https://github.com/kubernetes-incubator/kube-aws/issues/591

Additional notes for autosave regarding s3 error

---

core/controlplane/config/templates/cluster.yaml
core/nodepool/config/config.go
core/nodepool/config/deployment.go
test/integration/maincluster_test.go

Fix elasticFileSystemId only on node pools

---

model/spot_fleet.go
test/integration/maincluster_test.go

Fix IamFleetRole syntax

---

core/controlplane/config/templates/cluster.yaml

Changing the number of etcd nodes after the first creation is not supported.
Ref #631

cluster.yaml: Additional note for etcd.count

---

etcdadm/etcdadm

adding --rm to docker run aws_cli commands in etcdadm

---

contrib/bump-version
core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cluster.yaml
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile

* update kubernetes version to v1.6.3
* update kubernetes dashboard version to 1.6.0
* update calico
* update addon-resizer to 1.7
* update dex version to 2.4.1
* update custom flannel image to v0.7.1
* remove deprecated flag "--mode=linear" in
"cluster-proportional-autoscaler". Parameters in ConfigMap must be JSON
and use linear as key.

Update versions for various components.

---

core/controlplane/config/templates/cloud-config-controller

Label masters with 'node-role.kubernetes.io/master' label

---

core/controlplane/config/templates/cloud-config-controller

Fix taint being assigned as labels

---

make/test

Make `go test` timeout longer enough for Travis

---

core/controlplane/config/templates/cloud-config-controller

For https://github.com/kubernetes-incubator/kube-aws/issues/685

Apply heapster RBAC setup properly

---

README.md

Introduce kube-aws slack channel in README

---

core/controlplane/config/config.go

Fix the issue that cluster-autoscaler never scale-down the cluster

---

core/controlplane/config/templates/cluster.yaml

* Change confusing example for controller nodeLabels
* Remove outdated and scary statement for rbac enablement

Enhance cluster.yaml documentation

---

core/controlplane/config/templates/cloud-config-controller

Add critical-pod annotation to CA

---

core/controlplane/config/templates/cloud-config-controller

Add CA a CriticalAddonsOnly toleration

---

.travis.yml
containerized-build-release-binaries

Update golang to v1.8.3

---

core/controlplane/config/templates/cloud-config-controller

Install Tiller by default

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cluster.yaml

Update CA to 0.6.0

---

core/controlplane/config/templates/cluster.yaml
etcdadm/README.md
etcdadm/etcdadm
etcdadm/test
model/etcd.go

Update the default etcd version to 3.2.1

---

contrib/bump-version
core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cluster.yaml
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile

Update Kubernetes to v1.7.0

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-worker
core/controlplane/config/templates/cluster.yaml
core/nodepool/config/config.go
e2e/run
model/controller.go
model/node_pool_config.go
model/node_settings.go
test/integration/maincluster_test.go

Closes #578
This is verified manually by running E2E

Rename experimental.nodeLabels to controller.nodeLabels

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-worker
core/controlplane/config/templates/cluster.yaml
core/nodepool/config/config.go
core/root/config/config.go
e2e/run
model/controller.go
model/node_pool_config.go
model/node_settings.go
test/integration/maincluster_test.go

This PR depends on #755. Please see the last commit for changes made solely in this PR.
Resolves #754
This is verified manually by running E2E

Explicitly disallow tainting controller nodes

---

core/nodepool/config/config.go
model/controller.go
model/node_pool_config.go
model/node_settings.go
test/integration/maincluster_test.go

Fix node labeling to allow scheduling cluster-autoscaler to workers

---

core/controlplane/config/config.go
core/nodepool/config/config.go
core/nodepool/config/deployment.go
core/nodepool/config/worker.go
core/root/config/config.go
model/asg.go
model/controller.go
model/gpu.go
model/lauch_specification.go
model/node_drainer.go
model/node_drainer_test.go
model/node_pool_config.go
model/node_settings.go
model/spot_fleet.go
model/taint.go
model/taint_test.go

Use consistent names for validation functions

---

contrib/bump-version
core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile

This won't work until v1.7.1+coreos.0 is released by CoreOS: https://github.com/coreos/kubernetes/releases
Closes #766

Update Kubernetes to v1.7.1

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cloud-config-worker
core/controlplane/config/templates/cluster.yaml
core/nodepool/config/deployment.go
core/root/template_params.go

Workaround fix for https://github.com/kubernetes/kubernetes/issues/32749
Credit to @redbaron

Make PODs to resolve DNS names via locally running dnsmasq

---

core/controlplane/config/templates/cloud-config-controller

Fix for typo introduced in #792

---

contrib/bump-version
core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile

For https://github.com/kubernetes-incubator/kube-aws/issues/799

Bump default k8s to 1.7.2

---

core/controlplane/config/templates/cloud-config-controller

Introduced in https://github.com/kubernetes-incubator/kube-aws/pull/809.

Put kube2iam update strategy in the correct place

---

core/controlplane/config/templates/cloud-config-worker

Add Spot Fleet support for the automatic ALB target group attachment

---

Documentation/kubernetes-on-aws.md

When using MFA for the AWS Credentials, additional Env variable needs to be exported

Updating instructions for MFA token

---

cfnstack/assets.go

Fixed the typo in the Error message in the code

Fixed typo in the error message

---

contrib/bump-version
core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile

Bump default k8s to 1.7.3

---

Documentation/faq.md

Add AWS_PROFILE to FAQ

---

core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cloud-config-worker

Fix failing worker and controller nodes when Calico is enabled

---

contrib/bump-version
core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cluster.yaml

Also updated Heapster to v1.4.1.

Update kubernetes to v1.7.4

---

Makefile

The documentation site was published by running `make publish-docs` and is now live at https://kubernetes-incubator.github.io/kube-aws/
```
$ make publish-docs
if ! which gitbook; then npm install -g gitbook-cli; fi
/usr/local/bin/gitbook
if ! which gh-pages; then npm install -g gh-pages; fi
/usr/local/bin/gh-pages
gitbook install
info: installing 4 plugins using npm@3.9.2
info:
info: installing plugin "edit-link"
info: install plugin "edit-link" (*) from NPM with version 2.0.2
info: >> plugin "edit-link" installed with success
info:
info: installing plugin "prism"
info: install plugin "prism" (*) from NPM with version 2.2.1
info: >> plugin "prism" installed with success
info:
info: installing plugin "github"
info: install plugin "github" (*) from NPM with version 2.0.0
info: >> plugin …
```

Script the publishing process of the kube-aws documentation

---

hack/README.md
hack/relnote.go
make/test

The code quality is terrible but anyway, it worked for gathering the release note for v0.9.8-rc.1.
Resolves #857

Script release notes gathering

---

core/controlplane/config/encrypted_assets.go

Do not overwrite the tokens.csv file when re-rendering credentials

---

e2e/run

e2e: Add support for NodeAuthorizer

---

model/spot_fleet.go
test/integration/maincluster_test.go

Fix the spot fleet support not to use incorrect bid prices by default

---

core/nodepool/config/deployment.go
test/integration/maincluster_test.go

Fix node pool release channel

---

hack/relnote.go

* Also consider changes under `hack/`, `ci/`, `e2e/` to be categorized into the "Other changes" section of a release note
* Label an issue with "feature" to categorize it into the "Features" section

Improve the release note gathering script

---

e2e/run

e2e: Add support for toggling RBAC

---

core/controlplane/config/config.go
core/controlplane/config/config_test.go
core/controlplane/config/templates/cloud-config-controller

Do not allow enabling Node authorizer without RBAC

---

core/controlplane/config/templates/cluster.yaml

Fix a potential YAML parsing error in cluster.yaml

---

make/test

Fix test timeouts in CI

---

core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml
test/integration/maincluster_test.go

Drop the deprecated key `workerCount` in cluster.yaml

---

model/region.go

I found that the IAM partition and S3 endpoint used for the us-gov-west-1 region were incorrect.

Support deployment to AWS GovCloud

---

core/controlplane/config/templates/cloud-config-controller

Remove bashisms from kube autosaver, makes it work with posix SH

---

contrib/bump-version
core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile
vendor/github.com/aws/aws-sdk-go/CHANGELOG.md

See for details: https://github.com/coreos/kubernetes/issues/171

Rollback to 1.7.7 hyperkube image, as 1.7.8 is actually 1.9.0 alpha

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cluster.yaml

Kubernetes Dashboard 1.7 with RBAC and authentication.

---

core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml

Avoid creating empty secrets by kubernetes-dashboard-init container. Ref. https://github.com/kubernetes/dashboard/pull/2468

Update kubernetes-dashboard-init image.

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cluster.yaml

Ref. #978 #979 
e2e test results with istio deployed: https://scanner.heptio.com/4024f60c6b1535881b81328e952b4404/diagnostics/

Add support for the Initializers admission control.

---

contrib/bump-version
core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml
e2e/kubernetes/Dockerfile
e2e/kubernetes/Makefile

Tests from yesterday: https://scanner.heptio.com/4024f60c6b1535881b81328e952b4404/diagnostics/

Bump kubernetes version to 1.8.2.

---

core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml

Bump cluster-autoscaler version to v1.0.2

---

core/controlplane/config/templates/cloud-config-worker

Most of the services that use rkt containers had a command to perform some cleanup.
I've added the corresponding command to a service that was missing it, and also added some additional syntax to pre-existing commands in order to keep them consistent.

Add some additional cleanup to rkt containers

---

core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cloud-config-etcd
core/controlplane/config/templates/cloud-config-worker

Resolves #831
Depends on #1021 
Please see [the second commit](https://github.com/kubernetes-incubator/kube-aws/pull/1023/commits/88dd6511a1d81cc4583c7c0e5ef6587102599109) for reviewing changes independently from the PR this is dependent on.

Add support for S3 buckets with the default encryption enabled

---

docs/SUMMARY.md
docs/advanced-topics/high-availability.md
docs/cli-reference/README.md
docs/tutorials/quick-start.md

WIP since I ran through this guide and keep hitting `Invalid arn` messages during TLS bootstrap.

Quick start and high availability guides

---

core/controlplane/config/templates/cloud-config-controller

Fix install-kube-system when node drainer is enabled

---

core/controlplane/config/templates/stack-template.json
core/nodepool/config/templates/stack-template.json

Correct values for the `kubernetes.io/cluster/<Cluster ID>` tags

---

core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cluster.yaml
core/root/config/config.go
model/addons.go
test/integration/maincluster_test.go

Allow toggling Metrics Server installation

---

core/controlplane/config/templates/cloud-config-controller

Fix kubelet.service startup.

---

contrib/dex/README.md

Tidy up markdown, especially for pre-indented / fixed-width content, and a heading.
Thanks for this contribution @camilb! I didn't even know it was here. @mumoshu we should link to these contrib folders somewhere in the docs, like just a bullet-list on the 'add-ons' page or an extra 'Advanced Topics' page?

Tidy up markdown

---

docs/cli-reference/README.md
docs/getting-started/step-2-render.md
docs/tutorials/quick-start.md

Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1214

Fix documentation of s3-uri

---

core/controlplane/config/config.go
core/controlplane/config/templates/cluster.yaml

updating default version of https://github.com/kubernetes/dashboard because of this issue https://github.com/kubernetes/kops/issues/4745

update kubernetes-dashboard to 1.8.3

---

core/controlplane/config/templates/cloud-config-etcd

Fix etcd breakage due to strange systemd behavior

---

core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cloud-config-etcd
core/controlplane/config/templates/cloud-config-worker

Fixes #1278
Depends on #1281, but will be rebased and squashed after merging it.

Fix temporary kubelet.service failures

---

core/controlplane/config/config.go
core/controlplane/config/config_test.go
core/controlplane/config/templates/cluster.yaml
core/nodepool/config/config.go
core/nodepool/config/config_test.go
core/nodepool/config/deployment.go
core/nodepool/config/templates/stack-template.json
docs/getting-started/step-6-configure-add-ons.md
test/integration/maincluster_test.go

Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1215.
Also contains some additional tests, bug fix to AssumeRole and update to kiam 2.7.

kiam support improvements

---

core/etcd/config/templates/stack-template.json

append comma when necessary to the EtcdNodes range

---

model/derived/etcd_node.go

Use EtcdStackName for eni provider

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/root/config/templates/cluster.yaml
docs/advanced-topics/kubernetes-dashboard.md

templates: add boolean to make dashboard optional
Added disable flag to kubernetesDashboard to make the deployment optional
Fixes #1317

Added the ability to disable the dashboard

---

core/controlplane/config/templates/stack-template.json
core/etcd/config/templates/stack-template.json
core/nodepool/config/templates/stack-template.json

Matches the new network stack.

Tweak CloudFormation stack descriptions

---

core/etcd/config/templates/stack-template.json

https://github.com/kubernetes-incubator/kube-aws/issues/1342

Tag etcd volumes with names

---

core/controlplane/config/templates/cloud-config-controller

From https://github.com/kubernetes-incubator/kube-aws/pull/1319/files#diff-ef25536c536667a40b993d4d24ab7567R964, space causes the install-kube-system to fail:
`{kube-dns,kube-dns-autoscaler {{ if .KubernetesDashboard.Enabled }}`

Fix install-kube-system

---

core/controlplane/config/templates/cloud-config-controller
core/root/config/templates/cluster.yaml

Default controller manager limits

---

core/nodepool/config/templates/cloud-config-worker
core/nodepool/config/templates/stack-template.json
core/root/config/templates/cluster.yaml
model/ec2_instance.go
model/node_pool_config.go
model/raid0_mount.go
model/volume_mount.go
model/volume_mount_test.go

Resolves https://github.com/kubernetes-incubator/kube-aws/issues/1175.

Raid0 support

---

core/controlplane/config/templates/cloud-config-controller

Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1337

Update dashboard RBAC to match 1.8.3 requirements

---

core/root/config/templates/cluster.yaml

Towards https://github.com/kubernetes-incubator/kube-aws/issues/1209.
Basic instructions for now as I think we should wire a command to the existing logic, at least to print out the ID and if not to update the cluster.yaml.

Instructions for updating the AMI

---

README.md
cfnstack/provisioner.go
cmd/calculator.go
cmd/destroy.go
cmd/flag_util.go
cmd/init.go
cmd/render.go
cmd/root.go
cmd/show.go
cmd/status.go
cmd/up.go
cmd/update.go
cmd/validate.go
cmd/version.go
core/controlplane/cluster/cluster.go
core/controlplane/config/config.go
core/controlplane/config/credential.go
core/controlplane/config/encrypted_assets.go
core/etcd/cluster/cluster.go
core/network/cluster/cluster.go
core/nodepool/config/config.go
core/root/cluster.go
core/root/credentials.go
logger/color.go
logger/logger.go
model/gpu.go
model/node_pool_config.go
model/root_volume.go

- added logger to make logging more consistent (adds option to add common prefixes)
- added global options for silent, verbose and color messages (even though verbose is not used yet)

Consistent logging with options to silence, verbosify and color messages

---

core/controlplane/config/templates/stack-template.json

Fix duplicate controller role permissions for CloudWatch logging

---

.travis.yml
make/test

Bump go to 1.10.x for travis builds

---

core/nodepool/config/templates/cloud-config-worker
licenses/LICENSE.ebs-automatic-nvme-mapping
licenses/README.md

Add LICENSE for ebs-automatic-nvme-mapping

---

core/controlplane/config/templates/cloud-config-controller

Remove kube-system namespace out of kiam if statement

---

core/controlplane/config/config.go
core/controlplane/config/templates/cloud-config-controller
core/root/config/templates/cluster.yaml
test/integration/maincluster_test.go

Added in KIAM session timeout modifier

---

core/controlplane/config/config.go
core/controlplane/config/encrypted_assets.go
core/controlplane/config/encrypted_assets_test.go
core/controlplane/config/templates/cloud-config-controller
model/addons.go
test/helper/helper.go
test/integration/maincluster_test.go

Add api aggregator proxy certificate and enable on apiserver when the metrics server addon is enabled.

Add apiserver aggregator with certs when metrics server is enabled

---

core/controlplane/config/templates/cloud-config-controller
core/controlplane/config/templates/cloud-config-etcd
core/controlplane/config/templates/cloud-config-worker
model/custom_file.go
model/custom_file_test.go

Please can we also include this feature in the 0.10.x?

0.10.x Extend CustomFiles to be able to render go templates 

---

core/controlplane/config/templates/cloud-config-controller

After alpine:latest bad image started causing cluster roll issues.

0.10.x Remove dependency on alpine:latest

---

core/controlplane/config/encrypted_assets.go
core/controlplane/config/encrypted_assets_test.go
core/controlplane/config/templates/cloud-config-controller

fix: `encryptionAtRest: true` should not break controller nodes

---

core/controlplane/cluster/cluster.go
core/controlplane/cluster/cluster_test.go
core/controlplane/config/config.go
core/etcd/cluster/cluster.go
core/network/cluster/cluster.go
core/root/config/templates/cluster.yaml
model/cloudformation.go
model/stack_name_override.go
model/stack_name_overrides.go

See https://github.com/kubernetes-incubator/kube-aws/pull/1484 for details/comments

v0.11.x: feat: add CF stackNameOverride in cluster.yaml

---

cfnstack/cfnstack.go

This fix was PR'd to master and pulled into 0.11.x but is missing from 0.12.x which causes stacks to fail to validate in certain conditions.

Backport fix for StackExists behaviour into 0.12.x branch

---

builtin/files/cluster.yaml.tmpl
cmd/render.go
docs/add-ons/README.md
docs/add-ons/journald-logging-to-cloudwatch.md
docs/advanced-topics/README.md
docs/advanced-topics/cloudformation-updates-in-cli.md
docs/cli-reference/README.md
docs/getting-started/step-2-render.md
docs/getting-started/step-3-launch.md
docs/getting-started/step-4-update.md
docs/getting-started/step-5-add-node-pool.md
docs/tutorials/quick-start.md

Removing all references to the already removed kube-aws up/update commands

Removing all references to the already removed kube-aws up/update commands

---

builtin/files/cluster.yaml.tmpl
builtin/files/stack-templates/control-plane.json.tmpl
builtin/files/stack-templates/etcd.json.tmpl
builtin/files/stack-templates/network.json.tmpl
builtin/files/stack-templates/node-pool.json.tmpl
builtin/files/userdata/cloud-config-controller
filereader/texttemplate/texttemplate.go
pkg/api/cluster.go
pkg/api/subnet.go
pkg/api/subnets.go
pkg/model/stack.go
pkg/model/stack_new.go
pkg/model/types.go
test/integration/maincluster_test.go

Carry latest merges into the v0.13.x branch
Namely - stack subnets fix
Nat Gateway tagging
Kiam <3.0 support.

V0.13.0 rc.2 prep1

---

build
builtin/files/cluster.yaml.tmpl
builtin/files/etcdadm/README.md
builtin/files/etcdadm/test
builtin/files/userdata/cloud-config-controller
builtin/files/userdata/cloud-config-etcd
core/root/cluster.go
pkg/api/cluster.go
pkg/api/etcd.go
pkg/api/etcd_cluster.go
pkg/api/etcd_test.go
test/integration/maincluster_test.go

Remove support for Etcd v2
Bump default version to v3.2.26 (important bug fixes)

Etcd Upgrade

---

build
builtin/files/cluster.yaml.tmpl
builtin/files/etcdadm/README.md
builtin/files/etcdadm/test
builtin/files/userdata/cloud-config-controller
builtin/files/userdata/cloud-config-etcd
core/root/cluster.go
pkg/api/cluster.go
pkg/api/etcd.go
pkg/api/etcd_cluster.go
pkg/api/etcd_test.go
test/integration/maincluster_test.go

Cherry pick these changes into the 0.13.x branch

v0.13.0-rc.2

---

build
builtin/files/cluster.yaml.tmpl
builtin/files/etcdadm/README.md
builtin/files/etcdadm/test
builtin/files/stack-templates/control-plane.json.tmpl
builtin/files/stack-templates/etcd.json.tmpl
builtin/files/stack-templates/network.json.tmpl
builtin/files/stack-templates/node-pool.json.tmpl
builtin/files/userdata/cloud-config-controller
builtin/files/userdata/cloud-config-etcd
core/root/cluster.go
filereader/texttemplate/texttemplate.go
pkg/api/cluster.go
pkg/api/etcd.go
pkg/api/etcd_cluster.go
pkg/api/etcd_test.go
pkg/api/subnet.go
pkg/api/subnets.go
pkg/model/stack.go
pkg/model/stack_new.go
pkg/model/types.go
test/integration/maincluster_test.go

Bump K8s version to 1.14.2
Upgrade Etcd to 3.2.26
Pull a few fixes from master

v0.14.0-rc.2

---

builtin/files/cluster.yaml.tmpl
builtin/files/userdata/cloud-config-controller
pkg/api/cluster.go
pkg/api/types.go
pkg/model/cluster_test.go

- Allows a configurable TTL for CoreDNS.

Configurable CoreDNS TTL

---

builtin/files/cluster.yaml.tmpl
builtin/files/userdata/cloud-config-controller
pkg/api/cluster.go
pkg/api/types.go
test/integration/maincluster_test.go

And enabled by default but also allowing you to change the EventRateLimit settings yaml.

Make the EventRateLimit alpha admission controller experimental

---

OWNERS

- Adds @davidmccormick and @DominicGunn to owners so that @k8s-ci-robot is happy.

[0.13.x] Update OWNERS.

---

OWNERS

- Adds @davidmccormick and @dominicgunn to `OWNERS` to make

[0.14.x] Update OWNERS.

---

builtin/files/cluster.yaml.tmpl
builtin/files/etcdadm/etcdadm

* Update etcdadm
* Update cluster.yaml.tmpl

0.13.x Etcd version (#1646)

---

builtin/files/cluster.yaml.tmpl
builtin/files/etcdadm/etcdadm

* Update etcdadm
* Update cluster.yaml.tmpl

0.14.x Etcd version (#1646)

---

cfnresource/naming.go
cfnresource/naming_test.go
core/controlplane/config/config.go
core/nodepool/config/config.go

Cherry pick strict IAM Role name checking from master branch - missing from this branch

Correct IAM Role Namechecking in v0.12.x branch

---

builtin/files/userdata/cloud-config-controller

kiam-server port name changed from commit uswitch/kiam@ceb88e1
This PR is to reflect this change in the template

Change kiam-server 443 port name

---

builtin/files/userdata/cloud-config-controller

- resolve https://github.com/kubernetes-incubator/kube-aws/issues/1688
- modify podantiaffinity for coredns-deployment in https://github.com/kubernetes-incubator/kube-aws/pull/1671

Fix cloud-config-controller

---

builtin/files/plugins/dashboard/manifests/deployment.yaml

breaks apply of the dashboard plugin

Missing end

---

awsconn/awsconn.go
cmd/apply.go
cmd/calculator.go
cmd/destroy.go
cmd/diff.go
cmd/status.go
cmd/up.go
cmd/update.go
cmd/validate.go
core/root/cluster.go
core/root/describer.go
core/root/destroyer.go
core/root/options.go
docs/cli-reference/README.md

Add a new flag to command line utilities to allow to choose a AWS profile from the aws credentials file

Add flag to cmds to use AWS profile

---

pkg/api/cluster.go

Fix DisableContainerLinuxAutomaticUpdates data type

---

build
builtin/files/cluster.yaml.tmpl

- Bumps Kubernetes to the latest v1.16.x release.

[v0.16.0] Bump Kubernetes version

---

.travis.yml
go.mod

- designate go.mod with v1.14
- bump travis to use go 1.14

Bump golang to v1.14.3

---

core/controlplane/config/templates/cloud-config-controller
core/etcd/config/templates/cloud-config-etcd
core/nodepool/config/templates/cloud-config-worker

This a patch we added in our side other may benefit from. Feel free to reject as I know well is unmaintained.

[v0.12.x] [Unmaintained branch] Disable Flatcar auto-updates

---

builtin/files/cluster.yaml.tmpl
builtin/files/etcdadm/README.md
builtin/files/userdata/cloud-config-controller
builtin/files/userdata/cloud-config-etcd
builtin/files/userdata/cloud-config-worker
docs/cli-reference/README.md
docs/getting-started/step-2-render.md
docs/getting-started/step-4-update.md
docs/tutorials/quick-start.md

* use Flatcar in the v0.15.x branch, shamelessly stolen from @jorge07 and @dominicgunn, thanks!

[v0.15.0] Switch CoreOS to Flatcar

---

OWNERS
OWNERS_ALIASES
README.md

https://github.com/kubernetes/org/issues/2004

Update owners per k/org

---

builtin/files/userdata/cloud-config-controller

- Fixes a templating issue when CoreDNS Local is enabled.

[v0.14.x] CoreDNS Local Templating issue.
